import type {
  ReportFormat,
  ReportJobStatus,
  SupportedUiLocale,
} from '@tcrn/shared';
import { resolveTrilingualLocaleFamily } from '@tcrn/shared';

import { type RuntimeLocale, useRuntimeLocale } from '@/platform/runtime/locale/locale-provider';
import {
  formatLocaleDateTime,
  formatLocaleNumber,
  resolveLocaleRecord,
} from '@/platform/runtime/locale/locale-text';

type JobStatusFilter = 'all' | ReportJobStatus;

const COPY = {
  en: {
    state: {
      loadJobsError: 'Failed to load report jobs.',
      refreshJobsError: 'Failed to refresh report jobs.',
      previewError: 'Failed to preview the current MFR filters.',
      piiPortalHandoffPrefix: 'Report ready with',
      piiPortalHandoffSuffix: 'matched customers.',
      createLocalJobPrefix: 'MFR job',
      createLocalJobSuffix: 'was queued with an estimated',
      createLocalJobRowsSuffix: 'rows.',
      createJobError: 'Failed to create the MFR job.',
      downloadOpenedPrefix: 'Download opened for',
      downloadOpenedFallback: 'the selected report',
      downloadError: 'Failed to prepare the report download.',
      cancelError: 'Failed to cancel the selected report job.',
      cancelSuccessFallback: 'The selected job',
      cancelSuccessSuffix: 'was cancelled.',
    },
    header: {
      eyebrow: 'Reports',
      title: 'Reports Management',
      description: 'Preview, queue, cancel, and download Member Feedback Report jobs.',
      workspaceSettings: 'Talent settings',
      draftJob: 'Draft MFR job',
      refreshJobs: 'Refresh jobs',
    },
    summary: {
      tenantLabel: 'Tenant',
      tenantFallback: 'Tenant',
      tenantHint: 'Current tenant context.',
      reportLabel: 'Report',
      reportName: 'Member Feedback Report',
      reportDescription: 'Export member feedback data.',
      jobsLabel: 'Jobs',
      jobsLoading: '…',
      jobsHint: 'Current talent-scoped MFR jobs.',
      activeDownloadableLabel: 'Active / Downloadable',
      activeDownloadableHint: 'Counts from the currently loaded page.',
    },
    portal: {
      badge: 'Download link',
      title: 'Download link ready',
      description:
        'This report is available through a linked download page. Open the link below before it expires.',
      expiresPrefix: 'Expires at',
      estimatedPrefix: 'with an estimated',
      estimatedSuffix: 'rows.',
      openPlatform: 'Open link',
    },
    preview: {
      title: 'Preview',
      description: 'Preview matches use the current MFR job draft and return a small sample of the result set.',
      unavailableTitle: 'Preview unavailable',
      matchedRowsLabel: 'Matched Rows',
      matchedRowsHint: 'Estimated row count before queueing.',
      platformsLabel: 'Platforms',
      allPlatforms: 'All',
      platformsHint: 'Filter summary from the API response.',
      dateRangeLabel: 'Date Range',
      dateRangeUnbounded: 'Unbounded',
      includeExpiredHint: 'Expired memberships included.',
      excludeExpiredHint: 'Expired memberships excluded.',
      tableColumns: ['Nickname', 'Platform', 'Membership Level', 'Valid Window', 'Status'],
      emptyTitle: 'No MFR rows matched',
      emptyDescription: 'Adjust the filter draft and run another preview.',
      noPreviewTitle: 'No preview requested yet',
      noPreviewDescription: 'Open the MFR job drawer to preview matched rows before queueing a new report job.',
      unnamedCustomer: 'Unnamed customer',
      openEnded: 'open-ended',
    },
    ledger: {
      title: 'MFR jobs',
      description: 'Track queued jobs, cancel eligible requests, and download completed files.',
      filterLabel: 'Job status filter',
      showingPrefix: 'Showing',
      showingJobsSuffix: 'jobs on the current page,',
      showingTotalSuffix: 'in total.',
      unavailableTitle: 'Report jobs unavailable',
      tableColumns: ['File', 'Status', 'Rows', 'Requested', 'Completed', 'Actions'],
      emptyTitle: 'No MFR jobs found',
      emptyDescription: 'Queue a new MFR export or widen the status filter.',
      pendingFileAssignment: 'Pending file assignment',
      pendingRows: 'Pending',
      download: 'Download',
      cancel: 'Cancel',
      cancelDialogTitle: 'Cancel report job?',
      cancelDialogDescription:
        'Only pending or failed jobs can be cancelled. This removes the job from the current queue.',
      cancelDialogConfirm: 'Cancel job',
      downloadAriaLabel: (label: string) => `Download ${label}`,
      cancelAriaLabel: (label: string) => `Cancel ${label}`,
    },
    notes: {
      title: 'Report Notes',
      description: 'Review the current report target and download path.',
      scopeLabel: 'Scope',
      scopeValue: 'MFR',
      scopeHint: 'Member Feedback Report is currently available for the current talent scope.',
      sensitiveDeliveryLabel: 'Delivery',
      sensitiveDeliveryValue: 'Linked download',
      sensitiveDeliveryHint: 'When a download link is available, this report opens there instead of downloading directly on this page.',
      workflowLabel: 'Workflow',
      workflowValue: 'Single flow',
      workflowHint: 'Preview, queueing, confirmation, and downloads are handled on this page.',
    },
    drawer: {
      title: 'Create MFR Job',
      description: 'Queue a new member-feedback export with optional scope filters. Preview uses the same draft state as job creation.',
      cancel: 'Cancel',
      closeLabel: 'Close MFR job drawer',
      previewRows: 'Preview rows',
      createPending: 'Queueing MFR job…',
      create: 'Create MFR job',
      fields: {
        platformCodes: 'Platform codes',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: 'Membership class codes',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: 'Membership type codes',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: 'Membership level codes',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: 'Customer status codes',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: 'Download format',
        validFromStart: 'Valid-from start',
        validFromEnd: 'Valid-from end',
        validToStart: 'Valid-to start',
        validToEnd: 'Valid-to end',
        includeExpired: 'Include expired memberships',
        includeInactive: 'Include inactive memberships',
      },
    },
    options: {
      jobStatus: {
        all: 'All statuses',
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
      reportFormat: {
        xlsx: 'Excel (.xlsx)',
        csv: 'CSV (.csv)',
      },
      jobState: {
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
    },
    common: {
      never: 'Never',
    },
  },
  zh: {
    state: {
      loadJobsError: '加载报表任务失败。',
      refreshJobsError: '刷新报表任务失败。',
      previewError: '预览当前 MFR 筛选失败。',
      piiPortalHandoffPrefix: '报表已就绪，匹配到',
      piiPortalHandoffSuffix: '位客户。',
      createLocalJobPrefix: 'MFR 任务',
      createLocalJobSuffix: '已排队，预计',
      createLocalJobRowsSuffix: '行。',
      createJobError: '创建 MFR 任务失败。',
      downloadOpenedPrefix: '已打开下载：',
      downloadOpenedFallback: '所选报表',
      downloadError: '准备报表下载失败。',
      cancelError: '取消所选报表任务失败。',
      cancelSuccessFallback: '所选任务',
      cancelSuccessSuffix: '已取消。',
    },
    header: {
      eyebrow: '报表',
      title: '报表管理',
      description: '预览、排队、取消并下载会员反馈报表任务。',
      workspaceSettings: '艺人设置',
      draftJob: '起草 MFR 任务',
      refreshJobs: '刷新任务',
    },
    summary: {
      tenantLabel: '租户',
      tenantFallback: '当前租户',
      tenantHint: '当前租户上下文。',
      reportLabel: '报表',
      reportName: '会员反馈报表',
      reportDescription: '导出会员反馈数据。',
      jobsLabel: '任务数',
      jobsLoading: '…',
      jobsHint: '当前艺人范围内的 MFR 任务。',
      activeDownloadableLabel: '进行中 / 可下载',
      activeDownloadableHint: '基于当前已加载页面的统计。',
    },
    portal: {
      badge: '下载链接',
      title: '下载链接已就绪',
      description: '该报表通过外部下载链接提供。请在链接过期前打开并完成下载。',
      expiresPrefix: '过期时间',
      estimatedPrefix: '预计',
      estimatedSuffix: '行。',
      openPlatform: '打开链接',
    },
    preview: {
      title: '预览',
      description: '预览使用当前 MFR 任务草稿，并返回一小部分结果样本。',
      unavailableTitle: '预览不可用',
      matchedRowsLabel: '匹配行数',
      matchedRowsHint: '排队前的预估行数。',
      platformsLabel: '平台',
      allPlatforms: '全部',
      platformsHint: '来自 API 响应的筛选摘要。',
      dateRangeLabel: '时间范围',
      dateRangeUnbounded: '不限制',
      includeExpiredHint: '包含已过期会员。',
      excludeExpiredHint: '不包含已过期会员。',
      tableColumns: ['昵称', '平台', '会员等级', '有效期', '状态'],
      emptyTitle: '没有匹配到 MFR 行',
      emptyDescription: '请调整筛选草稿后重新预览。',
      noPreviewTitle: '尚未请求预览',
      noPreviewDescription: '先打开 MFR 任务抽屉预览匹配行，再决定是否创建报表任务。',
      unnamedCustomer: '未命名客户',
      openEnded: '未设结束时间',
    },
    ledger: {
      title: 'MFR 任务',
      description: '跟踪当前页的排队任务，取消可取消请求，并下载已完成产物。',
      filterLabel: '任务状态筛选',
      showingPrefix: '当前页显示',
      showingJobsSuffix: '个任务，总计',
      showingTotalSuffix: '个。',
      unavailableTitle: '报表任务不可用',
      tableColumns: ['文件', '状态', '行数', '请求时间', '完成时间', '操作'],
      emptyTitle: '没有找到 MFR 任务',
      emptyDescription: '创建新的 MFR 导出任务，或放宽状态筛选条件。',
      pendingFileAssignment: '等待分配文件名',
      pendingRows: '处理中',
      download: '下载',
      cancel: '取消',
      cancelDialogTitle: '取消报表任务？',
      cancelDialogDescription: '只有待处理或失败的任务可以取消，该操作会将任务移出当前队列。',
      cancelDialogConfirm: '取消任务',
      downloadAriaLabel: (label: string) => `下载 ${label}`,
      cancelAriaLabel: (label: string) => `取消 ${label}`,
    },
    notes: {
      title: '报表说明',
      description: '查看当前报表的作用域与下载方式。',
      scopeLabel: '范围',
      scopeValue: 'MFR',
      scopeHint: '当前艺人范围可用的报表为会员反馈报表。',
      sensitiveDeliveryLabel: '下载方式',
      sensitiveDeliveryValue: '外部链接',
      sensitiveDeliveryHint: '当下载链接可用时，报表会通过该链接打开，而不是在当前页直接下载。',
      workflowLabel: '工作流',
      workflowValue: '统一流程',
      workflowHint: '预览、排队、确认和下载都在同一处完成。',
    },
    drawer: {
      title: '创建 MFR 任务',
      description: '可带可选范围筛选创建新的会员反馈导出任务，预览与创建共享同一份草稿状态。',
      cancel: '取消',
      closeLabel: '关闭 MFR 任务抽屉',
      previewRows: '预览结果',
      createPending: 'MFR 任务排队中…',
      create: '创建 MFR 任务',
      fields: {
        platformCodes: '平台代码',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: '会员分类代码',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: '会员类型代码',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: '会员等级代码',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: '客户状态代码',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: '下载格式',
        validFromStart: '有效期开始（起）',
        validFromEnd: '有效期开始（止）',
        validToStart: '有效期结束（起）',
        validToEnd: '有效期结束（止）',
        includeExpired: '包含已过期会员',
        includeInactive: '包含未激活会员',
      },
    },
    options: {
      jobStatus: {
        all: '全部状态',
        pending: '待处理',
        running: '运行中',
        retrying: '重试中',
        success: '成功',
        consumed: '已消费',
        failed: '失败',
        expired: '已过期',
        cancelled: '已取消',
      },
      reportFormat: {
        xlsx: 'Excel（.xlsx）',
        csv: 'CSV（.csv）',
      },
      jobState: {
        pending: '待处理',
        running: '运行中',
        retrying: '重试中',
        success: '成功',
        consumed: '已消费',
        failed: '失败',
        expired: '已过期',
        cancelled: '已取消',
      },
    },
    common: {
      never: '从未',
    },
  },
  ja: {
    state: {
      loadJobsError: 'レポートジョブ台帳の読み込みに失敗しました。',
      refreshJobsError: 'レポートジョブ台帳の更新に失敗しました。',
      previewError: '現在の MFR フィルターのプレビューに失敗しました。',
      piiPortalHandoffPrefix: 'レポートの準備が完了し、',
      piiPortalHandoffSuffix: '人の顧客が一致しました。',
      createLocalJobPrefix: 'MFR ジョブ',
      createLocalJobSuffix: 'をキューに追加しました。推定',
      createLocalJobRowsSuffix: '行です。',
      createJobError: 'MFR ジョブの作成に失敗しました。',
      downloadOpenedPrefix: 'ダウンロードを開きました:',
      downloadOpenedFallback: '選択したレポート',
      downloadError: 'レポートダウンロードの準備に失敗しました。',
      cancelError: '選択したレポートジョブのキャンセルに失敗しました。',
      cancelSuccessFallback: '選択したジョブ',
      cancelSuccessSuffix: 'をキャンセルしました。',
    },
    header: {
      eyebrow: 'レポート',
      title: 'レポート管理',
      description: '会員フィードバックレポートのプレビュー、キュー投入、キャンセル、ダウンロードを行います。',
      workspaceSettings: 'タレント設定',
      draftJob: 'MFR ジョブを起票',
      refreshJobs: 'ジョブを更新',
    },
    summary: {
      tenantLabel: 'テナント',
      tenantFallback: '現在のテナント',
      tenantHint: '現在のテナントコンテキストです。',
      reportLabel: 'レポート',
      reportName: '会員フィードバックレポート',
      reportDescription: '会員フィードバックデータをエクスポートします。',
      jobsLabel: 'ジョブ数',
      jobsLoading: '…',
      jobsHint: '現在のタレント範囲における MFR ジョブです。',
      activeDownloadableLabel: '進行中 / ダウンロード可',
      activeDownloadableHint: '現在読み込まれているページの件数です。',
    },
    portal: {
      badge: 'ダウンロードリンク',
      title: 'ダウンロードリンクの準備完了',
      description:
        'このレポートは外部ダウンロードリンクで受け取ります。期限切れ前に以下のリンクを開いてください。',
      expiresPrefix: '有効期限',
      estimatedPrefix: '推定',
      estimatedSuffix: '行です。',
      openPlatform: 'リンクを開く',
    },
    preview: {
      title: 'プレビュー',
      description: 'プレビューは現在の MFR ジョブ草稿を使い、結果セットの一部サンプルを返します。',
      unavailableTitle: 'プレビューを利用できません',
      matchedRowsLabel: '一致行数',
      matchedRowsHint: 'キュー投入前の推定行数です。',
      platformsLabel: 'プラットフォーム',
      allPlatforms: 'すべて',
      platformsHint: 'API 応答のフィルター要約です。',
      dateRangeLabel: '期間',
      dateRangeUnbounded: '無制限',
      includeExpiredHint: '期限切れ会員を含みます。',
      excludeExpiredHint: '期限切れ会員を含みません。',
      tableColumns: ['ニックネーム', 'プラットフォーム', '会員レベル', '有効期間', '状態'],
      emptyTitle: '一致する MFR 行はありません',
      emptyDescription: 'フィルター草稿を調整して、もう一度プレビューしてください。',
      noPreviewTitle: 'まだプレビューは要求されていません',
      noPreviewDescription: 'まず MFR ジョブドロワーを開き、一致行を確認してからレポートジョブを作成してください。',
      unnamedCustomer: '名称未設定の顧客',
      openEnded: '終了日なし',
    },
    ledger: {
      title: 'MFR ジョブ',
      description: '現在ページのキュー済みジョブを追跡し、取消可能な要求を停止し、完了済み成果物をダウンロードします。',
      filterLabel: 'ジョブ状態フィルター',
      showingPrefix: '現在のページに',
      showingJobsSuffix: '件表示、合計',
      showingTotalSuffix: '件です。',
      unavailableTitle: 'レポートジョブを利用できません',
      tableColumns: ['ファイル', '状態', '行数', '要求日時', '完了日時', '操作'],
      emptyTitle: 'MFR ジョブが見つかりません',
      emptyDescription: '新しい MFR エクスポートを作成するか、状態フィルターを広げてください。',
      pendingFileAssignment: 'ファイル名割当待ち',
      pendingRows: '保留',
      download: 'ダウンロード',
      cancel: 'キャンセル',
      cancelDialogTitle: 'レポートジョブをキャンセルしますか？',
      cancelDialogDescription:
        '保留中または失敗したジョブのみキャンセルできます。これにより、ジョブは現在のキューから除外されます。',
      cancelDialogConfirm: 'ジョブをキャンセル',
      downloadAriaLabel: (label: string) => `${label} をダウンロード`,
      cancelAriaLabel: (label: string) => `${label} をキャンセル`,
    },
    notes: {
      title: 'レポートメモ',
      description: 'このレポートの現在のスコープとダウンロード経路を確認します。',
      scopeLabel: 'スコープ',
      scopeValue: 'MFR',
      scopeHint: '現在のタレント範囲では会員フィードバックレポートを利用できます。',
      sensitiveDeliveryLabel: 'ダウンロード方式',
      sensitiveDeliveryValue: 'リンクダウンロード',
      sensitiveDeliveryHint: 'ダウンロードリンクが利用できる場合、このページで直接ダウンロードする代わりにリンク先を開きます。',
      workflowLabel: 'ワークフロー',
      workflowValue: '単一フロー',
      workflowHint: 'プレビュー、キュー投入、確認、ダウンロードが一箇所で完結します。',
    },
    drawer: {
      title: 'MFR ジョブを作成',
      description: '任意のスコープフィルター付きで新しい会員フィードバックエクスポートを作成します。プレビューはジョブ作成と同じ草稿状態を使用します。',
      cancel: 'キャンセル',
      closeLabel: 'MFR ジョブドロワーを閉じる',
      previewRows: '行をプレビュー',
      createPending: 'MFR ジョブをキュー中…',
      create: 'MFR ジョブを作成',
      fields: {
        platformCodes: 'プラットフォームコード',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: '会員クラスコード',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: '会員タイプコード',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: '会員レベルコード',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: '顧客状態コード',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: 'ダウンロード形式',
        validFromStart: '有効開始（開始）',
        validFromEnd: '有効開始（終了）',
        validToStart: '有効終了（開始）',
        validToEnd: '有効終了（終了）',
        includeExpired: '期限切れ会員を含める',
        includeInactive: '非アクティブ会員を含める',
      },
    },
    options: {
      jobStatus: {
        all: 'すべての状態',
        pending: '保留',
        running: '実行中',
        retrying: '再試行中',
        success: '成功',
        consumed: '消費済み',
        failed: '失敗',
        expired: '期限切れ',
        cancelled: 'キャンセル済み',
      },
      reportFormat: {
        xlsx: 'Excel (.xlsx)',
        csv: 'CSV (.csv)',
      },
      jobState: {
        pending: '保留',
        running: '実行中',
        retrying: '再試行中',
        success: '成功',
        consumed: '消費済み',
        failed: '失敗',
        expired: '期限切れ',
        cancelled: 'キャンセル済み',
      },
    },
    common: {
      never: '未実施',
    },
  },
} as const;

export type ReportsManagementCopy = (typeof COPY)['en'];
const COPY_BY_LOCALE = COPY as unknown as Record<RuntimeLocale, ReportsManagementCopy>;

function getEffectiveSelectedLocale(
  currentLocale: RuntimeLocale,
  selectedLocale: SupportedUiLocale | undefined,
): SupportedUiLocale {
  if (selectedLocale && resolveTrilingualLocaleFamily(selectedLocale) === currentLocale) {
    return selectedLocale;
  }

  return currentLocale === 'zh' ? 'zh_HANS' : currentLocale;
}

export function useReportsManagementCopy() {
  const { currentLocale, selectedLocale } = useRuntimeLocale();
  const effectiveSelectedLocale = getEffectiveSelectedLocale(currentLocale, selectedLocale);
  const copy = resolveLocaleRecord(effectiveSelectedLocale, COPY_BY_LOCALE, currentLocale) as ReportsManagementCopy;

  return {
    currentLocale,
    selectedLocale: effectiveSelectedLocale,
    copy,
    jobStatusOptions: [
      { value: 'all' as JobStatusFilter, label: copy.options.jobStatus.all },
      { value: 'pending' as JobStatusFilter, label: copy.options.jobStatus.pending },
      { value: 'running' as JobStatusFilter, label: copy.options.jobStatus.running },
      { value: 'retrying' as JobStatusFilter, label: copy.options.jobStatus.retrying },
      { value: 'success' as JobStatusFilter, label: copy.options.jobStatus.success },
      { value: 'consumed' as JobStatusFilter, label: copy.options.jobStatus.consumed },
      { value: 'failed' as JobStatusFilter, label: copy.options.jobStatus.failed },
      { value: 'expired' as JobStatusFilter, label: copy.options.jobStatus.expired },
      { value: 'cancelled' as JobStatusFilter, label: copy.options.jobStatus.cancelled },
    ],
    reportFormatOptions: [
      { value: 'xlsx' as ReportFormat, label: copy.options.reportFormat.xlsx },
      { value: 'csv' as ReportFormat, label: copy.options.reportFormat.csv },
    ],
  };
}

export function formatReportsDateTime(
  locale: SupportedUiLocale | RuntimeLocale,
  value: string | null,
  fallback: string,
) {
  return formatLocaleDateTime(locale, value, fallback);
}

export function formatReportsNumber(
  locale: SupportedUiLocale | RuntimeLocale,
  value: number | null,
  pendingLabel: string,
) {
  if (value === null) {
    return pendingLabel;
  }

  return formatLocaleNumber(locale, value);
}

export function getReportsJobStatusLabel(
  locale: SupportedUiLocale | RuntimeLocale,
  status: ReportJobStatus,
) {
  return (resolveLocaleRecord(locale, COPY_BY_LOCALE) as ReportsManagementCopy).options.jobState[status];
}
