import type {
  ReportFormat,
  ReportJobStatus,
  SupportedUiLocale,
} from '@tcrn/shared';

import { useUiLocale } from '@/platform/runtime/locale/locale-provider';
import {
  formatLocaleDateTime,
  formatLocaleNumber,
  resolveLocaleRecord,
} from '@/platform/runtime/locale/locale-text';

type JobStatusFilter = 'all' | ReportJobStatus;

const COPY = {
  en: {
    state: {
      loadCatalogError: 'Failed to load the report catalog.',
      loadJobsError: 'Failed to load report jobs.',
      refreshJobsError: 'Failed to refresh report jobs.',
      previewError: 'Failed to preview the current MFR filters.',
      loadJobDetailError: 'Failed to load report job detail.',
      piiPortalHandoffPrefix: 'Report ready with',
      piiPortalHandoffSuffix: 'matched customers.',
      createLocalJobPrefix: 'MFR job',
      createLocalJobSuffix: 'was queued with an estimated',
      createLocalJobRowsSuffix: 'rows.',
      createJobError: 'Failed to create the MFR job.',
      downloadOpenedPrefix: 'Download opened for',
      downloadOpenedFallback: 'the selected report',
      downloadError: 'Failed to prepare the report download.',
      cancelError: 'Failed to cancel the selected report job.',
      cancelSuccessFallback: 'The selected job',
      cancelSuccessSuffix: 'was cancelled.',
    },
    header: {
      eyebrow: 'Reports',
      title: 'Reports Management',
      description: 'Browse available reports, draft exports, and review run history for the current talent scope.',
      workspaceSettings: 'Talent settings',
      draftJob: 'Draft report',
      refreshJobs: 'Refresh jobs',
    },
    summary: {
      tenantLabel: 'Tenant',
      tenantFallback: 'Tenant',
      tenantHint: 'Current tenant context.',
      catalogLabel: 'Catalog',
      catalogHint: 'API-backed report catalog items available in this workspace.',
      reportLabel: 'Report',
      reportName: 'Member Feedback Report',
      reportDescription: 'Export member feedback data.',
      jobsLabel: 'Jobs',
      jobsLoading: '…',
      jobsHint: 'Current talent-scoped report jobs.',
      activeDownloadableLabel: 'Active / Downloadable',
      activeDownloadableHint: 'Counts from the currently loaded page.',
    },
    portal: {
      badge: 'External PII handoff',
      title: 'PII platform handoff ready',
      description:
        'This run uses the external PII platform for delivery. TMS does not store the report binary; open the handoff link before it expires, then return to run history for TMS-side tracking.',
      expiresPrefix: 'Link expires at',
      estimatedPrefix: 'estimated',
      estimatedSuffix: 'rows will be handled externally.',
      draftStepLabel: '1. Draft in TMS',
      draftStepHint: 'Filters and preview stay in this report workspace.',
      platformStepLabel: '2. Complete in PII platform',
      platformStepHint: 'Use the external link for the sensitive report file.',
      historyStepLabel: '3. Track in history',
      historyStepHint: 'Return here for queue status and non-PII run context.',
      openPlatform: 'Open PII platform',
    },
    preview: {
      title: 'Preview',
      description: 'Preview matches use the current MFR job draft and return a small sample of the result set.',
      unavailableTitle: 'Preview unavailable',
      matchedRowsLabel: 'Matched Rows',
      matchedRowsHint: 'Estimated row count before queueing.',
      platformsLabel: 'Platforms',
      allPlatforms: 'All',
      platformsHint: 'Filter summary from the API response.',
      dateRangeLabel: 'Date Range',
      dateRangeUnbounded: 'Unbounded',
      includeExpiredHint: 'Expired memberships included.',
      excludeExpiredHint: 'Expired memberships excluded.',
      tableColumns: ['Nickname', 'Platform', 'Membership Level', 'Valid Window', 'Status'],
      emptyTitle: 'No MFR rows matched',
      emptyDescription: 'Adjust the filter draft and run another preview.',
      noPreviewTitle: 'No preview requested yet',
      noPreviewDescription: 'Open the MFR job drawer to preview matched rows before queueing a new report job.',
      unnamedCustomer: 'Unnamed customer',
      openEnded: 'open-ended',
    },
    ledger: {
      title: 'MFR jobs',
      description: 'Track queued jobs, cancel eligible requests, and download completed files.',
      filterLabel: 'Job status filter',
      showingPrefix: 'Showing',
      showingJobsSuffix: 'jobs on the current page,',
      showingTotalSuffix: 'in total.',
      unavailableTitle: 'Report jobs unavailable',
      tableColumns: ['File', 'Status', 'Rows', 'Requested', 'Completed', 'Actions'],
      emptyTitle: 'No MFR jobs found',
      emptyDescription: 'Queue a new MFR export or widen the status filter.',
      pendingFileAssignment: 'Pending file assignment',
      pendingRows: 'Pending',
      download: 'Download',
      details: 'Details',
      cancel: 'Cancel',
      cancelDialogTitle: 'Cancel report job?',
      cancelDialogDescription:
        'Only pending or failed jobs can be cancelled. This removes the job from the current queue.',
      cancelDialogConfirm: 'Cancel job',
      downloadAriaLabel: (label: string) => `Download ${label}`,
      detailsAriaLabel: (label: string) => `View details for ${label}`,
      cancelAriaLabel: (label: string) => `Cancel ${label}`,
    },
    notes: {
      title: 'Report Notes',
      description: 'Review catalog availability and delivery handling for this workspace.',
      scopeLabel: 'Scope',
      scopeValue: 'Talent scope',
      scopeHint: 'Published reports in this workspace currently run against the selected talent scope.',
      sensitiveDeliveryLabel: 'Delivery',
      sensitiveDeliveryValue: 'Linked download',
      sensitiveDeliveryHint: 'When a download link is available, that run opens there instead of downloading directly on this page.',
      workflowLabel: 'Workflow',
      workflowValue: 'Directory + history',
      workflowHint: 'Start from the report directory, then track queued runs and downloads in history.',
    },
    drawer: {
      title: 'Create MFR Job',
      description: 'Queue a new member-feedback export with optional scope filters. Preview uses the same draft state as job creation.',
      draftGuideTitle: 'Preview first, then queue',
      draftGuideDescription: 'Filters are generated from the selected report catalog schema. Use Preview rows to confirm the draft before creating the job.',
      codeFiltersTitle: 'Catalog filters',
      codeFiltersDescription: 'Use the report catalog filter schema for primary filters. Leave fields blank for all values.',
      validityTitle: 'Validity window',
      validityDescription: 'Limit memberships by valid-from / valid-to dates and decide whether expired or inactive memberships should be included.',
      outputTitle: 'Output',
      outputDescription: 'Choose the generated file format before queueing the job.',
      advancedTitle: 'Advanced',
      advancedDescription: 'Raw code entry is reserved for advanced fallback fields published by the catalog schema.',
      cancel: 'Cancel',
      closeLabel: 'Close MFR job drawer',
      previewRows: 'Preview rows',
      createPending: 'Queueing MFR job…',
      create: 'Create MFR job',
      unavailableReport: 'This report is not currently available.',
      fields: {
        platformCodes: 'Platform codes',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: 'Membership class codes',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: 'Membership type codes',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: 'Membership level codes',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: 'Customer status codes',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: 'Download format',
        validFromStart: 'Valid-from start',
        validFromEnd: 'Valid-from end',
        validToStart: 'Valid-to start',
        validToEnd: 'Valid-to end',
        includeExpired: 'Include expired memberships',
        includeInactive: 'Include inactive memberships',
      },
    },
    detail: {
      title: 'Report Job Detail',
      description: 'Inspect the request snapshot, status timeline, failure reason, and artifacts for this run.',
      closeLabel: 'Close report job detail',
      loading: 'Loading report job detail…',
      unavailableTitle: 'Report job detail unavailable',
      snapshotTitle: 'Parameter Snapshot',
      timelineTitle: 'Status Timeline',
      artifactsTitle: 'Artifacts',
      failureTitle: 'Failure Reason',
      noFailureReason: 'No failure reason recorded.',
      noArtifacts: 'No artifacts have been attached to this run.',
      retryFromFilters: 'Retry from filters',
      requestedAt: 'Requested at',
      format: 'Format',
      filters: 'Filters',
      noFilters: 'No filters were applied.',
      fileSize: 'File size',
      downloadState: 'Download state',
      downloadedAt: 'Downloaded at',
      expiresAt: 'Expires at',
      timelinePhases: {
        queued: 'Queued',
        started: 'Started',
        completed: 'Completed',
        downloaded: 'Downloaded',
        expired: 'Expired',
      },
      downloadStates: {
        available: 'Available',
        consumed: 'Consumed',
        expired: 'Expired',
        unavailable: 'Unavailable',
      },
    },
    options: {
      jobStatus: {
        all: 'All statuses',
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
      reportFormat: {
        xlsx: 'Excel (.xlsx)',
        csv: 'CSV (.csv)',
      },
      jobState: {
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
    },
    common: {
      never: 'Never',
    },
  },
  zh_HANS: {
    state: {
      loadCatalogError: '加载报表目录失败。',
      loadJobsError: '加载报表任务失败。',
      refreshJobsError: '刷新报表任务失败。',
      previewError: '预览当前 MFR 筛选失败。',
      loadJobDetailError: '加载报表任务详情失败。',
      piiPortalHandoffPrefix: '报表已就绪，匹配到',
      piiPortalHandoffSuffix: '位客户。',
      createLocalJobPrefix: 'MFR 任务',
      createLocalJobSuffix: '已排队，预计',
      createLocalJobRowsSuffix: '行。',
      createJobError: '创建 MFR 任务失败。',
      downloadOpenedPrefix: '已打开下载：',
      downloadOpenedFallback: '所选报表',
      downloadError: '准备报表下载失败。',
      cancelError: '取消所选报表任务失败。',
      cancelSuccessFallback: '所选任务',
      cancelSuccessSuffix: '已取消。',
    },
    header: {
      eyebrow: '报表',
      title: '报表管理',
      description: '浏览当前艺人范围可用的报表，起草导出任务，并查看运行历史。',
      workspaceSettings: '艺人设置',
      draftJob: '起草报表',
      refreshJobs: '刷新任务',
    },
    summary: {
      tenantLabel: '租户',
      tenantFallback: '当前租户',
      tenantHint: '当前租户上下文。',
      catalogLabel: '目录',
      catalogHint: '当前工作区可用的 API 驱动报表目录项。',
      reportLabel: '报表',
      reportName: '会员反馈报表',
      reportDescription: '导出会员反馈数据。',
      jobsLabel: '任务数',
      jobsLoading: '…',
      jobsHint: '当前艺人范围内的报表任务。',
      activeDownloadableLabel: '进行中 / 可下载',
      activeDownloadableHint: '基于当前已加载页面的统计。',
    },
    portal: {
      badge: '外部 PII 交接',
      title: 'PII 平台交接已就绪',
      description: '本次运行通过外部 PII 平台交付。TMS 不存储报表文件本体；请在交接链接过期前打开外部平台，然后回到运行历史查看 TMS 侧状态。',
      expiresPrefix: '链接过期时间',
      estimatedPrefix: '预计',
      estimatedSuffix: '行将由外部平台处理。',
      draftStepLabel: '1. 在 TMS 起草',
      draftStepHint: '筛选与预览保留在当前报表工作区。',
      platformStepLabel: '2. 在 PII 平台完成',
      platformStepHint: '通过外部链接处理敏感报表文件。',
      historyStepLabel: '3. 回到历史跟踪',
      historyStepHint: '在这里查看队列状态与非 PII 运行上下文。',
      openPlatform: '打开 PII 平台',
    },
    preview: {
      title: '预览',
      description: '预览使用当前 MFR 任务草稿，并返回一小部分结果样本。',
      unavailableTitle: '预览不可用',
      matchedRowsLabel: '匹配行数',
      matchedRowsHint: '排队前的预估行数。',
      platformsLabel: '平台',
      allPlatforms: '全部',
      platformsHint: '来自 API 响应的筛选摘要。',
      dateRangeLabel: '时间范围',
      dateRangeUnbounded: '不限制',
      includeExpiredHint: '包含已过期会员。',
      excludeExpiredHint: '不包含已过期会员。',
      tableColumns: ['昵称', '平台', '会员等级', '有效期', '状态'],
      emptyTitle: '没有匹配到 MFR 行',
      emptyDescription: '请调整筛选草稿后重新预览。',
      noPreviewTitle: '尚未请求预览',
      noPreviewDescription: '先打开 MFR 任务抽屉预览匹配行，再决定是否创建报表任务。',
      unnamedCustomer: '未命名客户',
      openEnded: '未设结束时间',
    },
    ledger: {
      title: 'MFR 任务',
      description: '跟踪当前页的排队任务，取消可取消请求，并下载已完成产物。',
      filterLabel: '任务状态筛选',
      showingPrefix: '当前页显示',
      showingJobsSuffix: '个任务，总计',
      showingTotalSuffix: '个。',
      unavailableTitle: '报表任务不可用',
      tableColumns: ['文件', '状态', '行数', '请求时间', '完成时间', '操作'],
      emptyTitle: '没有找到 MFR 任务',
      emptyDescription: '创建新的 MFR 导出任务，或放宽状态筛选条件。',
      pendingFileAssignment: '等待分配文件名',
      pendingRows: '处理中',
      download: '下载',
      details: '详情',
      cancel: '取消',
      cancelDialogTitle: '取消报表任务？',
      cancelDialogDescription: '只有待处理或失败的任务可以取消，该操作会将任务移出当前队列。',
      cancelDialogConfirm: '取消任务',
      downloadAriaLabel: (label: string) => `下载 ${label}`,
      detailsAriaLabel: (label: string) => `查看 ${label} 的详情`,
      cancelAriaLabel: (label: string) => `取消 ${label}`,
    },
    notes: {
      title: '报表说明',
      description: '查看当前工作区的报表可用性与交付方式。',
      scopeLabel: '范围',
      scopeValue: '艺人范围',
      scopeHint: '该工作区当前已发布的报表都以所选艺人范围运行。',
      sensitiveDeliveryLabel: '下载方式',
      sensitiveDeliveryValue: '外部链接',
      sensitiveDeliveryHint: '当某个运行生成下载链接时，会通过该链接打开，而不是在当前页直接下载。',
      workflowLabel: '工作流',
      workflowValue: '目录 + 历史',
      workflowHint: '先从报表目录起草任务，再到运行历史跟踪排队与下载。',
    },
    drawer: {
      title: '创建 MFR 任务',
      description: '可带可选范围筛选创建新的会员反馈导出任务，预览与创建共享同一份草稿状态。',
      draftGuideTitle: '先预览，再排队',
      draftGuideDescription: '筛选项来自所选报表的目录 schema。创建任务前请先用预览结果确认草稿。',
      codeFiltersTitle: '目录筛选',
      codeFiltersDescription: '使用报表目录 filter schema 中的主要筛选项；留空表示包含全部值。',
      validityTitle: '有效期窗口',
      validityDescription: '按 valid-from / valid-to 日期限制会员范围，并决定是否包含已过期或未激活会员。',
      outputTitle: '输出',
      outputDescription: '排队任务前选择生成文件格式。',
      advancedTitle: '高级',
      advancedDescription: '原始代码输入仅用于目录 schema 发布的高级兜底字段。',
      cancel: '取消',
      closeLabel: '关闭 MFR 任务抽屉',
      previewRows: '预览结果',
      createPending: 'MFR 任务排队中…',
      create: '创建 MFR 任务',
      unavailableReport: '当前报表暂不可用。',
      fields: {
        platformCodes: '平台代码',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: '会员分类代码',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: '会员类型代码',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: '会员等级代码',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: '客户状态代码',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: '下载格式',
        validFromStart: '有效期开始（起）',
        validFromEnd: '有效期开始（止）',
        validToStart: '有效期结束（起）',
        validToEnd: '有效期结束（止）',
        includeExpired: '包含已过期会员',
        includeInactive: '包含未激活会员',
      },
    },
    detail: {
      title: '报表任务详情',
      description: '查看本次运行的请求快照、状态时间线、失败原因与产物。',
      closeLabel: '关闭报表任务详情',
      loading: '正在加载报表任务详情…',
      unavailableTitle: '报表任务详情不可用',
      snapshotTitle: '参数快照',
      timelineTitle: '状态时间线',
      artifactsTitle: '产物',
      failureTitle: '失败原因',
      noFailureReason: '没有记录失败原因。',
      noArtifacts: '本次运行尚未附加产物。',
      retryFromFilters: '按这些筛选重试',
      requestedAt: '请求时间',
      format: '格式',
      filters: '筛选',
      noFilters: '未应用筛选。',
      fileSize: '文件大小',
      downloadState: '下载状态',
      downloadedAt: '下载时间',
      expiresAt: '过期时间',
      timelinePhases: {
        queued: '已排队',
        started: '已开始',
        completed: '已完成',
        downloaded: '已下载',
        expired: '已过期',
      },
      downloadStates: {
        available: '可下载',
        consumed: '已消费',
        expired: '已过期',
        unavailable: '不可用',
      },
    },
    options: {
      jobStatus: {
        all: '全部状态',
        pending: '待处理',
        running: '运行中',
        retrying: '重试中',
        success: '成功',
        consumed: '已消费',
        failed: '失败',
        expired: '已过期',
        cancelled: '已取消',
      },
      reportFormat: {
        xlsx: 'Excel（.xlsx）',
        csv: 'CSV（.csv）',
      },
      jobState: {
        pending: '待处理',
        running: '运行中',
        retrying: '重试中',
        success: '成功',
        consumed: '已消费',
        failed: '失败',
        expired: '已过期',
        cancelled: '已取消',
      },
    },
    common: {
      never: '从未',
    },
  },
  zh_HANT: {
    state: {
      loadCatalogError: '加载报表目录失败。',
      loadJobsError: '加载报表任务失败。',
      refreshJobsError: '刷新报表任务失败。',
      previewError: '预览当前 MFR 筛选失败。',
      loadJobDetailError: '加载报表任务详情失败。',
      piiPortalHandoffPrefix: '报表已就绪，匹配到',
      piiPortalHandoffSuffix: '位客户。',
      createLocalJobPrefix: 'MFR 任务',
      createLocalJobSuffix: '已排队，预计',
      createLocalJobRowsSuffix: '行。',
      createJobError: '创建 MFR 任务失败。',
      downloadOpenedPrefix: '已打开下载：',
      downloadOpenedFallback: '所选报表',
      downloadError: '准备报表下载失败。',
      cancelError: '取消所选报表任务失败。',
      cancelSuccessFallback: '所选任务',
      cancelSuccessSuffix: '已取消。',
    },
    header: {
      eyebrow: '报表',
      title: '报表管理',
      description: '浏览当前艺人范围可用的报表，起草导出任务，并查看运行历史。',
      workspaceSettings: '艺人设置',
      draftJob: '起草报表',
      refreshJobs: '刷新任务',
    },
    summary: {
      tenantLabel: '租户',
      tenantFallback: '当前租户',
      tenantHint: '当前租户上下文。',
      catalogLabel: '目录',
      catalogHint: '当前工作区可用的 API 驱动报表目录项。',
      reportLabel: '报表',
      reportName: '会员反馈报表',
      reportDescription: '导出会员反馈数据。',
      jobsLabel: '任务数',
      jobsLoading: '…',
      jobsHint: '当前艺人范围内的报表任务。',
      activeDownloadableLabel: '进行中 / 可下载',
      activeDownloadableHint: '基于当前已加载页面的统计。',
    },
    portal: {
      badge: '外部 PII 交接',
      title: 'PII 平台交接已就绪',
      description: '本次运行通过外部 PII 平台交付。TMS 不存储报表文件本体；请在交接链接过期前打开外部平台，然后回到运行历史查看 TMS 侧状态。',
      expiresPrefix: '链接过期时间',
      estimatedPrefix: '预计',
      estimatedSuffix: '行将由外部平台处理。',
      draftStepLabel: '1. 在 TMS 起草',
      draftStepHint: '筛选与预览保留在当前报表工作区。',
      platformStepLabel: '2. 在 PII 平台完成',
      platformStepHint: '通过外部链接处理敏感报表文件。',
      historyStepLabel: '3. 回到历史跟踪',
      historyStepHint: '在这里查看队列状态与非 PII 运行上下文。',
      openPlatform: '打开 PII 平台',
    },
    preview: {
      title: '预览',
      description: '预览使用当前 MFR 任务草稿，并返回一小部分结果样本。',
      unavailableTitle: '预览不可用',
      matchedRowsLabel: '匹配行数',
      matchedRowsHint: '排队前的预估行数。',
      platformsLabel: '平台',
      allPlatforms: '全部',
      platformsHint: '来自 API 响应的筛选摘要。',
      dateRangeLabel: '时间范围',
      dateRangeUnbounded: '不限制',
      includeExpiredHint: '包含已过期会员。',
      excludeExpiredHint: '不包含已过期会员。',
      tableColumns: ['昵称', '平台', '会员等级', '有效期', '状态'],
      emptyTitle: '没有匹配到 MFR 行',
      emptyDescription: '请调整筛选草稿后重新预览。',
      noPreviewTitle: '尚未请求预览',
      noPreviewDescription: '先打开 MFR 任务抽屉预览匹配行，再决定是否创建报表任务。',
      unnamedCustomer: '未命名客户',
      openEnded: '未设结束时间',
    },
    ledger: {
      title: 'MFR 任务',
      description: '跟踪当前页的排队任务，取消可取消请求，并下载已完成产物。',
      filterLabel: '任务状态筛选',
      showingPrefix: '当前页显示',
      showingJobsSuffix: '个任务，总计',
      showingTotalSuffix: '个。',
      unavailableTitle: '报表任务不可用',
      tableColumns: ['文件', '状态', '行数', '请求时间', '完成时间', '操作'],
      emptyTitle: '没有找到 MFR 任务',
      emptyDescription: '创建新的 MFR 导出任务，或放宽状态筛选条件。',
      pendingFileAssignment: '等待分配文件名',
      pendingRows: '处理中',
      download: '下载',
      details: '详情',
      cancel: '取消',
      cancelDialogTitle: '取消报表任务？',
      cancelDialogDescription: '只有待处理或失败的任务可以取消，该操作会将任务移出当前队列。',
      cancelDialogConfirm: '取消任务',
      downloadAriaLabel: (label: string) => `下载 ${label}`,
      detailsAriaLabel: (label: string) => `查看 ${label} 的详情`,
      cancelAriaLabel: (label: string) => `取消 ${label}`,
    },
    notes: {
      title: '报表说明',
      description: '查看当前工作区的报表可用性与交付方式。',
      scopeLabel: '范围',
      scopeValue: '艺人范围',
      scopeHint: '该工作区当前已发布的报表都以所选艺人范围运行。',
      sensitiveDeliveryLabel: '下载方式',
      sensitiveDeliveryValue: '外部链接',
      sensitiveDeliveryHint: '当某个运行生成下载链接时，会通过该链接打开，而不是在当前页直接下载。',
      workflowLabel: '工作流',
      workflowValue: '目录 + 历史',
      workflowHint: '先从报表目录起草任务，再到运行历史跟踪排队与下载。',
    },
    drawer: {
      title: '创建 MFR 任务',
      description: '可带可选范围筛选创建新的会员反馈导出任务，预览与创建共享同一份草稿状态。',
      draftGuideTitle: '先预览，再排队',
      draftGuideDescription: '筛选项来自所选报表的目录 schema。创建任务前请先用预览结果确认草稿。',
      codeFiltersTitle: '目录筛选',
      codeFiltersDescription: '使用报表目录 filter schema 中的主要筛选项；留空表示包含全部值。',
      validityTitle: '有效期窗口',
      validityDescription: '按 valid-from / valid-to 日期限制会员范围，并决定是否包含已过期或未激活会员。',
      outputTitle: '输出',
      outputDescription: '排队任务前选择生成文件格式。',
      advancedTitle: '高级',
      advancedDescription: '原始代码输入仅用于目录 schema 发布的高级兜底字段。',
      cancel: '取消',
      closeLabel: '关闭 MFR 任务抽屉',
      previewRows: '预览结果',
      createPending: 'MFR 任务排队中…',
      create: '创建 MFR 任务',
      unavailableReport: '当前报表暂不可用。',
      fields: {
        platformCodes: '平台代码',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: '会员分类代码',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: '会员类型代码',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: '会员等级代码',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: '客户状态代码',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: '下载格式',
        validFromStart: '有效期开始（起）',
        validFromEnd: '有效期开始（止）',
        validToStart: '有效期结束（起）',
        validToEnd: '有效期结束（止）',
        includeExpired: '包含已过期会员',
        includeInactive: '包含未激活会员',
      },
    },
    detail: {
      title: '报表任务详情',
      description: '查看本次运行的请求快照、状态时间线、失败原因与产物。',
      closeLabel: '关闭报表任务详情',
      loading: '正在加载报表任务详情…',
      unavailableTitle: '报表任务详情不可用',
      snapshotTitle: '参数快照',
      timelineTitle: '状态时间线',
      artifactsTitle: '产物',
      failureTitle: '失败原因',
      noFailureReason: '没有记录失败原因。',
      noArtifacts: '本次运行尚未附加产物。',
      retryFromFilters: '按这些筛选重试',
      requestedAt: '请求时间',
      format: '格式',
      filters: '筛选',
      noFilters: '未应用筛选。',
      fileSize: '文件大小',
      downloadState: '下载状态',
      downloadedAt: '下载时间',
      expiresAt: '过期时间',
      timelinePhases: {
        queued: '已排队',
        started: '已开始',
        completed: '已完成',
        downloaded: '已下载',
        expired: '已过期',
      },
      downloadStates: {
        available: '可下载',
        consumed: '已消费',
        expired: '已过期',
        unavailable: '不可用',
      },
    },
    options: {
      jobStatus: {
        all: '全部状态',
        pending: '待处理',
        running: '运行中',
        retrying: '重试中',
        success: '成功',
        consumed: '已消费',
        failed: '失败',
        expired: '已过期',
        cancelled: '已取消',
      },
      reportFormat: {
        xlsx: 'Excel（.xlsx）',
        csv: 'CSV（.csv）',
      },
      jobState: {
        pending: '待处理',
        running: '运行中',
        retrying: '重试中',
        success: '成功',
        consumed: '已消费',
        failed: '失败',
        expired: '已过期',
        cancelled: '已取消',
      },
    },
    common: {
      never: '从未',
    },
  },
  ja: {
    state: {
      loadCatalogError: 'レポートカタログの読み込みに失敗しました。',
      loadJobsError: 'レポートジョブ台帳の読み込みに失敗しました。',
      refreshJobsError: 'レポートジョブ台帳の更新に失敗しました。',
      previewError: '現在の MFR フィルターのプレビューに失敗しました。',
      loadJobDetailError: 'レポートジョブ詳細の読み込みに失敗しました。',
      piiPortalHandoffPrefix: 'レポートの準備が完了し、',
      piiPortalHandoffSuffix: '人の顧客が一致しました。',
      createLocalJobPrefix: 'MFR ジョブ',
      createLocalJobSuffix: 'をキューに追加しました。推定',
      createLocalJobRowsSuffix: '行です。',
      createJobError: 'MFR ジョブの作成に失敗しました。',
      downloadOpenedPrefix: 'ダウンロードを開きました:',
      downloadOpenedFallback: '選択したレポート',
      downloadError: 'レポートダウンロードの準備に失敗しました。',
      cancelError: '選択したレポートジョブのキャンセルに失敗しました。',
      cancelSuccessFallback: '選択したジョブ',
      cancelSuccessSuffix: 'をキャンセルしました。',
    },
    header: {
      eyebrow: 'レポート',
      title: 'レポート管理',
      description: '現在のタレント範囲で利用できるレポートを確認し、エクスポートを起票し、実行履歴を確認します。',
      workspaceSettings: 'タレント設定',
      draftJob: 'レポートを起票',
      refreshJobs: 'ジョブを更新',
    },
    summary: {
      tenantLabel: 'テナント',
      tenantFallback: '現在のテナント',
      tenantHint: '現在のテナントコンテキストです。',
      catalogLabel: 'カタログ',
      catalogHint: 'このワークスペースで利用できる API 駆動のレポートカタログ項目です。',
      reportLabel: 'レポート',
      reportName: '会員フィードバックレポート',
      reportDescription: '会員フィードバックデータをエクスポートします。',
      jobsLabel: 'ジョブ数',
      jobsLoading: '…',
      jobsHint: '現在のタレント範囲におけるレポートジョブです。',
      activeDownloadableLabel: '進行中 / ダウンロード可',
      activeDownloadableHint: '現在読み込まれているページの件数です。',
    },
    portal: {
      badge: '外部 PII ハンドオフ',
      title: 'PII プラットフォームへのハンドオフ準備完了',
      description:
        'この実行は外部 PII プラットフォームで配信します。TMS はレポートファイル本体を保存しません。ハンドオフリンクの期限前に外部プラットフォームを開き、その後 TMS 側の追跡は実行履歴に戻って確認してください。',
      expiresPrefix: 'リンク有効期限',
      estimatedPrefix: '推定',
      estimatedSuffix: '行が外部プラットフォームで処理されます。',
      draftStepLabel: '1. TMS で草稿作成',
      draftStepHint: 'フィルターとプレビューはこのレポートワークスペースに残ります。',
      platformStepLabel: '2. PII プラットフォームで完了',
      platformStepHint: '機密レポートファイルは外部リンクで処理します。',
      historyStepLabel: '3. 履歴で追跡',
      historyStepHint: 'キュー状態と非 PII の実行コンテキストはここで確認します。',
      openPlatform: 'PII プラットフォームを開く',
    },
    preview: {
      title: 'プレビュー',
      description: 'プレビューは現在の MFR ジョブ草稿を使い、結果セットの一部サンプルを返します。',
      unavailableTitle: 'プレビューを利用できません',
      matchedRowsLabel: '一致行数',
      matchedRowsHint: 'キュー投入前の推定行数です。',
      platformsLabel: 'プラットフォーム',
      allPlatforms: 'すべて',
      platformsHint: 'API 応答のフィルター要約です。',
      dateRangeLabel: '期間',
      dateRangeUnbounded: '無制限',
      includeExpiredHint: '期限切れ会員を含みます。',
      excludeExpiredHint: '期限切れ会員を含みません。',
      tableColumns: ['ニックネーム', 'プラットフォーム', '会員レベル', '有効期間', '状態'],
      emptyTitle: '一致する MFR 行はありません',
      emptyDescription: 'フィルター草稿を調整して、もう一度プレビューしてください。',
      noPreviewTitle: 'まだプレビューは要求されていません',
      noPreviewDescription: 'まず MFR ジョブドロワーを開き、一致行を確認してからレポートジョブを作成してください。',
      unnamedCustomer: '名称未設定の顧客',
      openEnded: '終了日なし',
    },
    ledger: {
      title: 'MFR ジョブ',
      description: '現在ページのキュー済みジョブを追跡し、取消可能な要求を停止し、完了済み成果物をダウンロードします。',
      filterLabel: 'ジョブ状態フィルター',
      showingPrefix: '現在のページに',
      showingJobsSuffix: '件表示、合計',
      showingTotalSuffix: '件です。',
      unavailableTitle: 'レポートジョブを利用できません',
      tableColumns: ['ファイル', '状態', '行数', '要求日時', '完了日時', '操作'],
      emptyTitle: 'MFR ジョブが見つかりません',
      emptyDescription: '新しい MFR エクスポートを作成するか、状態フィルターを広げてください。',
      pendingFileAssignment: 'ファイル名割当待ち',
      pendingRows: '保留',
      download: 'ダウンロード',
      details: '詳細',
      cancel: 'キャンセル',
      cancelDialogTitle: 'レポートジョブをキャンセルしますか？',
      cancelDialogDescription:
        '保留中または失敗したジョブのみキャンセルできます。これにより、ジョブは現在のキューから除外されます。',
      cancelDialogConfirm: 'ジョブをキャンセル',
      downloadAriaLabel: (label: string) => `${label} をダウンロード`,
      detailsAriaLabel: (label: string) => `${label} の詳細を表示`,
      cancelAriaLabel: (label: string) => `${label} をキャンセル`,
    },
    notes: {
      title: 'レポートメモ',
      description: 'このワークスペースで利用できるレポートと配信方法を確認します。',
      scopeLabel: 'スコープ',
      scopeValue: 'タレント範囲',
      scopeHint: 'このワークスペースで公開中のレポートは、現在選択中のタレント範囲で実行されます。',
      sensitiveDeliveryLabel: 'ダウンロード方式',
      sensitiveDeliveryValue: 'リンクダウンロード',
      sensitiveDeliveryHint: 'ダウンロードリンクが利用できる場合、その実行結果はこのページで直接ダウンロードする代わりにリンク先を開きます。',
      workflowLabel: 'ワークフロー',
      workflowValue: 'ディレクトリ + 履歴',
      workflowHint: 'レポートディレクトリから起票し、履歴でキューとダウンロードを追跡します。',
    },
    drawer: {
      title: 'MFR ジョブを作成',
      description: '任意のスコープフィルター付きで新しい会員フィードバックエクスポートを作成します。プレビューはジョブ作成と同じ草稿状態を使用します。',
      draftGuideTitle: '先にプレビューし、その後キューに追加',
      draftGuideDescription: 'フィルターは選択したレポートカタログ schema から生成されます。ジョブ作成前にプレビュー行で草稿を確認してください。',
      codeFiltersTitle: 'カタログフィルター',
      codeFiltersDescription: 'レポートカタログの filter schema にある主要フィルターを使用します。空欄の場合はすべての値を含めます。',
      validityTitle: '有効期間',
      validityDescription: 'valid-from / valid-to の日付で会員範囲を絞り、期限切れまたは非アクティブ会員を含めるかを決めます。',
      outputTitle: '出力',
      outputDescription: 'ジョブをキューに入れる前に生成ファイル形式を選択します。',
      advancedTitle: '詳細設定',
      advancedDescription: '生コード入力はカタログ schema が公開する詳細フォールバック項目に限定されます。',
      cancel: 'キャンセル',
      closeLabel: 'MFR ジョブドロワーを閉じる',
      previewRows: '行をプレビュー',
      createPending: 'MFR ジョブをキュー中…',
      create: 'MFR ジョブを作成',
      unavailableReport: 'このレポートは現在利用できません。',
      fields: {
        platformCodes: 'プラットフォームコード',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: '会員クラスコード',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: '会員タイプコード',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: '会員レベルコード',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: '顧客状態コード',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: 'ダウンロード形式',
        validFromStart: '有効開始（開始）',
        validFromEnd: '有効開始（終了）',
        validToStart: '有効終了（開始）',
        validToEnd: '有効終了（終了）',
        includeExpired: '期限切れ会員を含める',
        includeInactive: '非アクティブ会員を含める',
      },
    },
    detail: {
      title: 'レポートジョブ詳細',
      description: 'この実行のリクエストスナップショット、状態タイムライン、失敗理由、成果物を確認します。',
      closeLabel: 'レポートジョブ詳細を閉じる',
      loading: 'レポートジョブ詳細を読み込み中…',
      unavailableTitle: 'レポートジョブ詳細を利用できません',
      snapshotTitle: 'パラメータスナップショット',
      timelineTitle: '状態タイムライン',
      artifactsTitle: '成果物',
      failureTitle: '失敗理由',
      noFailureReason: '失敗理由は記録されていません。',
      noArtifacts: 'この実行には成果物が添付されていません。',
      retryFromFilters: 'このフィルターで再実行',
      requestedAt: '要求日時',
      format: '形式',
      filters: 'フィルター',
      noFilters: 'フィルターは適用されていません。',
      fileSize: 'ファイルサイズ',
      downloadState: 'ダウンロード状態',
      downloadedAt: 'ダウンロード日時',
      expiresAt: '有効期限',
      timelinePhases: {
        queued: 'キュー済み',
        started: '開始済み',
        completed: '完了',
        downloaded: 'ダウンロード済み',
        expired: '期限切れ',
      },
      downloadStates: {
        available: '利用可能',
        consumed: '消費済み',
        expired: '期限切れ',
        unavailable: '利用不可',
      },
    },
    options: {
      jobStatus: {
        all: 'すべての状態',
        pending: '保留',
        running: '実行中',
        retrying: '再試行中',
        success: '成功',
        consumed: '消費済み',
        failed: '失敗',
        expired: '期限切れ',
        cancelled: 'キャンセル済み',
      },
      reportFormat: {
        xlsx: 'Excel (.xlsx)',
        csv: 'CSV (.csv)',
      },
      jobState: {
        pending: '保留',
        running: '実行中',
        retrying: '再試行中',
        success: '成功',
        consumed: '消費済み',
        failed: '失敗',
        expired: '期限切れ',
        cancelled: 'キャンセル済み',
      },
    },
    common: {
      never: '未実施',
    },
  },
  ko: {
    state: {
      loadCatalogError: 'Failed to load the report catalog.',
      loadJobsError: 'Failed to load report jobs.',
      refreshJobsError: 'Failed to refresh report jobs.',
      previewError: 'Failed to preview the current MFR filters.',
      loadJobDetailError: 'Failed to load report job detail.',
      piiPortalHandoffPrefix: 'Report ready with',
      piiPortalHandoffSuffix: 'matched customers.',
      createLocalJobPrefix: 'MFR job',
      createLocalJobSuffix: 'was queued with an estimated',
      createLocalJobRowsSuffix: 'rows.',
      createJobError: 'Failed to create the MFR job.',
      downloadOpenedPrefix: 'Download opened for',
      downloadOpenedFallback: 'the selected report',
      downloadError: 'Failed to prepare the report download.',
      cancelError: 'Failed to cancel the selected report job.',
      cancelSuccessFallback: 'The selected job',
      cancelSuccessSuffix: 'was cancelled.',
    },
    header: {
      eyebrow: 'Reports',
      title: 'Reports Management',
      description: 'Browse available reports, draft exports, and review run history for the current talent scope.',
      workspaceSettings: 'Talent settings',
      draftJob: 'Draft report',
      refreshJobs: 'Refresh jobs',
    },
    summary: {
      tenantLabel: 'Tenant',
      tenantFallback: 'Tenant',
      tenantHint: 'Current tenant context.',
      catalogLabel: 'Catalog',
      catalogHint: 'API-backed report catalog items available in this workspace.',
      reportLabel: 'Report',
      reportName: 'Member Feedback Report',
      reportDescription: 'Export member feedback data.',
      jobsLabel: 'Jobs',
      jobsLoading: '…',
      jobsHint: 'Current talent-scoped report jobs.',
      activeDownloadableLabel: 'Active / Downloadable',
      activeDownloadableHint: 'Counts from the currently loaded page.',
    },
    portal: {
      badge: 'External PII handoff',
      title: 'PII platform handoff ready',
      description:
        'This run uses the external PII platform for delivery. TMS does not store the report binary; open the handoff link before it expires, then return to run history for TMS-side tracking.',
      expiresPrefix: 'Link expires at',
      estimatedPrefix: 'estimated',
      estimatedSuffix: 'rows will be handled externally.',
      draftStepLabel: '1. Draft in TMS',
      draftStepHint: 'Filters and preview stay in this report workspace.',
      platformStepLabel: '2. Complete in PII platform',
      platformStepHint: 'Use the external link for the sensitive report file.',
      historyStepLabel: '3. Track in history',
      historyStepHint: 'Return here for queue status and non-PII run context.',
      openPlatform: 'Open PII platform',
    },
    preview: {
      title: 'Preview',
      description: 'Preview matches use the current MFR job draft and return a small sample of the result set.',
      unavailableTitle: 'Preview unavailable',
      matchedRowsLabel: 'Matched Rows',
      matchedRowsHint: 'Estimated row count before queueing.',
      platformsLabel: 'Platforms',
      allPlatforms: 'All',
      platformsHint: 'Filter summary from the API response.',
      dateRangeLabel: 'Date Range',
      dateRangeUnbounded: 'Unbounded',
      includeExpiredHint: 'Expired memberships included.',
      excludeExpiredHint: 'Expired memberships excluded.',
      tableColumns: ['Nickname', 'Platform', 'Membership Level', 'Valid Window', 'Status'],
      emptyTitle: 'No MFR rows matched',
      emptyDescription: 'Adjust the filter draft and run another preview.',
      noPreviewTitle: 'No preview requested yet',
      noPreviewDescription: 'Open the MFR job drawer to preview matched rows before queueing a new report job.',
      unnamedCustomer: 'Unnamed customer',
      openEnded: 'open-ended',
    },
    ledger: {
      title: 'MFR jobs',
      description: 'Track queued jobs, cancel eligible requests, and download completed files.',
      filterLabel: 'Job status filter',
      showingPrefix: 'Showing',
      showingJobsSuffix: 'jobs on the current page,',
      showingTotalSuffix: 'in total.',
      unavailableTitle: 'Report jobs unavailable',
      tableColumns: ['File', 'Status', 'Rows', 'Requested', 'Completed', 'Actions'],
      emptyTitle: 'No MFR jobs found',
      emptyDescription: 'Queue a new MFR export or widen the status filter.',
      pendingFileAssignment: 'Pending file assignment',
      pendingRows: 'Pending',
      download: 'Download',
      details: 'Details',
      cancel: 'Cancel',
      cancelDialogTitle: 'Cancel report job?',
      cancelDialogDescription:
        'Only pending or failed jobs can be cancelled. This removes the job from the current queue.',
      cancelDialogConfirm: 'Cancel job',
      downloadAriaLabel: (label: string) => `Download ${label}`,
      detailsAriaLabel: (label: string) => `View details for ${label}`,
      cancelAriaLabel: (label: string) => `Cancel ${label}`,
    },
    notes: {
      title: 'Report Notes',
      description: 'Review catalog availability and delivery handling for this workspace.',
      scopeLabel: 'Scope',
      scopeValue: 'Talent scope',
      scopeHint: 'Published reports in this workspace currently run against the selected talent scope.',
      sensitiveDeliveryLabel: 'Delivery',
      sensitiveDeliveryValue: 'Linked download',
      sensitiveDeliveryHint: 'When a download link is available, that run opens there instead of downloading directly on this page.',
      workflowLabel: 'Workflow',
      workflowValue: 'Directory + history',
      workflowHint: 'Start from the report directory, then track queued runs and downloads in history.',
    },
    drawer: {
      title: 'Create MFR Job',
      description: 'Queue a new member-feedback export with optional scope filters. Preview uses the same draft state as job creation.',
      draftGuideTitle: 'Preview first, then queue',
      draftGuideDescription: 'Filters are generated from the selected report catalog schema. Use Preview rows to confirm the draft before creating the job.',
      codeFiltersTitle: 'Catalog filters',
      codeFiltersDescription: 'Use the report catalog filter schema for primary filters. Leave fields blank for all values.',
      validityTitle: 'Validity window',
      validityDescription: 'Limit memberships by valid-from / valid-to dates and decide whether expired or inactive memberships should be included.',
      outputTitle: 'Output',
      outputDescription: 'Choose the generated file format before queueing the job.',
      advancedTitle: 'Advanced',
      advancedDescription: 'Raw code entry is reserved for advanced fallback fields published by the catalog schema.',
      cancel: 'Cancel',
      closeLabel: 'Close MFR job drawer',
      previewRows: 'Preview rows',
      createPending: 'Queueing MFR job…',
      create: 'Create MFR job',
      unavailableReport: 'This report is not currently available.',
      fields: {
        platformCodes: 'Platform codes',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: 'Membership class codes',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: 'Membership type codes',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: 'Membership level codes',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: 'Customer status codes',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: 'Download format',
        validFromStart: 'Valid-from start',
        validFromEnd: 'Valid-from end',
        validToStart: 'Valid-to start',
        validToEnd: 'Valid-to end',
        includeExpired: 'Include expired memberships',
        includeInactive: 'Include inactive memberships',
      },
    },
    detail: {
      title: 'Report Job Detail',
      description: 'Inspect the request snapshot, status timeline, failure reason, and artifacts for this run.',
      closeLabel: 'Close report job detail',
      loading: 'Loading report job detail…',
      unavailableTitle: 'Report job detail unavailable',
      snapshotTitle: 'Parameter Snapshot',
      timelineTitle: 'Status Timeline',
      artifactsTitle: 'Artifacts',
      failureTitle: 'Failure Reason',
      noFailureReason: 'No failure reason recorded.',
      noArtifacts: 'No artifacts have been attached to this run.',
      retryFromFilters: 'Retry from filters',
      requestedAt: 'Requested at',
      format: 'Format',
      filters: 'Filters',
      noFilters: 'No filters were applied.',
      fileSize: 'File size',
      downloadState: 'Download state',
      downloadedAt: 'Downloaded at',
      expiresAt: 'Expires at',
      timelinePhases: {
        queued: 'Queued',
        started: 'Started',
        completed: 'Completed',
        downloaded: 'Downloaded',
        expired: 'Expired',
      },
      downloadStates: {
        available: 'Available',
        consumed: 'Consumed',
        expired: 'Expired',
        unavailable: 'Unavailable',
      },
    },
    options: {
      jobStatus: {
        all: 'All statuses',
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
      reportFormat: {
        xlsx: 'Excel (.xlsx)',
        csv: 'CSV (.csv)',
      },
      jobState: {
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
    },
    common: {
      never: 'Never',
    },
  },
  fr: {
    state: {
      loadCatalogError: 'Failed to load the report catalog.',
      loadJobsError: 'Failed to load report jobs.',
      refreshJobsError: 'Failed to refresh report jobs.',
      previewError: 'Failed to preview the current MFR filters.',
      loadJobDetailError: 'Failed to load report job detail.',
      piiPortalHandoffPrefix: 'Report ready with',
      piiPortalHandoffSuffix: 'matched customers.',
      createLocalJobPrefix: 'MFR job',
      createLocalJobSuffix: 'was queued with an estimated',
      createLocalJobRowsSuffix: 'rows.',
      createJobError: 'Failed to create the MFR job.',
      downloadOpenedPrefix: 'Download opened for',
      downloadOpenedFallback: 'the selected report',
      downloadError: 'Failed to prepare the report download.',
      cancelError: 'Failed to cancel the selected report job.',
      cancelSuccessFallback: 'The selected job',
      cancelSuccessSuffix: 'was cancelled.',
    },
    header: {
      eyebrow: 'Reports',
      title: 'Reports Management',
      description: 'Browse available reports, draft exports, and review run history for the current talent scope.',
      workspaceSettings: 'Talent settings',
      draftJob: 'Draft report',
      refreshJobs: 'Refresh jobs',
    },
    summary: {
      tenantLabel: 'Tenant',
      tenantFallback: 'Tenant',
      tenantHint: 'Current tenant context.',
      catalogLabel: 'Catalog',
      catalogHint: 'API-backed report catalog items available in this workspace.',
      reportLabel: 'Report',
      reportName: 'Member Feedback Report',
      reportDescription: 'Export member feedback data.',
      jobsLabel: 'Jobs',
      jobsLoading: '…',
      jobsHint: 'Current talent-scoped report jobs.',
      activeDownloadableLabel: 'Active / Downloadable',
      activeDownloadableHint: 'Counts from the currently loaded page.',
    },
    portal: {
      badge: 'External PII handoff',
      title: 'PII platform handoff ready',
      description:
        'This run uses the external PII platform for delivery. TMS does not store the report binary; open the handoff link before it expires, then return to run history for TMS-side tracking.',
      expiresPrefix: 'Link expires at',
      estimatedPrefix: 'estimated',
      estimatedSuffix: 'rows will be handled externally.',
      draftStepLabel: '1. Draft in TMS',
      draftStepHint: 'Filters and preview stay in this report workspace.',
      platformStepLabel: '2. Complete in PII platform',
      platformStepHint: 'Use the external link for the sensitive report file.',
      historyStepLabel: '3. Track in history',
      historyStepHint: 'Return here for queue status and non-PII run context.',
      openPlatform: 'Open PII platform',
    },
    preview: {
      title: 'Preview',
      description: 'Preview matches use the current MFR job draft and return a small sample of the result set.',
      unavailableTitle: 'Preview unavailable',
      matchedRowsLabel: 'Matched Rows',
      matchedRowsHint: 'Estimated row count before queueing.',
      platformsLabel: 'Platforms',
      allPlatforms: 'All',
      platformsHint: 'Filter summary from the API response.',
      dateRangeLabel: 'Date Range',
      dateRangeUnbounded: 'Unbounded',
      includeExpiredHint: 'Expired memberships included.',
      excludeExpiredHint: 'Expired memberships excluded.',
      tableColumns: ['Nickname', 'Platform', 'Membership Level', 'Valid Window', 'Status'],
      emptyTitle: 'No MFR rows matched',
      emptyDescription: 'Adjust the filter draft and run another preview.',
      noPreviewTitle: 'No preview requested yet',
      noPreviewDescription: 'Open the MFR job drawer to preview matched rows before queueing a new report job.',
      unnamedCustomer: 'Unnamed customer',
      openEnded: 'open-ended',
    },
    ledger: {
      title: 'MFR jobs',
      description: 'Track queued jobs, cancel eligible requests, and download completed files.',
      filterLabel: 'Job status filter',
      showingPrefix: 'Showing',
      showingJobsSuffix: 'jobs on the current page,',
      showingTotalSuffix: 'in total.',
      unavailableTitle: 'Report jobs unavailable',
      tableColumns: ['File', 'Status', 'Rows', 'Requested', 'Completed', 'Actions'],
      emptyTitle: 'No MFR jobs found',
      emptyDescription: 'Queue a new MFR export or widen the status filter.',
      pendingFileAssignment: 'Pending file assignment',
      pendingRows: 'Pending',
      download: 'Download',
      details: 'Details',
      cancel: 'Cancel',
      cancelDialogTitle: 'Cancel report job?',
      cancelDialogDescription:
        'Only pending or failed jobs can be cancelled. This removes the job from the current queue.',
      cancelDialogConfirm: 'Cancel job',
      downloadAriaLabel: (label: string) => `Download ${label}`,
      detailsAriaLabel: (label: string) => `View details for ${label}`,
      cancelAriaLabel: (label: string) => `Cancel ${label}`,
    },
    notes: {
      title: 'Report Notes',
      description: 'Review catalog availability and delivery handling for this workspace.',
      scopeLabel: 'Scope',
      scopeValue: 'Talent scope',
      scopeHint: 'Published reports in this workspace currently run against the selected talent scope.',
      sensitiveDeliveryLabel: 'Delivery',
      sensitiveDeliveryValue: 'Linked download',
      sensitiveDeliveryHint: 'When a download link is available, that run opens there instead of downloading directly on this page.',
      workflowLabel: 'Workflow',
      workflowValue: 'Directory + history',
      workflowHint: 'Start from the report directory, then track queued runs and downloads in history.',
    },
    drawer: {
      title: 'Create MFR Job',
      description: 'Queue a new member-feedback export with optional scope filters. Preview uses the same draft state as job creation.',
      draftGuideTitle: 'Preview first, then queue',
      draftGuideDescription: 'Filters are generated from the selected report catalog schema. Use Preview rows to confirm the draft before creating the job.',
      codeFiltersTitle: 'Catalog filters',
      codeFiltersDescription: 'Use the report catalog filter schema for primary filters. Leave fields blank for all values.',
      validityTitle: 'Validity window',
      validityDescription: 'Limit memberships by valid-from / valid-to dates and decide whether expired or inactive memberships should be included.',
      outputTitle: 'Output',
      outputDescription: 'Choose the generated file format before queueing the job.',
      advancedTitle: 'Advanced',
      advancedDescription: 'Raw code entry is reserved for advanced fallback fields published by the catalog schema.',
      cancel: 'Cancel',
      closeLabel: 'Close MFR job drawer',
      previewRows: 'Preview rows',
      createPending: 'Queueing MFR job…',
      create: 'Create MFR job',
      unavailableReport: 'This report is not currently available.',
      fields: {
        platformCodes: 'Platform codes',
        platformCodesPlaceholder: 'youtube, bilibili',
        membershipClassCodes: 'Membership class codes',
        membershipClassCodesPlaceholder: 'premium, vip',
        membershipTypeCodes: 'Membership type codes',
        membershipTypeCodesPlaceholder: 'monthly, annual',
        membershipLevelCodes: 'Membership level codes',
        membershipLevelCodesPlaceholder: 'gold, diamond',
        customerStatusCodes: 'Customer status codes',
        customerStatusCodesPlaceholder: 'active, paused',
        downloadFormat: 'Download format',
        validFromStart: 'Valid-from start',
        validFromEnd: 'Valid-from end',
        validToStart: 'Valid-to start',
        validToEnd: 'Valid-to end',
        includeExpired: 'Include expired memberships',
        includeInactive: 'Include inactive memberships',
      },
    },
    detail: {
      title: 'Report Job Detail',
      description: 'Inspect the request snapshot, status timeline, failure reason, and artifacts for this run.',
      closeLabel: 'Close report job detail',
      loading: 'Loading report job detail…',
      unavailableTitle: 'Report job detail unavailable',
      snapshotTitle: 'Parameter Snapshot',
      timelineTitle: 'Status Timeline',
      artifactsTitle: 'Artifacts',
      failureTitle: 'Failure Reason',
      noFailureReason: 'No failure reason recorded.',
      noArtifacts: 'No artifacts have been attached to this run.',
      retryFromFilters: 'Retry from filters',
      requestedAt: 'Requested at',
      format: 'Format',
      filters: 'Filters',
      noFilters: 'No filters were applied.',
      fileSize: 'File size',
      downloadState: 'Download state',
      downloadedAt: 'Downloaded at',
      expiresAt: 'Expires at',
      timelinePhases: {
        queued: 'Queued',
        started: 'Started',
        completed: 'Completed',
        downloaded: 'Downloaded',
        expired: 'Expired',
      },
      downloadStates: {
        available: 'Available',
        consumed: 'Consumed',
        expired: 'Expired',
        unavailable: 'Unavailable',
      },
    },
    options: {
      jobStatus: {
        all: 'All statuses',
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
      reportFormat: {
        xlsx: 'Excel (.xlsx)',
        csv: 'CSV (.csv)',
      },
      jobState: {
        pending: 'Pending',
        running: 'Running',
        retrying: 'Retrying',
        success: 'Success',
        consumed: 'Consumed',
        failed: 'Failed',
        expired: 'Expired',
        cancelled: 'Cancelled',
      },
    },
    common: {
      never: 'Never',
    },
  },
} as const;

export type ReportsManagementCopy = (typeof COPY)['en'];
const COPY_BY_LOCALE = COPY as unknown as Record<SupportedUiLocale, ReportsManagementCopy>;

export function useReportsManagementCopy() {
  const { locale } = useUiLocale();
  const effectiveSelectedLocale = locale;
  const copy = resolveLocaleRecord(effectiveSelectedLocale, COPY_BY_LOCALE) as ReportsManagementCopy;

  return {
    locale: effectiveSelectedLocale,
    copy,
    jobStatusOptions: [
      { value: 'all' as JobStatusFilter, label: copy.options.jobStatus.all },
      { value: 'pending' as JobStatusFilter, label: copy.options.jobStatus.pending },
      { value: 'running' as JobStatusFilter, label: copy.options.jobStatus.running },
      { value: 'retrying' as JobStatusFilter, label: copy.options.jobStatus.retrying },
      { value: 'success' as JobStatusFilter, label: copy.options.jobStatus.success },
      { value: 'consumed' as JobStatusFilter, label: copy.options.jobStatus.consumed },
      { value: 'failed' as JobStatusFilter, label: copy.options.jobStatus.failed },
      { value: 'expired' as JobStatusFilter, label: copy.options.jobStatus.expired },
      { value: 'cancelled' as JobStatusFilter, label: copy.options.jobStatus.cancelled },
    ],
    reportFormatOptions: [
      { value: 'xlsx' as ReportFormat, label: copy.options.reportFormat.xlsx },
      { value: 'csv' as ReportFormat, label: copy.options.reportFormat.csv },
    ],
  };
}

export function formatReportsDateTime(
  locale: SupportedUiLocale ,
  value: string | null,
  fallback: string,
) {
  return formatLocaleDateTime(locale, value, fallback);
}

export function formatReportsNumber(
  locale: SupportedUiLocale ,
  value: number | null,
  pendingLabel: string,
) {
  if (value === null) {
    return pendingLabel;
  }

  return formatLocaleNumber(locale, value);
}

export function getReportsJobStatusLabel(
  locale: SupportedUiLocale ,
  status: ReportJobStatus,
) {
  return (resolveLocaleRecord(locale, COPY_BY_LOCALE) as ReportsManagementCopy).options.jobState[status];
}
