// © 2026 月球厨师莱恩 (TPMOONCHEFRYAN) – PolyForm Noncommercial License

/**
 * Standard error codes used across the application
 * PRD §4.1, 03-认证系统 Part A
 */
export const ErrorCodes = {
  // Authentication errors (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_TOTP_REQUIRED: 'AUTH_TOTP_REQUIRED',
  AUTH_TOTP_INVALID: 'AUTH_TOTP_INVALID',
  AUTH_TOTP_NOT_ENABLED: 'AUTH_TOTP_NOT_ENABLED',
  AUTH_TOTP_ALREADY_ENABLED: 'AUTH_TOTP_ALREADY_ENABLED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_PASSWORD_EXPIRED: 'AUTH_PASSWORD_EXPIRED',
  AUTH_PASSWORD_RESET_REQUIRED: 'AUTH_PASSWORD_RESET_REQUIRED',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_PASSWORD_SAME: 'AUTH_PASSWORD_SAME',
  AUTH_PASSWORD_HISTORY: 'AUTH_PASSWORD_HISTORY',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_RECOVERY_CODE_INVALID: 'AUTH_RECOVERY_CODE_INVALID',
  AUTH_RECOVERY_CODE_EXHAUSTED: 'AUTH_RECOVERY_CODE_EXHAUSTED',

  // User errors (USER_xxx)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_USERNAME_TAKEN: 'USER_USERNAME_TAKEN',

  // Permission errors (PERM_xxx)
  PERM_ACCESS_DENIED: 'PERM_ACCESS_DENIED',
  PERM_SCOPE_INVALID: 'PERM_SCOPE_INVALID',

  // Tenant errors (TENANT_xxx)
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_DISABLED: 'TENANT_DISABLED',
  TENANT_SCHEMA_ERROR: 'TENANT_SCHEMA_ERROR',

  // Validation errors (VALIDATION_xxx)
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID: 'VALIDATION_FIELD_INVALID',

  // Resource errors (RES_xxx)
  RES_NOT_FOUND: 'RES_NOT_FOUND',
  RES_ALREADY_EXISTS: 'RES_ALREADY_EXISTS',
  RES_CONFLICT: 'RES_CONFLICT',
  VERSION_CONFLICT: 'RES_CONFLICT', // Alias for RES_CONFLICT
  RES_VERSION_MISMATCH: 'RES_VERSION_MISMATCH', // PRD §10.1 乐观锁
  CODE_ALREADY_EXISTS: 'CODE_ALREADY_EXISTS',

  // PII Service errors (PII_xxx) - PRD §11.4
  PII_FETCH_FAILED: 'PII_FETCH_FAILED',
  PII_SERVICE_UNAVAILABLE: 'PII_SERVICE_UNAVAILABLE',
  PII_TOKEN_EXPIRED: 'PII_TOKEN_EXPIRED',
  PII_DECRYPTION_FAILED: 'PII_DECRYPTION_FAILED',

  // Import errors (IMP_xxx) - PRD §11.7
  IMP_INVALID_FILE_FORMAT: 'IMP_INVALID_FILE_FORMAT',
  IMP_ROW_VALIDATION_FAILED: 'IMP_ROW_VALIDATION_FAILED',
  IMP_JOB_CANCELLED: 'IMP_JOB_CANCELLED',
  IMP_MAX_ROWS_EXCEEDED: 'IMP_MAX_ROWS_EXCEEDED',

  // Report errors (RPT_xxx) - PRD §20
  RPT_JOB_PENDING: 'RPT_JOB_PENDING',
  RPT_JOB_FAILED: 'RPT_JOB_FAILED',
  RPT_JOB_EXPIRED: 'RPT_JOB_EXPIRED',
  RPT_FILE_NOT_READY: 'RPT_FILE_NOT_READY',

  // Rate limiting (SYS_xxx)
  SYS_RATE_LIMITED: 'SYS_RATE_LIMITED',

  // System errors (SYS_xxx)
  SYS_ERROR: 'SYS_ERROR',
  SYS_MAINTENANCE: 'SYS_MAINTENANCE',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_EXTERNAL_SERVICE_ERROR: 'SYS_EXTERNAL_SERVICE_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * HTTP Status codes mapping
 */
export const ErrorHttpStatus: Record<ErrorCode, number> = {
  // Auth errors
  [ErrorCodes.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCodes.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCodes.AUTH_TOKEN_INVALID]: 401,
  [ErrorCodes.AUTH_REFRESH_TOKEN_EXPIRED]: 401,
  [ErrorCodes.AUTH_REFRESH_TOKEN_INVALID]: 401,
  [ErrorCodes.AUTH_TOTP_REQUIRED]: 401,
  [ErrorCodes.AUTH_TOTP_INVALID]: 401,
  [ErrorCodes.AUTH_TOTP_NOT_ENABLED]: 400,
  [ErrorCodes.AUTH_TOTP_ALREADY_ENABLED]: 400,
  [ErrorCodes.AUTH_SESSION_EXPIRED]: 401,
  [ErrorCodes.AUTH_SESSION_INVALID]: 401,
  [ErrorCodes.AUTH_PASSWORD_EXPIRED]: 401,
  [ErrorCodes.AUTH_PASSWORD_RESET_REQUIRED]: 401,
  [ErrorCodes.AUTH_PASSWORD_WEAK]: 422,
  [ErrorCodes.AUTH_PASSWORD_SAME]: 422,
  [ErrorCodes.AUTH_PASSWORD_HISTORY]: 422,
  [ErrorCodes.AUTH_ACCOUNT_LOCKED]: 401,
  [ErrorCodes.AUTH_ACCOUNT_DISABLED]: 403,
  [ErrorCodes.AUTH_RECOVERY_CODE_INVALID]: 401,
  [ErrorCodes.AUTH_RECOVERY_CODE_EXHAUSTED]: 401,

  // User errors
  [ErrorCodes.USER_NOT_FOUND]: 404,
  [ErrorCodes.USER_ALREADY_EXISTS]: 409,
  [ErrorCodes.USER_EMAIL_TAKEN]: 409,
  [ErrorCodes.USER_USERNAME_TAKEN]: 409,

  // Permission errors
  [ErrorCodes.PERM_ACCESS_DENIED]: 403,
  [ErrorCodes.PERM_SCOPE_INVALID]: 403,

  // Tenant errors
  [ErrorCodes.TENANT_NOT_FOUND]: 404,
  [ErrorCodes.TENANT_DISABLED]: 403,
  [ErrorCodes.TENANT_SCHEMA_ERROR]: 500,

  // Validation errors
  [ErrorCodes.VALIDATION_FAILED]: 400,
  [ErrorCodes.VALIDATION_FIELD_REQUIRED]: 400,
  [ErrorCodes.VALIDATION_FIELD_INVALID]: 400,

  // Resource errors
  [ErrorCodes.RES_NOT_FOUND]: 404,
  [ErrorCodes.RES_ALREADY_EXISTS]: 409,
  [ErrorCodes.RES_CONFLICT]: 409,
  [ErrorCodes.RES_VERSION_MISMATCH]: 409,
  [ErrorCodes.CODE_ALREADY_EXISTS]: 409,

  // PII errors
  [ErrorCodes.PII_FETCH_FAILED]: 502,
  [ErrorCodes.PII_SERVICE_UNAVAILABLE]: 503,
  [ErrorCodes.PII_TOKEN_EXPIRED]: 401,
  [ErrorCodes.PII_DECRYPTION_FAILED]: 500,

  // Import errors
  [ErrorCodes.IMP_INVALID_FILE_FORMAT]: 400,
  [ErrorCodes.IMP_ROW_VALIDATION_FAILED]: 400,
  [ErrorCodes.IMP_JOB_CANCELLED]: 400,
  [ErrorCodes.IMP_MAX_ROWS_EXCEEDED]: 400,

  // Report errors
  [ErrorCodes.RPT_JOB_PENDING]: 202,
  [ErrorCodes.RPT_JOB_FAILED]: 500,
  [ErrorCodes.RPT_JOB_EXPIRED]: 410,
  [ErrorCodes.RPT_FILE_NOT_READY]: 202,

  // System errors
  [ErrorCodes.SYS_RATE_LIMITED]: 429,
  [ErrorCodes.SYS_ERROR]: 500,
  [ErrorCodes.SYS_MAINTENANCE]: 503,
  [ErrorCodes.SYS_DATABASE_ERROR]: 500,
  [ErrorCodes.SYS_EXTERNAL_SERVICE_ERROR]: 502,
};
