// © 2026 月球厨师莱恩 (TPMOONCHEFRYAN) – PolyForm Noncommercial License

/**
 * Technical Event Types
 * Based on PRD §15 日志模块
 */
export enum TechEventType {
  // Import related
  IMPORT_JOB_STARTED = 'IMPORT_JOB_STARTED',
  IMPORT_JOB_COMPLETED = 'IMPORT_JOB_COMPLETED',
  IMPORT_ROW_FAILED = 'IMPORT_ROW_FAILED',

  // Export related
  EXPORT_JOB_STARTED = 'EXPORT_JOB_STARTED',
  EXPORT_JOB_COMPLETED = 'EXPORT_JOB_COMPLETED',
  EXPORT_JOB_FAILED = 'EXPORT_JOB_FAILED',

  // Permission related
  PERMISSION_SNAPSHOT_STARTED = 'PERMISSION_SNAPSHOT_STARTED',
  PERMISSION_SNAPSHOT_COMPLETED = 'PERMISSION_SNAPSHOT_COMPLETED',
  PERMISSION_SNAPSHOT_FAILED = 'PERMISSION_SNAPSHOT_FAILED',

  // Authentication related
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  AUTH_2FA_ENABLED = 'AUTH_2FA_ENABLED',
  AUTH_RECOVERY_CODE_USED = 'AUTH_RECOVERY_CODE_USED',
  AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET',
  AUTH_LOGOUT = 'AUTH_LOGOUT',

  // PII related
  PII_ACCESS_REQUESTED = 'PII_ACCESS_REQUESTED',
  PII_ACCESS_GRANTED = 'PII_ACCESS_GRANTED',
  PII_ACCESS_DENIED = 'PII_ACCESS_DENIED',
  PII_FETCH_FAILED = 'PII_FETCH_FAILED',

  // Report related
  REPORT_JOB_CREATED = 'REPORT_JOB_CREATED',
  REPORT_JOB_STARTED = 'REPORT_JOB_STARTED',
  REPORT_JOB_COMPLETED = 'REPORT_JOB_COMPLETED',
  REPORT_JOB_FAILED = 'REPORT_JOB_FAILED',
  REPORT_DOWNLOADED = 'REPORT_DOWNLOADED',
  REPORT_PII_BATCH_REQUESTED = 'REPORT_PII_BATCH_REQUESTED',
  REPORT_JOBS_EXPIRED = 'REPORT_JOBS_EXPIRED',

  // System related
  SYSTEM_STARTUP = 'SYSTEM_STARTUP',
  SYSTEM_SHUTDOWN = 'SYSTEM_SHUTDOWN',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SYSTEM_INFO = 'SYSTEM_INFO',
  SECURITY_EVENT = 'SECURITY_EVENT',

  // Log cleanup
  LOG_CLEANUP_STARTED = 'LOG_CLEANUP_STARTED',
  LOG_CLEANUP_COMPLETED = 'LOG_CLEANUP_COMPLETED',

  // Tenant related
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_ACTIVATED = 'TENANT_ACTIVATED',
  TENANT_DEACTIVATED = 'TENANT_DEACTIVATED',

  // User management
  USER_CREATED = 'USER_CREATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_REACTIVATED = 'USER_REACTIVATED',

  // Scheduled tasks
  SCHEDULED_TASK_STARTED = 'SCHEDULED_TASK_STARTED',
  SCHEDULED_TASK_COMPLETED = 'SCHEDULED_TASK_COMPLETED',
  SCHEDULED_TASK_FAILED = 'SCHEDULED_TASK_FAILED',
  MEMBERSHIP_BATCH_PROCESSED = 'MEMBERSHIP_BATCH_PROCESSED',
}

/**
 * Technical Event Scope
 */
export enum TechEventScope {
  GENERAL = 'general',
  SECURITY = 'security',
  IMPORT = 'import',
  EXPORT = 'export',
  PII = 'pii',
  PERMISSION = 'permission',
  INTEGRATION = 'integration',
  REPORT = 'report',
  SCHEDULED = 'scheduled',
}

// Note: LogSeverity is exported from types/enums.ts

/**
 * Integration direction
 */
export enum IntegrationDirection {
  INBOUND = 'inbound',
  OUTBOUND = 'outbound',
}
