import { type SupportedUiLocale } from '@tcrn/shared';

import { resolveLocaleRecord } from '@/platform/runtime/locale/locale-text';

const COPY = {
  en: {
    title: 'API Registry',
    subtitle: 'Read-only operation metadata, Swagger sync, and gateway readiness.',
    refresh: 'Refresh',
    download: 'Download JSON',
    openDocs: 'Open Swagger',
    openDrift: 'Open drift report',
    copyCode: 'Copy code',
    copied: 'Copied',
    retry: 'Retry',
    close: 'Close',
    loadingTitle: 'Loading API registry',
    loadingDescription: 'Reading generated registry and drift state.',
    emptyTitle: 'No registry operations',
    emptyDescription: 'The generated source snapshot is empty or unavailable.',
    errorTitle: 'Registry unavailable',
    deniedTitle: 'AC permission required',
    clean: 'Clean',
    failed: 'Drift failed',
    version: 'Version',
    sourceCommit: 'Source commit',
    generatedAt: 'Generated',
    drift: 'Drift',
    policy: 'Policy',
    group: 'Group',
    module: 'Module',
    capability: 'Capability',
    exposure: 'Exposure',
    stability: 'Stability',
    deprecation: 'Deprecation',
    search: 'Search operations',
    all: 'All',
    operation: 'Operation',
    method: 'Method',
    path: 'Path',
    docs: 'Docs',
    viewDetails: 'View details',
    permissions: 'Permissions',
    scope: 'Scope',
    schemas: 'Schemas',
    gateway: 'Gateway',
    builder: 'Builder',
    detailTitle: 'Operation detail',
    readonly: 'Read-only',
    dynamicPermission: 'Dynamic permission proof required',
    noPermission: 'No static RBAC permission',
    eligible: 'Eligible',
    notEligible: 'Not eligible',
    warnings: 'Warnings',
    operationsShown: 'operations shown',
    deprecated: 'Deprecated',
    notDeprecated: 'Not deprecated',
  },
  zh_HANS: {
    title: 'API 注册表',
    subtitle: '只读查看操作元数据、Swagger 同步与网关就绪状态。',
    refresh: '刷新',
    download: '下载 JSON',
    openDocs: '打开 Swagger',
    openDrift: '打开漂移报告',
    copyCode: '复制代码',
    copied: '已复制',
    retry: '重试',
    close: '关闭',
    loadingTitle: '正在加载 API 注册表',
    loadingDescription: '正在读取生成的注册表与漂移状态。',
    emptyTitle: '暂无注册操作',
    emptyDescription: '生成的源快照为空或不可用。',
    errorTitle: '注册表不可用',
    deniedTitle: '需要 AC 权限',
    clean: '干净',
    failed: '漂移失败',
    version: '版本',
    sourceCommit: '源提交',
    generatedAt: '生成时间',
    drift: '漂移',
    policy: '策略',
    group: '分组',
    module: '模块',
    capability: '能力',
    exposure: '暴露范围',
    stability: '稳定性',
    deprecation: '弃用',
    search: '搜索操作',
    all: '全部',
    operation: '操作',
    method: '方法',
    path: '路径',
    docs: '文档',
    viewDetails: '查看详情',
    permissions: '权限',
    scope: '范围',
    schemas: 'Schema',
    gateway: '网关',
    builder: 'Builder',
    detailTitle: '操作详情',
    readonly: '只读',
    dynamicPermission: '需要动态权限证明',
    noPermission: '无静态 RBAC 权限',
    eligible: '可导出',
    notEligible: '不可导出',
    warnings: '警告',
    operationsShown: '个操作',
    deprecated: '已弃用',
    notDeprecated: '未弃用',
  },
  zh_HANT: {
    title: 'API 註冊表',
    subtitle: '唯讀檢視操作中繼資料、Swagger 同步與閘道就緒狀態。',
    refresh: '重新整理',
    download: '下載 JSON',
    openDocs: '開啟 Swagger',
    openDrift: '開啟漂移報告',
    copyCode: '複製代碼',
    copied: '已複製',
    retry: '重試',
    close: '關閉',
    loadingTitle: '正在載入 API 註冊表',
    loadingDescription: '正在讀取產生的註冊表與漂移狀態。',
    emptyTitle: '尚無註冊操作',
    emptyDescription: '產生的來源快照為空或不可用。',
    errorTitle: '註冊表不可用',
    deniedTitle: '需要 AC 權限',
    clean: '乾淨',
    failed: '漂移失敗',
    version: '版本',
    sourceCommit: '來源提交',
    generatedAt: '產生時間',
    drift: '漂移',
    policy: '策略',
    group: '分組',
    module: '模組',
    capability: '能力',
    exposure: '暴露範圍',
    stability: '穩定性',
    deprecation: '棄用',
    search: '搜尋操作',
    all: '全部',
    operation: '操作',
    method: '方法',
    path: '路徑',
    docs: '文件',
    viewDetails: '檢視詳情',
    permissions: '權限',
    scope: '範圍',
    schemas: 'Schema',
    gateway: '閘道',
    builder: 'Builder',
    detailTitle: '操作詳情',
    readonly: '唯讀',
    dynamicPermission: '需要動態權限證明',
    noPermission: '無靜態 RBAC 權限',
    eligible: '可匯出',
    notEligible: '不可匯出',
    warnings: '警告',
    operationsShown: '個操作',
    deprecated: '已棄用',
    notDeprecated: '未棄用',
  },
  ja: {
    title: 'API レジストリ',
    subtitle: '操作メタデータ、Swagger 同期、ゲートウェイ準備状況を読み取り専用で確認します。',
    refresh: '更新',
    download: 'JSON をダウンロード',
    openDocs: 'Swagger を開く',
    openDrift: 'ドリフトレポートを開く',
    copyCode: 'コードをコピー',
    copied: 'コピー済み',
    retry: '再試行',
    close: '閉じる',
    loadingTitle: 'API レジストリを読み込み中',
    loadingDescription: '生成済みレジストリとドリフト状態を読み込んでいます。',
    emptyTitle: '登録済み操作はありません',
    emptyDescription: '生成されたソーススナップショットが空、または利用できません。',
    errorTitle: 'レジストリを利用できません',
    deniedTitle: 'AC 権限が必要です',
    clean: '正常',
    failed: 'ドリフト失敗',
    version: 'バージョン',
    sourceCommit: 'ソースコミット',
    generatedAt: '生成日時',
    drift: 'ドリフト',
    policy: 'ポリシー',
    group: 'グループ',
    module: 'モジュール',
    capability: 'ケイパビリティ',
    exposure: '公開範囲',
    stability: '安定性',
    deprecation: '非推奨',
    search: '操作を検索',
    all: 'すべて',
    operation: '操作',
    method: 'メソッド',
    path: 'パス',
    docs: 'Docs',
    viewDetails: '詳細を表示',
    permissions: '権限',
    scope: 'スコープ',
    schemas: 'Schema',
    gateway: 'ゲートウェイ',
    builder: 'Builder',
    detailTitle: '操作詳細',
    readonly: '読み取り専用',
    dynamicPermission: '動的権限の証跡が必要',
    noPermission: '静的 RBAC 権限なし',
    eligible: '対象',
    notEligible: '対象外',
    warnings: '警告',
    operationsShown: '件の操作',
    deprecated: '非推奨',
    notDeprecated: '非推奨ではない',
  },
  ko: {
    title: 'API 레지스트리',
    subtitle: '작업 메타데이터, Swagger 동기화, 게이트웨이 준비 상태를 읽기 전용으로 확인합니다.',
    refresh: '새로고침',
    download: 'JSON 다운로드',
    openDocs: 'Swagger 열기',
    openDrift: '드리프트 보고서 열기',
    copyCode: '코드 복사',
    copied: '복사됨',
    retry: '다시 시도',
    close: '닫기',
    loadingTitle: 'API 레지스트리 로드 중',
    loadingDescription: '생성된 레지스트리와 드리프트 상태를 읽고 있습니다.',
    emptyTitle: '등록된 작업 없음',
    emptyDescription: '생성된 소스 스냅샷이 비어 있거나 사용할 수 없습니다.',
    errorTitle: '레지스트리를 사용할 수 없음',
    deniedTitle: 'AC 권한 필요',
    clean: '정상',
    failed: '드리프트 실패',
    version: '버전',
    sourceCommit: '소스 커밋',
    generatedAt: '생성 시간',
    drift: '드리프트',
    policy: '정책',
    group: '그룹',
    module: '모듈',
    capability: '기능',
    exposure: '노출 범위',
    stability: '안정성',
    deprecation: '사용 중단',
    search: '작업 검색',
    all: '전체',
    operation: '작업',
    method: '메서드',
    path: '경로',
    docs: '문서',
    viewDetails: '상세 보기',
    permissions: '권한',
    scope: '범위',
    schemas: 'Schema',
    gateway: '게이트웨이',
    builder: 'Builder',
    detailTitle: '작업 상세',
    readonly: '읽기 전용',
    dynamicPermission: '동적 권한 증거 필요',
    noPermission: '정적 RBAC 권한 없음',
    eligible: '가능',
    notEligible: '불가',
    warnings: '경고',
    operationsShown: '개 작업',
    deprecated: '사용 중단',
    notDeprecated: '사용 중단 아님',
  },
  fr: {
    title: 'Registre API',
    subtitle:
      'Metadonnees operation, synchronisation Swagger et readiness gateway en lecture seule.',
    refresh: 'Actualiser',
    download: 'Telecharger JSON',
    openDocs: 'Ouvrir Swagger',
    openDrift: 'Ouvrir rapport drift',
    copyCode: 'Copier le code',
    copied: 'Copie',
    retry: 'Reessayer',
    close: 'Fermer',
    loadingTitle: 'Chargement du registre API',
    loadingDescription: 'Lecture du registre genere et de l etat de drift.',
    emptyTitle: 'Aucune operation',
    emptyDescription: 'Le snapshot source genere est vide ou indisponible.',
    errorTitle: 'Registre indisponible',
    deniedTitle: 'Permission AC requise',
    clean: 'Propre',
    failed: 'Drift en echec',
    version: 'Version',
    sourceCommit: 'Commit source',
    generatedAt: 'Genere',
    drift: 'Drift',
    policy: 'Politique',
    group: 'Groupe',
    module: 'Module',
    capability: 'Capacite',
    exposure: 'Exposition',
    stability: 'Stabilite',
    deprecation: 'Depreciation',
    search: 'Rechercher',
    all: 'Tous',
    operation: 'Operation',
    method: 'Methode',
    path: 'Chemin',
    docs: 'Docs',
    viewDetails: 'Voir detail',
    permissions: 'Permissions',
    scope: 'Portee',
    schemas: 'Schemas',
    gateway: 'Gateway',
    builder: 'Builder',
    detailTitle: 'Detail operation',
    readonly: 'Lecture seule',
    dynamicPermission: 'Preuve de permission dynamique requise',
    noPermission: 'Aucune permission RBAC statique',
    eligible: 'Eligible',
    notEligible: 'Non eligible',
    warnings: 'Avertissements',
    operationsShown: 'operations affichees',
    deprecated: 'Deprecie',
    notDeprecated: 'Non deprecie',
  },
} as const;

export type ApiRegistryCopy = (typeof COPY)['en'];
const COPY_RECORD = COPY as unknown as Record<SupportedUiLocale, ApiRegistryCopy>;

export function useApiRegistryCopy(locale: SupportedUiLocale) {
  return resolveLocaleRecord(locale, COPY_RECORD) as ApiRegistryCopy;
}
