import type { PermissionAction, RbacRolePolicyEffect, SupportedUiLocale } from '@tcrn/shared';

import { useUiLocale } from '@/platform/runtime/locale/locale-provider';
import {
  formatLocaleDateTime,
  pickLocaleText,
  resolveLocaleRecord,
} from '@/platform/runtime/locale/locale-text';

type UserManagementLocale = SupportedUiLocale;

const ROLE_ACTION_LABELS: Record<SupportedUiLocale, Record<PermissionAction, string>> = {
  en: {
    read: 'Read',
    write: 'Update',
    delete: 'Delete',
    execute: 'Execute',
    admin: 'Admin',
  },
  zh_HANS: {
    read: '读取',
    write: '更新',
    delete: '删除',
    execute: '执行',
    admin: '管理',
  },
  zh_HANT: {
    read: '读取',
    write: '更新',
    delete: '删除',
    execute: '执行',
    admin: '管理',
  },
  ja: {
    read: '閲覧',
    write: '更新',
    delete: '削除',
    execute: '実行',
    admin: '管理',
  },
  ko: {
    read: 'Read',
    write: 'Update',
    delete: 'Delete',
    execute: 'Execute',
    admin: 'Admin',
  },
  fr: {
    read: 'Read',
    write: 'Update',
    delete: 'Delete',
    execute: 'Execute',
    admin: 'Admin',
  },
};

const ROLE_PERMISSION_OPTION_LABELS: Record<
  SupportedUiLocale,
  Record<RbacRolePolicyEffect | 'unset', string>
> = {
  en: {
    unset: 'Unset',
    grant: 'Grant',
    deny: 'Deny',
  },
  zh_HANS: {
    unset: '未设置',
    grant: '允许',
    deny: '拒绝',
  },
  zh_HANT: {
    unset: '未设置',
    grant: '允许',
    deny: '拒绝',
  },
  ja: {
    unset: '未設定',
    grant: '許可',
    deny: '拒否',
  },
  ko: {
    unset: 'Unset',
    grant: 'Grant',
    deny: 'Deny',
  },
  fr: {
    unset: 'Unset',
    grant: 'Grant',
    deny: 'Deny',
  },
};

const SCOPE_TYPE_LABELS: Record<
  SupportedUiLocale,
  Record<'tenant' | 'subsidiary' | 'talent', string>
> = {
  en: {
    tenant: 'Tenant',
    subsidiary: 'Subsidiary',
    talent: 'Talent',
  },
  zh_HANS: {
    tenant: '租户',
    subsidiary: '分目录',
    talent: '艺人',
  },
  zh_HANT: {
    tenant: '租户',
    subsidiary: '分目录',
    talent: '艺人',
  },
  ja: {
    tenant: 'テナント',
    subsidiary: '配下スコープ',
    talent: 'タレント',
  },
  ko: {
    tenant: 'Tenant',
    subsidiary: 'Subsidiary',
    talent: 'Talent',
  },
  fr: {
    tenant: 'Tenant',
    subsidiary: 'Subsidiary',
    talent: 'Talent',
  },
};

const DELEGATE_TYPE_LABELS: Record<SupportedUiLocale, Record<'user' | 'role', string>> = {
  en: {
    user: 'User',
    role: 'Role',
  },
  zh_HANS: {
    user: '用户',
    role: '角色',
  },
  zh_HANT: {
    user: '用户',
    role: '角色',
  },
  ja: {
    user: 'ユーザー',
    role: 'ロール',
  },
  ko: {
    user: 'User',
    role: 'Role',
  },
  fr: {
    user: 'User',
    role: 'Role',
  },
};

const LANGUAGE_LABELS: Record<SupportedUiLocale, Record<SupportedUiLocale, string>> = {
  en: {
    en: 'English',
    zh_HANS: 'Simplified Chinese',
    zh_HANT: 'Traditional Chinese',
    ja: 'Japanese',
    ko: 'Korean',
    fr: 'French',
  },
  zh_HANS: {
    en: '英语',
    zh_HANS: '简体中文',
    zh_HANT: '繁體中文',
    ja: '日语',
    ko: '韩语',
    fr: '法语',
  },
  zh_HANT: {
    en: '英语',
    zh_HANS: '简体中文',
    zh_HANT: '繁體中文',
    ja: '日语',
    ko: '韩语',
    fr: '法语',
  },
  ja: {
    en: '英語',
    zh_HANS: '簡体字中国語',
    zh_HANT: '繁体字中国語',
    ja: '日本語',
    ko: '韓国語',
    fr: 'フランス語',
  },
  ko: {
    en: 'English',
    zh_HANS: 'Simplified Chinese',
    zh_HANT: 'Traditional Chinese',
    ja: 'Japanese',
    ko: 'Korean',
    fr: 'French',
  },
  fr: {
    en: 'English',
    zh_HANS: 'Simplified Chinese',
    zh_HANT: 'Traditional Chinese',
    ja: 'Japanese',
    ko: 'Korean',
    fr: 'French',
  },
};

const ROLE_RESOURCE_COLUMN_LABELS: Record<SupportedUiLocale, string> = {
  en: 'Resource',
  zh_HANS: '资源',
  zh_HANT: '资源',
  ja: 'リソース',
  ko: 'Resource',
  fr: 'Resource',
};

const EXPLICIT_PERMISSION_COUNT_LABELS: Record<SupportedUiLocale, (count: number) => string> = {
  en: (count) => `${count} explicit permission${count === 1 ? '' : 's'}`,
  zh_HANS: (count) => `${count} 条显式权限`,
  zh_HANT: (count) => `${count} 條顯式權限`,
  ja: (count) => `${count} 件の明示的権限`,
  ko: (count) => `${count} explicit permission${count === 1 ? '' : 's'}`,
  fr: (count) =>
    `${count} autorisation${count === 1 ? '' : 's'} explicite${count === 1 ? '' : 's'}`,
};

const COPY = {
  en: {
    shared: {
      cancel: 'Cancel',
      confirm: 'Confirm',
      confirmAction: 'Confirm action',
      never: 'Never',
      unavailable: 'Unavailable',
      seen: 'Seen',
      tenantWorkspace: 'Tenant',
      acWorkspace: 'Platform',
      tenantAccessLabel: 'tenant access',
      acAccessLabel: 'platform access',
      tenantSessionLabel: 'tenant context',
      acSessionLabel: 'platform context',
      tenantDirectoryLabel: 'tenant user directory',
      acDirectoryLabel: 'AC identity directory',
      tenantRoot: 'Tenant root',
      unnamedScope: 'Unnamed scope',
      tenantWideAssignment: 'Tenant-wide assignment',
      tenantWideBinding: 'Tenant-wide binding',
      tenantWideVisibility: 'Tenant-wide visibility',
      grantedLabel: 'Granted',
      expiresLabel: 'Expires',
      includesSubunits: 'Includes subunits',
      inherit: 'Inherit',
      userActive: 'User Active',
      userInactive: 'User Inactive',
      protectedRole: 'Built-in locked',
      customRole: 'Custom role',
      save: 'Save',
      remove: 'Remove',
      noCompatibleRoles: 'No compatible roles',
      assignLinks: (count: number) => `${count} active links`,
      scopeCount: (count: number) => `${count} scope${count === 1 ? '' : 's'}`,
      userCount: (count: number) => `${count} user${count === 1 ? '' : 's'}`,
      assignmentCount: (count: number) => `${count} assignment${count === 1 ? '' : 's'}`,
      inheritedAssignments: (count: number) =>
        `${count} inherited assignment${count === 1 ? '' : 's'} currently propagate access.`,
    },
    management: {
      pageUnavailableTitle: 'User management is unavailable',
      pageUnavailableDescription: (workspaceAccessLabel: string) =>
        `The ${workspaceAccessLabel} could not load users, roles, or delegated-admin resources.`,
      badge: (workspaceLabel: string) => workspaceLabel,
      title: 'Identity, role, and delegation control',
      description:
        'Manage users, role definitions, and delegation here. Use dedicated pages when you need to create or edit.',
      summaryVisibleUsersLabel: 'Visible Users',
      summaryVisibleUsersHint: (_workspaceSessionLabel: string) =>
        'Users matching the current filters.',
      summaryRoleTemplatesLabel: 'Role Templates',
      summaryRoleTemplatesHint: 'Role permission templates available for assignment are shown here.',
      summaryDelegationsLabel: 'Delegations',
      summaryDelegationsHint:
        'Delegated-admin records can target subsidiary or talent scope from this page.',
      tabs: {
        users: 'Users',
        roles: 'Roles',
        delegation: 'Delegation',
      },
      users: {
        title: 'System users',
        description:
          'Keep the list focused on search, status, and account actions. Creating and editing users happens on dedicated pages.',
        newUser: 'New user',
        searchLabel: 'Search',
        searchPlaceholder: 'Search username, email, or display name',
        statusLabel: 'Status',
        statusAll: 'All users',
        statusActive: 'Active only',
        statusInactive: 'Inactive only',
        unavailableTitle: 'System users unavailable',
        emptyTitle: 'No system users matched this filter',
        emptyDescription: (workspaceDirectoryLabel: string) =>
          `Adjust the search or status filter to view other users in the ${workspaceDirectoryLabel}.`,
        columns: ['User', 'Status', 'Security', 'Last Login', 'Created', 'Actions'],
        active: 'Active',
        inactive: 'Inactive',
        resetRequired: 'Reset Required',
        totpEnabled: 'TOTP Enabled',
        noTotp: 'No TOTP',
        edit: 'Edit',
        requireTotp: 'Require TOTP',
        requireTotpTitle: (name: string) => `Require TOTP for ${name}?`,
        requireTotpDescription:
          'The next successful login will require this user to complete TOTP enrollment before access is restored.',
        requireTotpConfirm: 'Require TOTP',
        requireTotpPending: 'Saving TOTP requirement…',
        requireTotpSuccess: (name: string) => `${name} must configure TOTP on next login.`,
        requireTotpError: 'Failed to mark the user for TOTP enrollment.',
        deactivate: 'Deactivate',
        deactivateTitle: (name: string) => `Deactivate ${name}?`,
        deactivateDescription: (workspaceAccessLabel: string) =>
          `This user will lose active ${workspaceAccessLabel} until the account is reactivated.`,
        deactivateConfirm: 'Deactivate user',
        deactivatePending: 'Deactivating user…',
        deactivateSuccess: (name: string) => `${name} was deactivated.`,
        deactivateError: 'Failed to deactivate system user.',
        reactivate: 'Reactivate',
        reactivateTitle: (name: string) => `Reactivate ${name}?`,
        reactivateDescription: (workspaceAccessLabel: string) =>
          `Reactivating this user restores ${workspaceAccessLabel} without resetting the rest of the account profile.`,
        reactivateConfirm: 'Reactivate user',
        reactivatePending: 'Reactivating user…',
        reactivateSuccess: (name: string) => `${name} was reactivated.`,
        reactivateError: 'Failed to reactivate system user.',
      },
      roles: {
        title: 'Roles',
        description:
          'Review role coverage here, then open a dedicated role page when deeper changes are needed.',
        newRole: 'New role',
        unavailableTitle: 'Roles unavailable',
        emptyTitle: 'No roles available',
        emptyDescription: (workspaceAccessLabel: string) =>
          `No roles are currently available for ${workspaceAccessLabel}.`,
        columns: ['Role', 'Coverage', 'Users', 'Template', 'Updated', 'Actions'],
        permissions: (count: number) => `${count} permissions`,
        assignedUsers: (count: number) => `${count} assigned users`,
        protected: 'Built-in locked',
        custom: 'Custom role',
        edit: 'Edit',
      },
      delegation: {
        title: 'Delegated administration',
        description:
          'Delegate subsidiary or talent administration with a clear scope and current grant list.',
        grantTitle: 'Grant delegated admin',
        grantDescription: 'Choose a visible scope and assign a user or role.',
        grantButton: 'Grant delegation',
        grantPending: 'Granting delegation…',
        loadingTitle: 'Loading delegatable scopes',
        loadingDescription:
          'The organization tree is loading so the form can offer the right scopes.',
        noScopesTitle: 'No delegatable scopes available',
        noScopesDescription:
          'No visible subsidiary or talent scopes are available for delegated administration.',
        scopeTypeLabel: 'Scope type',
        scopeTypeSubsidiary: 'Subsidiary',
        scopeTypeTalent: 'Talent',
        scopeTargetLabel: 'Scope target',
        delegateTypeLabel: 'Delegate type',
        delegateTypeUser: 'User',
        delegateTypeRole: 'Role',
        delegateLabel: 'Delegate',
        sourceNote:
          'Delegation options come from the visible organization tree plus the current users and roles.',
        selectScopeError: 'Select a scope before granting delegated administration.',
        selectDelegateError: 'Select a delegate before granting delegated administration.',
        createError: 'Failed to create delegated admin assignment.',
        createSuccess: (delegateName: string, scopeName: string) =>
          `${delegateName} was granted delegated administration for ${scopeName}.`,
        unavailableTitle: 'Delegated admins unavailable',
        emptyTitle: 'No delegated admins configured',
        emptyDescription: (isAcWorkspace: boolean) =>
          `This ${isAcWorkspace ? 'AC tenant' : 'tenant'} currently has no subsidiary- or talent-scoped delegated-admin grants.`,
        columns: ['Scope', 'Delegate', 'Granted By', 'Granted At', 'Actions'],
        systemGrantedBy: 'System',
        remove: 'Remove',
        removeTitle: (name: string) => `Remove ${name}?`,
        removeDescription:
          'This removes the delegated-admin grant from the selected scope and immediately removes the assignment from the list.',
        removeConfirm: 'Remove delegation',
        removePending: 'Removing delegation…',
        removeSuccess: (name: string) => `Delegated administration for ${name} was removed.`,
        removeError: 'Failed to remove delegated admin.',
      },
    },
    editor: {
      loading: 'Loading user editor…',
      unavailableTitle: 'User editor unavailable',
      loadError: 'Failed to load system user detail.',
      supportDataError: 'Failed to load role and scope options.',
      missingTargetError: 'Missing system user id.',
      createError: 'Failed to create system user.',
      updateError: 'Failed to update system user.',
      assignmentSelectRoleError: 'Select a role before assigning it.',
      assignmentCreateError: 'Failed to assign role.',
      assignmentUpdateError: 'Failed to update role assignment.',
      assignmentRemoveError: 'Failed to remove role assignment.',
      assignmentPermissionTitle: 'Role assignment unavailable for this scope',
      assignmentPermissionDescription:
        'Your current session cannot assign roles at the selected scope. Profile editing remains available.',
      validation: {
        username: 'Username must be at least 3 characters.',
        email: 'Email address is required.',
        initialPassword: 'Initial password must be at least 12 characters.',
      },
      backToInventory: 'Back to users',
      badge: (workspaceLabel: string) => workspaceLabel,
      createTitle: 'Create system user',
      createDescription:
        'Create a new user on a dedicated page so profile data and role access stay focused.',
      editDescription:
        'Use this page to update profile data, scoped role access, and security actions.',
      accountProfileTitle: 'Account profile',
      fields: {
        username: 'Username',
        email: 'Email',
        initialPassword: 'Initial password',
        forceReset: 'Force password reset on first login',
        displayName: 'Display name',
        phone: 'Phone',
        preferredLanguage: 'Preferred language',
      },
      forceResetDescription:
        'Keep the bootstrap password short-lived by forcing the user through a reset after the first authenticated session.',
      immutableIdentityDescription:
        'Username and email remain immutable here. Password rotation stays in profile and security workflows instead of being hidden inside a crowded list view.',
      submitCreate: 'Create user',
      submitSave: 'Save profile',
      pendingCreate: 'Creating user…',
      pendingSave: 'Saving profile…',
      summaryRoleAssignmentsLabel: 'Role Assignments',
      summaryRoleAssignmentsHint: 'Current role assignments for this user.',
      summaryScopeAccessLabel: 'Scope Access',
      summaryScopeAccessHint: 'Direct visibility rules currently attached to this user.',
      summaryLastLoginLabel: 'Last Login',
      lastLoginSeen: 'Seen',
      lastLoginNeverHint: 'This user has not logged in yet.',
      updateSuccess: (name: string) => `${name} was updated.`,
      scopedAssignmentsTitle: 'Scoped role assignments',
      scopedAssignmentsDescription:
        'Assign roles at tenant, subsidiary, or talent scope from this page. The list page stays focused on browsing.',
      manageRoleTemplates: 'Manage role templates',
      scopeField: 'Scope',
      roleField: 'Role',
      expiresAtField: 'Expires at',
      assignmentInheritLabel: 'Inherit to child scopes when supported',
      assignmentScopeWarning:
        'Changing scope, inheritance, or expiration can expand or contract effective access. Review the before/after access summary before saving.',
      assignmentInitialAdminWarning:
        'Initial Admin grants every permission in this tenant. Keep at least one active tenant-scope Initial Admin assignment before saving.',
      assignmentRemovalWarning:
        "Removing this assignment may change the user's effective access. Review the affected scope, inheritance, expiration, and snapshot refresh result before saving.",
      assignmentSnapshotRefreshExpectation:
        'Permission version and snapshot refresh will be checked after save.',
      assignmentImpactSummary: (
        roleName: string,
        userName: string,
        scopeName: string,
        inheritState: string,
        expiresAt: string
      ) =>
        `Role: ${roleName}. User: ${userName}. Scope: ${scopeName}. Inherit: ${inheritState}. Expires: ${expiresAt}.`,
      assignmentCreateInitialAdminTitle: 'Assign Initial Admin?',
      assignmentCreateInitialAdminConfirm: 'Assign Initial Admin',
      assignmentUpdateTitle: (roleName: string) => `Save changes to ${roleName} assignment?`,
      assignmentUpdateConfirm: 'Save assignment',
      assignmentUpdatePending: 'Saving assignment…',
      assignmentRemovalTitle: (roleName: string, userName: string) =>
        `Remove ${roleName} from ${userName}?`,
      assignmentRemovalConfirm: 'Remove assignment',
      assignmentRemovalPending: 'Removing assignment…',
      assignmentSubmit: 'Assign role',
      assignmentPending: 'Assigning role…',
      noAssignmentsTitle: 'No scoped roles assigned',
      noAssignmentsDescription:
        'This user has no role assignments yet. Use the form above to grant one at the right scope.',
      assignmentCreated: (roleName: string) => `${roleName} was assigned.`,
      assignmentUpdated: 'Role assignment was updated.',
      assignmentRemoved: 'Role assignment was removed.',
      assignmentSavePending: 'Saving…',
      directScopeAccessTitle: 'Direct scope access',
      directScopeAccessDescription:
        'Review direct access rules here. Use the dedicated access flow to change them.',
      noDirectScopeAccessTitle: 'No direct scope access rules',
      noDirectScopeAccessDescription: 'This user has no direct access rules.',
    },
    roleEditor: {
      loading: 'Loading role…',
      unavailableTitle: 'Role unavailable',
      loadError: 'Failed to load role detail.',
      createError: 'Failed to create role.',
      updateError: 'Failed to update role.',
      missingTargetError: 'Missing role target.',
      createTitle: 'Create role',
      titleFallback: 'Role',
      backToInventory: 'Back to roles',
      badge: (workspaceLabel: string) => workspaceLabel,
      createDescription:
        'Define role details and the explicit permissions required for this scope.',
      editDescription:
        'Review role details, explicit permissions, and where this role is assigned.',
      initialAdminLockTitle: 'Initial Admin locked',
      initialAdminLockDescription:
        'Initial Admin is the built-in recovery role. Its name and permissions are locked to prevent access loss.',
      summaryExplicitPermissionsLabel: 'Explicit Permissions',
      summaryExplicitPermissionsHint:
        'Unset actions inherit the broader catalog defaults or remain unavailable.',
      summaryAssignedUsersLabel: 'Assigned Users',
      summaryAssignedUsersHint:
        'Live assignments remain visible while metadata and permissions are edited.',
      summaryBoundScopesLabel: 'Bound Scopes',
      summaryBoundScopesHint: 'Shows where this role is currently assigned.',
      scopeBindingsTitle: 'Assignment-derived scope bindings',
      scopeBindingsDescription:
        'This role is currently assigned at the tenant, subsidiary, or talent level.',
      scopeBindingsEmpty:
        'No current assignments bind this role to a tenant, subsidiary, or talent scope.',
      assignedUsersTitle: 'Assigned users',
      assignedUsersDescription:
        'Review which users currently hold this role and where the assignment is scoped.',
      assignedUsersEmpty: 'No users are currently assigned to this role.',
      fields: {
        roleCode: 'Role code',
        nameBase: 'Base role name',
        description: 'Description',
      },
      createHint:
        'Role code becomes the stable identifier after creation. Leave actions unset to avoid granting behavior you do not need.',
      editHint:
        'Role code stays immutable after creation. Roles are kept for audit history; remove assignments or change Grant, Deny, and Unset states to change effective access.',
      permissionMatrixTitle: 'Permission matrix',
      permissionMatrixDescription: 'Explicit effects can be left unset, granted, or denied.',
      notAvailable: 'N/A',
      submitCreate: 'Create role',
      submitSave: 'Save role',
      pendingCreate: 'Creating role…',
      pendingSave: 'Saving role…',
      createSuccess: (name: string) => `${name} was created.`,
      updateSuccess: (name: string) => `${name} was updated.`,
      translationManagement: {
        trigger: 'Translation management',
        title: 'Role name translations',
        baseValueLabel: 'Base role name (English)',
        save: 'Save',
        cancel: 'Cancel',
        closeButtonAriaLabel: 'Close role name translations drawer',
        empty: 'No additional translations configured yet.',
        summary: (count: number) =>
          `${count} additional locale ${count === 1 ? 'value' : 'values'} configured.`,
        languageLoadError:
          'Language options are temporarily unavailable. Load the System Dictionary languages and try again.',
      },
      validation: {
        code: 'Role code must be 3-32 characters using only A-Z, 0-9, and _.',
        nameBase: 'Base role name is required.',
      },
    },
  },
  zh_HANS: {
    shared: {
      cancel: '取消',
      confirm: '确认',
      confirmAction: '确认操作',
      never: '从未',
      unavailable: '不可用',
      seen: '已登录',
      tenantWorkspace: '租户',
      acWorkspace: '平台工作区',
      tenantAccessLabel: '租户访问',
      acAccessLabel: '平台访问',
      tenantSessionLabel: '租户上下文',
      acSessionLabel: '平台上下文',
      tenantDirectoryLabel: '租户用户目录',
      acDirectoryLabel: 'AC 身份目录',
      tenantRoot: '租户根级',
      unnamedScope: '未命名范围',
      tenantWideAssignment: '租户级分配',
      tenantWideBinding: '租户级绑定',
      tenantWideVisibility: '租户级可见性',
      grantedLabel: '授权时间',
      expiresLabel: '到期时间',
      includesSubunits: '包含下级',
      inherit: '继承',
      userActive: '用户启用',
      userInactive: '用户停用',
      protectedRole: '内置锁定',
      customRole: '自定义角色',
      save: '保存',
      remove: '移除',
      noCompatibleRoles: '没有可分配角色',
      assignLinks: (count: number) => `${count} 条生效链接`,
      scopeCount: (count: number) => `${count} 个范围`,
      userCount: (count: number) => `${count} 位用户`,
      assignmentCount: (count: number) => `${count} 条分配`,
      inheritedAssignments: (count: number) => `当前有 ${count} 条继承分配在传播权限。`,
    },
    management: {
      pageUnavailableTitle: '用户管理不可用',
      pageUnavailableDescription: (_workspaceAccessLabel: string) =>
        '当前范围无法加载用户、角色或委派管理数据。',
      badge: (workspaceLabel: string) => workspaceLabel,
      title: '身份、角色与委派管理',
      description: '在同一处管理用户、角色与委派；创建或编辑时进入独立页面。',
      summaryVisibleUsersLabel: '可见用户',
      summaryVisibleUsersHint: (_workspaceSessionLabel: string) =>
        '按当前会话上下文和筛选条件得到的用户结果。',
      summaryRoleTemplatesLabel: '角色模板',
      summaryRoleTemplatesHint: '这里显示当前范围允许使用的角色权限模板。',
      summaryDelegationsLabel: '委派记录',
      summaryDelegationsHint: '委派记录继续以分目录或艺人为目标范围进行管理。',
      tabs: {
        users: '用户',
        roles: '角色',
        delegation: '委派',
      },
      users: {
        title: '系统用户',
        description: '列表页只负责搜索、状态筛选和账户操作；创建与编辑用户在独立页面进行。',
        newUser: '新建用户',
        searchLabel: '搜索',
        searchPlaceholder: '搜索用户名、邮箱或显示名',
        statusLabel: '状态',
        statusAll: '全部用户',
        statusActive: '仅激活',
        statusInactive: '仅停用',
        unavailableTitle: '系统用户不可用',
        emptyTitle: '没有符合条件的系统用户',
        emptyDescription: (workspaceDirectoryLabel: string) =>
          `请调整搜索或状态筛选，查看 ${workspaceDirectoryLabel} 中的其他用户。`,
        columns: ['用户', '状态', '安全', '最近登录', '创建时间', '操作'],
        active: '激活',
        inactive: '停用',
        resetRequired: '需重置密码',
        totpEnabled: '已启用 TOTP',
        noTotp: '未启用 TOTP',
        edit: '编辑',
        requireTotp: '要求启用 TOTP',
        requireTotpTitle: (name: string) => `为 ${name} 强制启用 TOTP？`,
        requireTotpDescription: '该用户下次成功登录后，必须先完成 TOTP 绑定。',
        requireTotpConfirm: '要求启用 TOTP',
        requireTotpPending: '正在保存 TOTP 要求…',
        requireTotpSuccess: (name: string) => `${name} 下次登录时必须配置 TOTP。`,
        requireTotpError: '设置 TOTP 要求失败。',
        deactivate: '停用',
        deactivateTitle: (name: string) => `停用 ${name}？`,
        deactivateDescription: (_workspaceAccessLabel: string) =>
          '停用后，该用户将失去当前访问权限，直到重新激活。',
        deactivateConfirm: '停用用户',
        deactivatePending: '正在停用用户…',
        deactivateSuccess: (name: string) => `${name} 已停用。`,
        deactivateError: '停用系统用户失败。',
        reactivate: '重新激活',
        reactivateTitle: (name: string) => `重新激活 ${name}？`,
        reactivateDescription: (_workspaceAccessLabel: string) =>
          '重新激活后，该用户可恢复访问权限，不会重置其他账户资料。',
        reactivateConfirm: '重新激活用户',
        reactivatePending: '正在重新激活用户…',
        reactivateSuccess: (name: string) => `${name} 已重新激活。`,
        reactivateError: '重新激活系统用户失败。',
      },
      roles: {
        title: '系统角色',
        description: '在列表中审查角色覆盖面，需要深度编辑时进入独立角色页面。',
        newRole: '新建角色',
        unavailableTitle: '系统角色不可用',
        emptyTitle: '没有可用角色',
        emptyDescription: (_workspaceAccessLabel: string) =>
          '这里显示当前范围允许使用的角色权限模板。',
        columns: ['角色', '覆盖面', '用户数', '模板', '更新时间', '操作'],
        permissions: (count: number) => `${count} 条权限`,
        assignedUsers: (count: number) => `${count} 位分配用户`,
        protected: '内置锁定',
        custom: '自定义角色',
        edit: '编辑',
      },
      delegation: {
        title: '委派管理',
        description: '按范围将分目录或艺人管理权限委派给指定用户或角色，并在列表中追踪现有授权。',
        grantTitle: '授予委派管理',
        grantDescription: '选择一个可见范围，并将该范围委派给用户或角色。',
        grantButton: '授予委派',
        grantPending: '正在授予委派…',
        loadingTitle: '正在加载可委派范围',
        loadingDescription: '组织树加载完成后，表单即可直接提供可委派范围。',
        noScopesTitle: '没有可委派的范围',
        noScopesDescription: '当前没有可用于委派管理的分目录或艺人范围。',
        scopeTypeLabel: '范围类型',
        scopeTypeSubsidiary: '分目录',
        scopeTypeTalent: '艺人',
        scopeTargetLabel: '范围目标',
        delegateTypeLabel: '委派对象类型',
        delegateTypeUser: '用户',
        delegateTypeRole: '角色',
        delegateLabel: '委派对象',
        sourceNote: '委派选项来自当前可见组织树以及已加载的用户、角色列表。',
        selectScopeError: '请先选择一个范围。',
        selectDelegateError: '请先选择一个委派对象。',
        createError: '创建委派管理失败。',
        createSuccess: (delegateName: string, scopeName: string) =>
          `${delegateName} 已获得 ${scopeName} 的委派管理权限。`,
        unavailableTitle: '委派管理不可用',
        emptyTitle: '尚未配置委派管理',
        emptyDescription: (isAcWorkspace: boolean) =>
          `当前${isAcWorkspace ? ' AC 租户' : '租户'}还没有分目录或艺人范围的委派管理授权。`,
        columns: ['范围', '委派对象', '授权人', '授权时间', '操作'],
        systemGrantedBy: '系统',
        remove: '移除',
        removeTitle: (name: string) => `移除 ${name} 的委派管理？`,
        removeDescription: '这会从所选范围中移除委派管理授权，并立即从列表中删除该记录。',
        removeConfirm: '移除委派',
        removePending: '正在移除委派…',
        removeSuccess: (name: string) => `${name} 的委派管理已移除。`,
        removeError: '移除委派管理失败。',
      },
    },
    editor: {
      loading: '正在加载用户编辑页…',
      unavailableTitle: '用户编辑页不可用',
      loadError: '加载系统用户详情失败。',
      supportDataError: '加载角色和范围选项失败。',
      missingTargetError: '缺少系统用户 ID。',
      createError: '创建系统用户失败。',
      updateError: '更新系统用户失败。',
      assignmentSelectRoleError: '请先选择要分配的角色。',
      assignmentCreateError: '分配角色失败。',
      assignmentUpdateError: '更新角色分配失败。',
      assignmentRemoveError: '移除角色分配失败。',
      assignmentPermissionTitle: '当前范围不可分配角色',
      assignmentPermissionDescription: '当前会话无权在所选范围分配角色，账户资料编辑仍可继续。',
      validation: {
        username: '用户名至少需要 3 个字符。',
        email: '必须填写有效邮箱。',
        initialPassword: '初始密码至少需要 12 个字符。',
      },
      backToInventory: '返回用户',
      badge: (workspaceLabel: string) => workspaceLabel,
      createTitle: '新建系统用户',
      createDescription: '在独立页面中创建用户，让身份信息与范围分配保持聚焦。',
      editDescription: '用户在独立页面中编辑，让身份信息、范围角色分配和安全操作保持聚焦。',
      accountProfileTitle: '账户资料',
      fields: {
        username: '用户名',
        email: '邮箱',
        initialPassword: '初始密码',
        forceReset: '首次登录时强制重置密码',
        displayName: '显示名',
        phone: '手机号',
        preferredLanguage: '首选语言',
      },
      forceResetDescription: '让引导阶段密码仅短期有效，首次认证后必须立即重置。',
      immutableIdentityDescription:
        '用户名和邮箱在此处不可修改。密码轮换保留给个人资料和安全流程，不再藏在拥挤的列表页里。',
      submitCreate: '创建用户',
      submitSave: '保存资料',
      pendingCreate: '正在创建用户…',
      pendingSave: '正在保存资料…',
      summaryRoleAssignmentsLabel: '角色分配',
      summaryRoleAssignmentsHint: '所选用户当前的角色分配数量。',
      summaryScopeAccessLabel: '范围访问',
      summaryScopeAccessHint: '直接挂在此用户上的可见性规则。',
      summaryLastLoginLabel: '最近登录',
      lastLoginSeen: '已登录',
      lastLoginNeverHint: '该用户尚未登录过。',
      updateSuccess: (name: string) => `${name} 已更新。`,
      scopedAssignmentsTitle: '范围角色分配',
      scopedAssignmentsDescription:
        '可在此按租户、分目录或艺人范围直接分配角色，列表页仅保留浏览。',
      manageRoleTemplates: '管理角色模板',
      scopeField: '范围',
      roleField: '角色',
      expiresAtField: '到期时间',
      assignmentInheritLabel: '在支持时继承到下级范围',
      assignmentScopeWarning: '更改范围、继承或到期时间可能扩大或收缩有效访问权限，保存前请审查影响。',
      assignmentInitialAdminWarning:
        'Initial Admin 拥有该租户内全部权限。保存前必须保留至少一个有效的租户级 Initial Admin 分配。',
      assignmentRemovalWarning:
        '移除此分配可能改变用户有效访问权限。保存前请审查范围、继承、到期时间和快照刷新结果。',
      assignmentSnapshotRefreshExpectation: '保存后会检查权限版本并刷新权限快照。',
      assignmentImpactSummary: (
        roleName: string,
        userName: string,
        scopeName: string,
        inheritState: string,
        expiresAt: string
      ) =>
        `角色：${roleName}。用户：${userName}。范围：${scopeName}。继承：${inheritState}。到期：${expiresAt}。`,
      assignmentCreateInitialAdminTitle: '分配 Initial Admin？',
      assignmentCreateInitialAdminConfirm: '分配 Initial Admin',
      assignmentUpdateTitle: (roleName: string) => `保存 ${roleName} 分配变更？`,
      assignmentUpdateConfirm: '保存分配',
      assignmentUpdatePending: '正在保存分配…',
      assignmentRemovalTitle: (roleName: string, userName: string) =>
        `从 ${userName} 移除 ${roleName}？`,
      assignmentRemovalConfirm: '移除分配',
      assignmentRemovalPending: '正在移除分配…',
      assignmentSubmit: '分配角色',
      assignmentPending: '正在分配角色…',
      noAssignmentsTitle: '尚未分配范围角色',
      noAssignmentsDescription: '该用户当前还没有角色分配，请使用上方表单授予正确范围的角色。',
      assignmentCreated: (roleName: string) => `${roleName} 已分配。`,
      assignmentUpdated: '角色分配已更新。',
      assignmentRemoved: '角色分配已移除。',
      assignmentSavePending: '正在保存…',
      directScopeAccessTitle: '直接范围访问',
      directScopeAccessDescription: '这里展示直接范围访问记录；如需修改，请使用专门的访问入口。',
      noDirectScopeAccessTitle: '没有直接范围访问规则',
      noDirectScopeAccessDescription: '该用户当前没有直接访问规则。',
    },
    roleEditor: {
      loading: '正在加载系统角色…',
      unavailableTitle: '系统角色不可用',
      loadError: '加载系统角色详情失败。',
      createError: '创建系统角色失败。',
      updateError: '更新系统角色失败。',
      missingTargetError: '缺少系统角色目标。',
      createTitle: '新建系统角色',
      titleFallback: '系统角色',
      backToInventory: '返回角色',
      badge: (workspaceLabel: string) => workspaceLabel,
      createDescription: '定义当前范围所需的角色信息与显式权限。',
      editDescription: '无需回到列表页即可审查角色信息、显式权限和当前范围覆盖。',
      initialAdminLockTitle: 'Initial Admin 已锁定',
      initialAdminLockDescription:
        'Initial Admin 是内置救援角色。其名称和权限已锁定，以避免访问丢失。',
      summaryExplicitPermissionsLabel: '显式权限',
      summaryExplicitPermissionsHint: '未设置的动作将继承更宽的目录默认值，或保持不可用。',
      summaryAssignedUsersLabel: '已分配用户',
      summaryAssignedUsersHint: '编辑元数据和权限时，现有分配仍在此可见。',
      summaryBoundScopesLabel: '绑定范围',
      summaryBoundScopesHint: '当前范围覆盖来自现有角色分配。',
      scopeBindingsTitle: '分配派生的范围绑定',
      scopeBindingsDescription: '当前绑定来自租户、分目录和艺人范围下的激活用户角色分配。',
      scopeBindingsEmpty: '当前没有任何分配将该角色绑定到租户、分目录或艺人范围。',
      assignedUsersTitle: '已分配用户',
      assignedUsersDescription: '查看当前哪些用户持有该角色，以及分配落在哪个范围。',
      assignedUsersEmpty: '当前没有用户持有该角色。',
      fields: {
        roleCode: '角色编码',
        nameBase: '基准角色名',
        description: '描述',
      },
      createHint: '角色编码在创建后会成为稳定标识。将动作保持未设置，可避免授予不需要的行为。',
      editHint: '角色编码在创建后不可修改。角色会保留用于审计；请移除分配或调整允许、拒绝、未设置状态来改变实际访问。',
      permissionMatrixTitle: '权限矩阵',
      permissionMatrixDescription: '显式效果可以设置为未设置、允许或拒绝。',
      notAvailable: '不适用',
      submitCreate: '创建角色',
      submitSave: '保存角色',
      pendingCreate: '正在创建角色…',
      pendingSave: '正在保存角色…',
      createSuccess: (name: string) => `${name} 已创建。`,
      updateSuccess: (name: string) => `${name} 已更新。`,
      translationManagement: {
        trigger: '翻译管理',
        title: '角色名称翻译',
        baseValueLabel: '英文主名称',
        save: '保存',
        cancel: '取消',
        closeButtonAriaLabel: '关闭角色名称翻译抽屉',
        empty: '当前还没有额外语言翻译。',
        summary: (count: number) => `已配置 ${count} 个额外语言值。`,
        languageLoadError: '语言选项暂时不可用，请先加载系统词典中的 Language 条目后重试。',
      },
      validation: {
        code: '角色编码需为 3-32 位，仅允许 A-Z、0-9 和下划线。',
        nameBase: '必须填写基准角色名。',
      },
    },
  },
  zh_HANT: {
    shared: {
      cancel: '取消',
      confirm: '确认',
      confirmAction: '确认操作',
      never: '从未',
      unavailable: '不可用',
      seen: '已登录',
      tenantWorkspace: '租户',
      acWorkspace: '平台工作区',
      tenantAccessLabel: '租户访问',
      acAccessLabel: '平台访问',
      tenantSessionLabel: '租户上下文',
      acSessionLabel: '平台上下文',
      tenantDirectoryLabel: '租户用户目录',
      acDirectoryLabel: 'AC 身份目录',
      tenantRoot: '租户根级',
      unnamedScope: '未命名范围',
      tenantWideAssignment: '租户级分配',
      tenantWideBinding: '租户级绑定',
      tenantWideVisibility: '租户级可见性',
      grantedLabel: '授权时间',
      expiresLabel: '到期时间',
      includesSubunits: '包含下级',
      inherit: '继承',
      userActive: '用户启用',
      userInactive: '用户停用',
      protectedRole: '内置锁定',
      customRole: '自定义角色',
      save: '保存',
      remove: '移除',
      noCompatibleRoles: '没有可分配角色',
      assignLinks: (count: number) => `${count} 条生效链接`,
      scopeCount: (count: number) => `${count} 个范围`,
      userCount: (count: number) => `${count} 位用户`,
      assignmentCount: (count: number) => `${count} 条分配`,
      inheritedAssignments: (count: number) => `当前有 ${count} 条继承分配在传播权限。`,
    },
    management: {
      pageUnavailableTitle: '用户管理不可用',
      pageUnavailableDescription: (_workspaceAccessLabel: string) =>
        '当前范围无法加载用户、角色或委派管理数据。',
      badge: (workspaceLabel: string) => workspaceLabel,
      title: '身份、角色与委派管理',
      description: '在同一处管理用户、角色与委派；创建或编辑时进入独立页面。',
      summaryVisibleUsersLabel: '可见用户',
      summaryVisibleUsersHint: (_workspaceSessionLabel: string) =>
        '按当前会话上下文和筛选条件得到的用户结果。',
      summaryRoleTemplatesLabel: '角色模板',
      summaryRoleTemplatesHint: '这里显示当前范围允许使用的角色权限模板。',
      summaryDelegationsLabel: '委派记录',
      summaryDelegationsHint: '委派记录继续以分目录或艺人为目标范围进行管理。',
      tabs: {
        users: '用户',
        roles: '角色',
        delegation: '委派',
      },
      users: {
        title: '系统用户',
        description: '列表页只负责搜索、状态筛选和账户操作；创建与编辑用户在独立页面进行。',
        newUser: '新建用户',
        searchLabel: '搜索',
        searchPlaceholder: '搜索用户名、邮箱或显示名',
        statusLabel: '状态',
        statusAll: '全部用户',
        statusActive: '仅激活',
        statusInactive: '仅停用',
        unavailableTitle: '系统用户不可用',
        emptyTitle: '没有符合条件的系统用户',
        emptyDescription: (workspaceDirectoryLabel: string) =>
          `请调整搜索或状态筛选，查看 ${workspaceDirectoryLabel} 中的其他用户。`,
        columns: ['用户', '状态', '安全', '最近登录', '创建时间', '操作'],
        active: '激活',
        inactive: '停用',
        resetRequired: '需重置密码',
        totpEnabled: '已启用 TOTP',
        noTotp: '未启用 TOTP',
        edit: '编辑',
        requireTotp: '要求启用 TOTP',
        requireTotpTitle: (name: string) => `为 ${name} 强制启用 TOTP？`,
        requireTotpDescription: '该用户下次成功登录后，必须先完成 TOTP 绑定。',
        requireTotpConfirm: '要求启用 TOTP',
        requireTotpPending: '正在保存 TOTP 要求…',
        requireTotpSuccess: (name: string) => `${name} 下次登录时必须配置 TOTP。`,
        requireTotpError: '设置 TOTP 要求失败。',
        deactivate: '停用',
        deactivateTitle: (name: string) => `停用 ${name}？`,
        deactivateDescription: (_workspaceAccessLabel: string) =>
          '停用后，该用户将失去当前访问权限，直到重新激活。',
        deactivateConfirm: '停用用户',
        deactivatePending: '正在停用用户…',
        deactivateSuccess: (name: string) => `${name} 已停用。`,
        deactivateError: '停用系统用户失败。',
        reactivate: '重新激活',
        reactivateTitle: (name: string) => `重新激活 ${name}？`,
        reactivateDescription: (_workspaceAccessLabel: string) =>
          '重新激活后，该用户可恢复访问权限，不会重置其他账户资料。',
        reactivateConfirm: '重新激活用户',
        reactivatePending: '正在重新激活用户…',
        reactivateSuccess: (name: string) => `${name} 已重新激活。`,
        reactivateError: '重新激活系统用户失败。',
      },
      roles: {
        title: '系统角色',
        description: '在列表中审查角色覆盖面，需要深度编辑时进入独立角色页面。',
        newRole: '新建角色',
        unavailableTitle: '系统角色不可用',
        emptyTitle: '没有可用角色',
        emptyDescription: (_workspaceAccessLabel: string) =>
          '这里显示当前范围允许使用的角色权限模板。',
        columns: ['角色', '覆盖面', '用户数', '模板', '更新时间', '操作'],
        permissions: (count: number) => `${count} 条权限`,
        assignedUsers: (count: number) => `${count} 位分配用户`,
        protected: '内置锁定',
        custom: '自定义角色',
        edit: '编辑',
      },
      delegation: {
        title: '委派管理',
        description: '按范围将分目录或艺人管理权限委派给指定用户或角色，并在列表中追踪现有授权。',
        grantTitle: '授予委派管理',
        grantDescription: '选择一个可见范围，并将该范围委派给用户或角色。',
        grantButton: '授予委派',
        grantPending: '正在授予委派…',
        loadingTitle: '正在加载可委派范围',
        loadingDescription: '组织树加载完成后，表单即可直接提供可委派范围。',
        noScopesTitle: '没有可委派的范围',
        noScopesDescription: '当前没有可用于委派管理的分目录或艺人范围。',
        scopeTypeLabel: '范围类型',
        scopeTypeSubsidiary: '分目录',
        scopeTypeTalent: '艺人',
        scopeTargetLabel: '范围目标',
        delegateTypeLabel: '委派对象类型',
        delegateTypeUser: '用户',
        delegateTypeRole: '角色',
        delegateLabel: '委派对象',
        sourceNote: '委派选项来自当前可见组织树以及已加载的用户、角色列表。',
        selectScopeError: '请先选择一个范围。',
        selectDelegateError: '请先选择一个委派对象。',
        createError: '创建委派管理失败。',
        createSuccess: (delegateName: string, scopeName: string) =>
          `${delegateName} 已获得 ${scopeName} 的委派管理权限。`,
        unavailableTitle: '委派管理不可用',
        emptyTitle: '尚未配置委派管理',
        emptyDescription: (isAcWorkspace: boolean) =>
          `当前${isAcWorkspace ? ' AC 租户' : '租户'}还没有分目录或艺人范围的委派管理授权。`,
        columns: ['范围', '委派对象', '授权人', '授权时间', '操作'],
        systemGrantedBy: '系统',
        remove: '移除',
        removeTitle: (name: string) => `移除 ${name} 的委派管理？`,
        removeDescription: '这会从所选范围中移除委派管理授权，并立即从列表中删除该记录。',
        removeConfirm: '移除委派',
        removePending: '正在移除委派…',
        removeSuccess: (name: string) => `${name} 的委派管理已移除。`,
        removeError: '移除委派管理失败。',
      },
    },
    editor: {
      loading: '正在加载用户编辑页…',
      unavailableTitle: '用户编辑页不可用',
      loadError: '加载系统用户详情失败。',
      supportDataError: '加载角色和范围选项失败。',
      missingTargetError: '缺少系统用户 ID。',
      createError: '创建系统用户失败。',
      updateError: '更新系统用户失败。',
      assignmentSelectRoleError: '请先选择要分配的角色。',
      assignmentCreateError: '分配角色失败。',
      assignmentUpdateError: '更新角色分配失败。',
      assignmentRemoveError: '移除角色分配失败。',
      assignmentPermissionTitle: '当前范围不可分配角色',
      assignmentPermissionDescription: '当前会话无权在所选范围分配角色，账户资料编辑仍可继续。',
      validation: {
        username: '用户名至少需要 3 个字符。',
        email: '必须填写有效邮箱。',
        initialPassword: '初始密码至少需要 12 个字符。',
      },
      backToInventory: '返回用户',
      badge: (workspaceLabel: string) => workspaceLabel,
      createTitle: '新建系统用户',
      createDescription: '在独立页面中创建用户，让身份信息与范围分配保持聚焦。',
      editDescription: '用户在独立页面中编辑，让身份信息、范围角色分配和安全操作保持聚焦。',
      accountProfileTitle: '账户资料',
      fields: {
        username: '用户名',
        email: '邮箱',
        initialPassword: '初始密码',
        forceReset: '首次登录时强制重置密码',
        displayName: '显示名',
        phone: '手机号',
        preferredLanguage: '首选语言',
      },
      forceResetDescription: '让引导阶段密码仅短期有效，首次认证后必须立即重置。',
      immutableIdentityDescription:
        '用户名和邮箱在此处不可修改。密码轮换保留给个人资料和安全流程，不再藏在拥挤的列表页里。',
      submitCreate: '创建用户',
      submitSave: '保存资料',
      pendingCreate: '正在创建用户…',
      pendingSave: '正在保存资料…',
      summaryRoleAssignmentsLabel: '角色分配',
      summaryRoleAssignmentsHint: '所选用户当前的角色分配数量。',
      summaryScopeAccessLabel: '范围访问',
      summaryScopeAccessHint: '直接挂在此用户上的可见性规则。',
      summaryLastLoginLabel: '最近登录',
      lastLoginSeen: '已登录',
      lastLoginNeverHint: '该用户尚未登录过。',
      updateSuccess: (name: string) => `${name} 已更新。`,
      scopedAssignmentsTitle: '范围角色分配',
      scopedAssignmentsDescription:
        '可在此按租户、分目录或艺人范围直接分配角色，列表页仅保留浏览。',
      manageRoleTemplates: '管理角色模板',
      scopeField: '范围',
      roleField: '角色',
      expiresAtField: '到期时间',
      assignmentInheritLabel: '在支持时继承到下级范围',
      assignmentScopeWarning: '更改范围、继承或到期时间可能扩大或收缩有效访问权限，保存前请审查影响。',
      assignmentInitialAdminWarning:
        'Initial Admin 拥有该租户内全部权限。保存前必须保留至少一个有效的租户级 Initial Admin 分配。',
      assignmentRemovalWarning:
        '移除此分配可能改变用户有效访问权限。保存前请审查范围、继承、到期时间和快照刷新结果。',
      assignmentSnapshotRefreshExpectation: '保存后会检查权限版本并刷新权限快照。',
      assignmentImpactSummary: (
        roleName: string,
        userName: string,
        scopeName: string,
        inheritState: string,
        expiresAt: string
      ) =>
        `角色：${roleName}。用户：${userName}。范围：${scopeName}。继承：${inheritState}。到期：${expiresAt}。`,
      assignmentCreateInitialAdminTitle: '分配 Initial Admin？',
      assignmentCreateInitialAdminConfirm: '分配 Initial Admin',
      assignmentUpdateTitle: (roleName: string) => `保存 ${roleName} 分配变更？`,
      assignmentUpdateConfirm: '保存分配',
      assignmentUpdatePending: '正在保存分配…',
      assignmentRemovalTitle: (roleName: string, userName: string) =>
        `从 ${userName} 移除 ${roleName}？`,
      assignmentRemovalConfirm: '移除分配',
      assignmentRemovalPending: '正在移除分配…',
      assignmentSubmit: '分配角色',
      assignmentPending: '正在分配角色…',
      noAssignmentsTitle: '尚未分配范围角色',
      noAssignmentsDescription: '该用户当前还没有角色分配，请使用上方表单授予正确范围的角色。',
      assignmentCreated: (roleName: string) => `${roleName} 已分配。`,
      assignmentUpdated: '角色分配已更新。',
      assignmentRemoved: '角色分配已移除。',
      assignmentSavePending: '正在保存…',
      directScopeAccessTitle: '直接范围访问',
      directScopeAccessDescription: '这里展示直接范围访问记录；如需修改，请使用专门的访问入口。',
      noDirectScopeAccessTitle: '没有直接范围访问规则',
      noDirectScopeAccessDescription: '该用户当前没有直接访问规则。',
    },
    roleEditor: {
      loading: '正在加载系统角色…',
      unavailableTitle: '系统角色不可用',
      loadError: '加载系统角色详情失败。',
      createError: '创建系统角色失败。',
      updateError: '更新系统角色失败。',
      missingTargetError: '缺少系统角色目标。',
      createTitle: '新建系统角色',
      titleFallback: '系统角色',
      backToInventory: '返回角色',
      badge: (workspaceLabel: string) => workspaceLabel,
      createDescription: '定义当前范围所需的角色信息与显式权限。',
      editDescription: '无需回到列表页即可审查角色信息、显式权限和当前范围覆盖。',
      initialAdminLockTitle: 'Initial Admin 已鎖定',
      initialAdminLockDescription:
        'Initial Admin 是內建救援角色。其名稱和權限已鎖定，以避免存取遺失。',
      summaryExplicitPermissionsLabel: '显式权限',
      summaryExplicitPermissionsHint: '未设置的动作将继承更宽的目录默认值，或保持不可用。',
      summaryAssignedUsersLabel: '已分配用户',
      summaryAssignedUsersHint: '编辑元数据和权限时，现有分配仍在此可见。',
      summaryBoundScopesLabel: '绑定范围',
      summaryBoundScopesHint: '当前范围覆盖来自现有角色分配。',
      scopeBindingsTitle: '分配派生的范围绑定',
      scopeBindingsDescription: '当前绑定来自租户、分目录和艺人范围下的激活用户角色分配。',
      scopeBindingsEmpty: '当前没有任何分配将该角色绑定到租户、分目录或艺人范围。',
      assignedUsersTitle: '已分配用户',
      assignedUsersDescription: '查看当前哪些用户持有该角色，以及分配落在哪个范围。',
      assignedUsersEmpty: '当前没有用户持有该角色。',
      fields: {
        roleCode: '角色编码',
        nameBase: '基准角色名',
        description: '描述',
      },
      createHint: '角色编码在创建后会成为稳定标识。将动作保持未设置，可避免授予不需要的行为。',
      editHint: '角色编码在创建后不可修改。角色会保留用于审计；请移除分配或调整允许、拒绝、未设置状态来改变实际访问。',
      permissionMatrixTitle: '权限矩阵',
      permissionMatrixDescription: '显式效果可以设置为未设置、允许或拒绝。',
      notAvailable: '不适用',
      submitCreate: '创建角色',
      submitSave: '保存角色',
      pendingCreate: '正在创建角色…',
      pendingSave: '正在保存角色…',
      createSuccess: (name: string) => `${name} 已创建。`,
      updateSuccess: (name: string) => `${name} 已更新。`,
      translationManagement: {
        trigger: '翻译管理',
        title: '角色名称翻译',
        baseValueLabel: '英文主名称',
        save: '保存',
        cancel: '取消',
        closeButtonAriaLabel: '关闭角色名称翻译抽屉',
        empty: '当前还没有额外语言翻译。',
        summary: (count: number) => `已配置 ${count} 个额外语言值。`,
        languageLoadError: '语言选项暂时不可用，请先加载系统词典中的 Language 条目后重试。',
      },
      validation: {
        code: '角色编码需为 3-32 位，仅允许 A-Z、0-9 和下划线。',
        nameBase: '必须填写基准角色名。',
      },
    },
  },
  ja: {
    shared: {
      cancel: 'キャンセル',
      confirm: '確認',
      confirmAction: '操作の確認',
      never: '未実施',
      unavailable: '利用不可',
      seen: '確認済み',
      tenantWorkspace: 'テナント',
      acWorkspace: 'プラットフォームワークスペース',
      tenantAccessLabel: 'テナントアクセス',
      acAccessLabel: 'プラットフォームアクセス',
      tenantSessionLabel: 'テナントコンテキスト',
      acSessionLabel: 'プラットフォームコンテキスト',
      tenantDirectoryLabel: 'テナントユーザーディレクトリ',
      acDirectoryLabel: 'AC ID ディレクトリ',
      tenantRoot: 'テナントルート',
      unnamedScope: '名称未設定の範囲',
      tenantWideAssignment: 'テナント全体の割当',
      tenantWideBinding: 'テナント全体の紐付け',
      tenantWideVisibility: 'テナント全体の可視範囲',
      grantedLabel: '付与',
      expiresLabel: '期限',
      includesSubunits: '下位範囲を含む',
      inherit: '継承',
      userActive: 'ユーザー有効',
      userInactive: 'ユーザー無効',
      protectedRole: '組み込みロック',
      customRole: 'カスタムロール',
      save: '保存',
      remove: '削除',
      noCompatibleRoles: '利用可能なロールがありません',
      assignLinks: (count: number) => `${count} 件の有効リンク`,
      scopeCount: (count: number) => `${count} 件の範囲`,
      userCount: (count: number) => `${count} 人のユーザー`,
      assignmentCount: (count: number) => `${count} 件の割当`,
      inheritedAssignments: (count: number) => `現在 ${count} 件の継承割当が権限を伝播しています。`,
    },
    management: {
      pageUnavailableTitle: 'ユーザー管理を読み込めません',
      pageUnavailableDescription: (_workspaceAccessLabel: string) =>
        '現在の範囲でユーザー、ロール、委任管理データを読み込めませんでした。',
      badge: (workspaceLabel: string) => workspaceLabel,
      title: 'ID・ロール・委任管理',
      description:
        'ユーザー、ロール定義、委任権限を一つの画面で管理し、一覧ページに重い編集フォームを混在させません。',
      summaryVisibleUsersLabel: '表示中のユーザー',
      summaryVisibleUsersHint: (_workspaceSessionLabel: string) =>
        '現在のセッション条件と検索フィルターに一致したユーザー数です。',
      summaryRoleTemplatesLabel: 'ロールテンプレート',
      summaryRoleTemplatesHint: '現在の範囲で利用できるロールテンプレートのみを表示します。',
      summaryDelegationsLabel: '委任件数',
      summaryDelegationsHint: '委任レコードは配下スコープまたはタレント範囲を対象に管理されます。',
      tabs: {
        users: 'ユーザー',
        roles: 'ロール',
        delegation: '委任',
      },
      users: {
        title: 'システムユーザー',
        description: '一覧は検索、状態、アカウント操作に集中し、作成と編集は専用ページで行います。',
        newUser: 'ユーザー作成',
        searchLabel: '検索',
        searchPlaceholder: 'ユーザー名、メール、表示名で検索',
        statusLabel: '状態',
        statusAll: 'すべてのユーザー',
        statusActive: '有効のみ',
        statusInactive: '無効のみ',
        unavailableTitle: 'システムユーザーを読み込めません',
        emptyTitle: '条件に一致するユーザーがありません',
        emptyDescription: (workspaceDirectoryLabel: string) =>
          `${workspaceDirectoryLabel} の別のユーザーを確認するには検索または状態フィルターを調整してください。`,
        columns: ['ユーザー', '状態', 'セキュリティ', '最終ログイン', '作成日時', '操作'],
        active: '有効',
        inactive: '無効',
        resetRequired: 'パスワード再設定',
        totpEnabled: 'TOTP 有効',
        noTotp: 'TOTP 未設定',
        edit: '編集',
        requireTotp: 'TOTP を必須化',
        requireTotpTitle: (name: string) => `${name} に TOTP を必須化しますか？`,
        requireTotpDescription:
          '次回ログイン時、このユーザーは TOTP 登録を完了する必要があります。',
        requireTotpConfirm: 'TOTP を必須化',
        requireTotpPending: 'TOTP 要件を保存中…',
        requireTotpSuccess: (name: string) => `${name} は次回ログイン時に TOTP 設定が必要です。`,
        requireTotpError: 'TOTP 必須設定の保存に失敗しました。',
        deactivate: '無効化',
        deactivateTitle: (name: string) => `${name} を無効化しますか？`,
        deactivateDescription: (_workspaceAccessLabel: string) =>
          '無効化すると、このユーザーは現在のアクセス権を失います。',
        deactivateConfirm: 'ユーザーを無効化',
        deactivatePending: 'ユーザーを無効化中…',
        deactivateSuccess: (name: string) => `${name} を無効化しました。`,
        deactivateError: 'システムユーザーの無効化に失敗しました。',
        reactivate: '再有効化',
        reactivateTitle: (name: string) => `${name} を再有効化しますか？`,
        reactivateDescription: (_workspaceAccessLabel: string) =>
          '再有効化すると、このユーザーは他のプロフィール情報を変えずにアクセスを回復します。',
        reactivateConfirm: 'ユーザーを再有効化',
        reactivatePending: 'ユーザーを再有効化中…',
        reactivateSuccess: (name: string) => `${name} を再有効化しました。`,
        reactivateError: 'システムユーザーの再有効化に失敗しました。',
      },
      roles: {
        title: 'システムロール',
        description: '一覧でロールの適用範囲を確認し、詳細編集は専用ロールページで行います。',
        newRole: 'ロール作成',
        unavailableTitle: 'システムロールを読み込めません',
        emptyTitle: '利用できるロールがありません',
        emptyDescription: (_workspaceAccessLabel: string) =>
          '現在の範囲で利用できるロール権限テンプレートを表示します。',
        columns: ['ロール', '権限範囲', '割当ユーザー', '種別', '更新日時', '操作'],
        permissions: (count: number) => `${count} 件の権限`,
        assignedUsers: (count: number) => `${count} 人の割当ユーザー`,
        protected: 'Built-in locked',
        custom: 'Custom role',
        edit: '編集',
      },
      delegation: {
        title: '委任管理',
        description:
          '配下スコープまたはタレント範囲に対する管理権限をユーザーまたはロールへ委任し、既存の付与を一覧で管理します。',
        grantTitle: '委任管理を付与',
        grantDescription: '表示可能な範囲を選択し、その範囲をユーザーまたはロールへ委任します。',
        grantButton: '委任を付与',
        grantPending: '委任を付与中…',
        loadingTitle: '委任可能な範囲を読み込み中',
        loadingDescription: '組織ツリーの読み込み後、フォームから委任可能な範囲を選択できます。',
        noScopesTitle: '委任可能な範囲がありません',
        noScopesDescription: '委任管理に利用できる配下スコープまたはタレント範囲がありません。',
        scopeTypeLabel: '範囲タイプ',
        scopeTypeSubsidiary: '配下スコープ',
        scopeTypeTalent: 'タレント',
        scopeTargetLabel: '範囲対象',
        delegateTypeLabel: '委任先タイプ',
        delegateTypeUser: 'ユーザー',
        delegateTypeRole: 'ロール',
        delegateLabel: '委任先',
        sourceNote:
          '委任候補は表示中の組織ツリーと読み込み済みのユーザー・ロール一覧から取得されます。',
        selectScopeError: '委任前に範囲を選択してください。',
        selectDelegateError: '委任前に対象を選択してください。',
        createError: '委任管理の作成に失敗しました。',
        createSuccess: (delegateName: string, scopeName: string) =>
          `${delegateName} に ${scopeName} の委任管理を付与しました。`,
        unavailableTitle: '委任管理を読み込めません',
        emptyTitle: '委任管理は未設定です',
        emptyDescription: (isAcWorkspace: boolean) =>
          `現在の${isAcWorkspace ? ' AC テナント' : 'テナント'}には配下スコープまたはタレント範囲の委任管理がありません。`,
        columns: ['範囲', '委任先', '付与者', '付与日時', '操作'],
        systemGrantedBy: 'システム',
        remove: '解除',
        removeTitle: (name: string) => `${name} の委任管理を解除しますか？`,
        removeDescription: '選択した範囲から委任管理を解除し、一覧から即時に削除します。',
        removeConfirm: '委任を解除',
        removePending: '委任を解除中…',
        removeSuccess: (name: string) => `${name} の委任管理を解除しました。`,
        removeError: '委任管理の解除に失敗しました。',
      },
    },
    editor: {
      loading: 'ユーザー編集画面を読み込み中…',
      unavailableTitle: 'ユーザー編集画面を読み込めません',
      loadError: 'システムユーザー詳細の読み込みに失敗しました。',
      supportDataError: 'ロールと範囲オプションの読み込みに失敗しました。',
      missingTargetError: 'システムユーザー ID がありません。',
      createError: 'システムユーザーの作成に失敗しました。',
      updateError: 'システムユーザーの更新に失敗しました。',
      assignmentSelectRoleError: '割り当てるロールを選択してください。',
      assignmentCreateError: 'ロールの割当てに失敗しました。',
      assignmentUpdateError: 'ロール割当ての更新に失敗しました。',
      assignmentRemoveError: 'ロール割当ての削除に失敗しました。',
      assignmentPermissionTitle: 'この範囲ではロールを割り当てられません',
      assignmentPermissionDescription:
        '現在のセッションでは選択した範囲にロールを割り当てられません。プロフィール編集は引き続き利用できます。',
      validation: {
        username: 'ユーザー名は 3 文字以上必要です。',
        email: '有効なメールアドレスを入力してください。',
        initialPassword: '初期パスワードは 12 文字以上必要です。',
      },
      backToInventory: 'ユーザー一覧に戻る',
      badge: (workspaceLabel: string) => workspaceLabel,
      createTitle: 'システムユーザーを作成',
      createDescription: '専用ページでユーザーを作成し、ID 情報と範囲割当てを整理して扱います。',
      editDescription:
        'ID 情報、範囲ロール割当て、セキュリティ操作を専用ページで整理して扱います。',
      accountProfileTitle: 'アカウント情報',
      fields: {
        username: 'ユーザー名',
        email: 'メールアドレス',
        initialPassword: '初期パスワード',
        forceReset: '初回ログイン時にパスワード変更を必須化',
        displayName: '表示名',
        phone: '電話番号',
        preferredLanguage: '優先言語',
      },
      forceResetDescription: '初期パスワードを短命にし、最初の認証後ただちに再設定させます。',
      immutableIdentityDescription:
        'ここではユーザー名とメールアドレスは変更できません。パスワード更新はプロフィールやセキュリティ導線で行います。',
      submitCreate: 'ユーザーを作成',
      submitSave: 'プロフィールを保存',
      pendingCreate: 'ユーザーを作成中…',
      pendingSave: 'プロフィールを保存中…',
      summaryRoleAssignmentsLabel: 'ロール割当て',
      summaryRoleAssignmentsHint: '選択中ユーザーの現在のロール割当数です。',
      summaryScopeAccessLabel: '範囲アクセス',
      summaryScopeAccessHint: 'このユーザーに直接付与された可視性ルールです。',
      summaryLastLoginLabel: '最終ログイン',
      lastLoginSeen: '確認済み',
      lastLoginNeverHint: 'このユーザーはまだログインしていません。',
      updateSuccess: (name: string) => `${name} を更新しました。`,
      scopedAssignmentsTitle: '範囲ロール割当て',
      scopedAssignmentsDescription:
        'テナント、配下スコープ、タレント範囲でロールを直接割り当てます。一覧ページは閲覧に集中させます。',
      manageRoleTemplates: 'ロールテンプレートを管理',
      scopeField: '範囲',
      roleField: 'ロール',
      expiresAtField: '有効期限',
      assignmentInheritLabel: '対応時は下位範囲へ継承',
      assignmentScopeWarning:
        '範囲、継承、期限の変更は有効アクセスを拡大または縮小する可能性があります。保存前に影響を確認してください。',
      assignmentInitialAdminWarning:
        'Initial Admin はこのテナントのすべての権限を付与します。保存前に有効なテナント範囲の Initial Admin 割当を少なくとも 1 件残してください。',
      assignmentRemovalWarning:
        'この割当を削除するとユーザーの有効アクセスが変わる可能性があります。保存前に範囲、継承、期限、スナップショット更新結果を確認してください。',
      assignmentSnapshotRefreshExpectation:
        '保存後に権限バージョンと権限スナップショット更新を確認します。',
      assignmentImpactSummary: (
        roleName: string,
        userName: string,
        scopeName: string,
        inheritState: string,
        expiresAt: string
      ) =>
        `ロール: ${roleName}。ユーザー: ${userName}。範囲: ${scopeName}。継承: ${inheritState}。期限: ${expiresAt}。`,
      assignmentCreateInitialAdminTitle: 'Initial Admin を割り当てますか？',
      assignmentCreateInitialAdminConfirm: 'Initial Admin を割り当て',
      assignmentUpdateTitle: (roleName: string) => `${roleName} の割当変更を保存しますか？`,
      assignmentUpdateConfirm: '割当を保存',
      assignmentUpdatePending: '割当を保存中…',
      assignmentRemovalTitle: (roleName: string, userName: string) =>
        `${userName} から ${roleName} を削除しますか？`,
      assignmentRemovalConfirm: '割当を削除',
      assignmentRemovalPending: '割当を削除中…',
      assignmentSubmit: 'ロールを割り当て',
      assignmentPending: 'ロールを割当て中…',
      noAssignmentsTitle: '範囲ロールが未設定です',
      noAssignmentsDescription:
        'このユーザーにはまだロール割当てがありません。上の入力欄で適切な範囲にロールを付与してください。',
      assignmentCreated: (roleName: string) => `${roleName} を割り当てました。`,
      assignmentUpdated: 'ロール割当てを更新しました。',
      assignmentRemoved: 'ロール割当てを削除しました。',
      assignmentSavePending: '保存中…',
      directScopeAccessTitle: '直接範囲アクセス',
      directScopeAccessDescription:
        'ここで直接スコープアクセス記録を確認できます。変更は専用のアクセス画面から行います。',
      noDirectScopeAccessTitle: '直接範囲アクセスはありません',
      noDirectScopeAccessDescription: 'このユーザーには現在、直接アクセスルールがありません。',
    },
    roleEditor: {
      loading: 'システムロールを読み込み中…',
      unavailableTitle: 'システムロールを読み込めません',
      loadError: 'システムロール詳細の読み込みに失敗しました。',
      createError: 'システムロールの作成に失敗しました。',
      updateError: 'システムロールの更新に失敗しました。',
      missingTargetError: '対象のシステムロールがありません。',
      createTitle: 'システムロールを作成',
      titleFallback: 'システムロール',
      backToInventory: 'ロール一覧に戻る',
      badge: (workspaceLabel: string) => workspaceLabel,
      createDescription: '現在の範囲で必要なロール情報と明示的な権限を定義します。',
      editDescription: '一覧に戻らずにロール情報、明示的権限、現在の範囲カバーを確認します。',
      initialAdminLockTitle: 'Initial Admin はロック済み',
      initialAdminLockDescription:
        'Initial Admin は組み込みの復旧ロールです。アクセス喪失を防ぐため、名前と権限はロックされています。',
      summaryExplicitPermissionsLabel: '明示的権限',
      summaryExplicitPermissionsHint:
        '未設定の操作はカタログ既定値を継承するか、利用不可のまま残ります。',
      summaryAssignedUsersLabel: '割当ユーザー',
      summaryAssignedUsersHint: '属性や権限を編集しても、現行割当はここで確認できます。',
      summaryBoundScopesLabel: '紐付け範囲',
      summaryBoundScopesHint:
        '範囲紐付けは現在のロール割当から導出され、別テーブルではありません。',
      scopeBindingsTitle: '割当て由来の範囲紐付け',
      scopeBindingsDescription:
        '現在の範囲カバーは、テナント・配下スコープ・タレント範囲で現在のロール割当から導出されます。',
      scopeBindingsEmpty:
        'このロールをテナント、配下スコープ、タレント範囲へ紐付ける現在の割当はありません。',
      assignedUsersTitle: '割当ユーザー',
      assignedUsersDescription:
        'どのユーザーがこのロールを保持し、どの範囲で付与されているかを確認します。',
      assignedUsersEmpty: '現在このロールを持つユーザーはいません。',
      fields: {
        roleCode: 'ロールコード',
        nameBase: '基準ロール名',
        description: '説明',
      },
      createHint:
        'ロールコードは作成後の安定識別子になります。不要な挙動を避けるため、不要な操作は未設定のままにしてください。',
      editHint:
        'ロールコードは作成後に変更できません。ロールは監査履歴のため保持されます。実効アクセスを変えるには割当を削除するか、許可、拒否、未設定を変更してください。',
      permissionMatrixTitle: '権限マトリクス',
      permissionMatrixDescription: '明示的効果は未設定、許可、拒否のいずれかを選べます。',
      notAvailable: '対象外',
      submitCreate: 'ロールを作成',
      submitSave: 'ロールを保存',
      pendingCreate: 'ロールを作成中…',
      pendingSave: 'ロールを保存中…',
      createSuccess: (name: string) => `${name} を作成しました。`,
      updateSuccess: (name: string) => `${name} を更新しました。`,
      translationManagement: {
        trigger: '翻訳管理',
        title: 'ロール名の翻訳',
        baseValueLabel: '英語の基準名',
        save: '保存',
        cancel: 'キャンセル',
        closeButtonAriaLabel: 'ロール名翻訳ドロワーを閉じる',
        empty: '追加の翻訳はまだ設定されていません。',
        summary: (count: number) => `追加ロケール ${count} 件を設定済みです。`,
        languageLoadError:
          '言語オプションを読み込めません。System Dictionary の Language 項目を読み込んでから再試行してください。',
      },
      validation: {
        code: 'ロールコードは 3〜32 文字で、A-Z、0-9、_ のみ使用できます。',
        nameBase: '基準ロール名は必須です。',
      },
    },
  },
  ko: {
    shared: {
      cancel: 'Cancel',
      confirm: 'Confirm',
      confirmAction: 'Confirm action',
      never: 'Never',
      unavailable: 'Unavailable',
      seen: 'Seen',
      tenantWorkspace: 'Tenant',
      acWorkspace: 'Platform',
      tenantAccessLabel: 'tenant access',
      acAccessLabel: 'platform access',
      tenantSessionLabel: 'tenant context',
      acSessionLabel: 'platform context',
      tenantDirectoryLabel: 'tenant user directory',
      acDirectoryLabel: 'AC identity directory',
      tenantRoot: 'Tenant root',
      unnamedScope: 'Unnamed scope',
      tenantWideAssignment: 'Tenant-wide assignment',
      tenantWideBinding: 'Tenant-wide binding',
      tenantWideVisibility: 'Tenant-wide visibility',
      grantedLabel: 'Granted',
      expiresLabel: 'Expires',
      includesSubunits: 'Includes subunits',
      inherit: 'Inherit',
      userActive: 'User Active',
      userInactive: 'User Inactive',
      protectedRole: 'Built-in locked',
      customRole: 'Custom role',
      save: 'Save',
      remove: 'Remove',
      noCompatibleRoles: 'No compatible roles',
      assignLinks: (count: number) => `${count} active links`,
      scopeCount: (count: number) => `${count} scope${count === 1 ? '' : 's'}`,
      userCount: (count: number) => `${count} user${count === 1 ? '' : 's'}`,
      assignmentCount: (count: number) => `${count} assignment${count === 1 ? '' : 's'}`,
      inheritedAssignments: (count: number) =>
        `${count} inherited assignment${count === 1 ? '' : 's'} currently propagate access.`,
    },
    management: {
      pageUnavailableTitle: 'User management is unavailable',
      pageUnavailableDescription: (workspaceAccessLabel: string) =>
        `The ${workspaceAccessLabel} could not load users, roles, or delegated-admin resources.`,
      badge: (workspaceLabel: string) => workspaceLabel,
      title: 'Identity, role, and delegation control',
      description:
        'Manage users, role definitions, and delegation here. Use dedicated pages when you need to create or edit.',
      summaryVisibleUsersLabel: 'Visible Users',
      summaryVisibleUsersHint: (_workspaceSessionLabel: string) =>
        'Users matching the current filters.',
      summaryRoleTemplatesLabel: 'Role Templates',
      summaryRoleTemplatesHint: 'Role permission templates available for assignment are shown here.',
      summaryDelegationsLabel: 'Delegations',
      summaryDelegationsHint:
        'Delegated-admin records can target subsidiary or talent scope from this page.',
      tabs: {
        users: 'Users',
        roles: 'Roles',
        delegation: 'Delegation',
      },
      users: {
        title: 'System users',
        description:
          'Keep the list focused on search, status, and account actions. Creating and editing users happens on dedicated pages.',
        newUser: 'New user',
        searchLabel: 'Search',
        searchPlaceholder: 'Search username, email, or display name',
        statusLabel: 'Status',
        statusAll: 'All users',
        statusActive: 'Active only',
        statusInactive: 'Inactive only',
        unavailableTitle: 'System users unavailable',
        emptyTitle: 'No system users matched this filter',
        emptyDescription: (workspaceDirectoryLabel: string) =>
          `Adjust the search or status filter to view other users in the ${workspaceDirectoryLabel}.`,
        columns: ['User', 'Status', 'Security', 'Last Login', 'Created', 'Actions'],
        active: 'Active',
        inactive: 'Inactive',
        resetRequired: 'Reset Required',
        totpEnabled: 'TOTP Enabled',
        noTotp: 'No TOTP',
        edit: 'Edit',
        requireTotp: 'Require TOTP',
        requireTotpTitle: (name: string) => `Require TOTP for ${name}?`,
        requireTotpDescription:
          'The next successful login will require this user to complete TOTP enrollment before access is restored.',
        requireTotpConfirm: 'Require TOTP',
        requireTotpPending: 'Saving TOTP requirement…',
        requireTotpSuccess: (name: string) => `${name} must configure TOTP on next login.`,
        requireTotpError: 'Failed to mark the user for TOTP enrollment.',
        deactivate: 'Deactivate',
        deactivateTitle: (name: string) => `Deactivate ${name}?`,
        deactivateDescription: (workspaceAccessLabel: string) =>
          `This user will lose active ${workspaceAccessLabel} until the account is reactivated.`,
        deactivateConfirm: 'Deactivate user',
        deactivatePending: 'Deactivating user…',
        deactivateSuccess: (name: string) => `${name} was deactivated.`,
        deactivateError: 'Failed to deactivate system user.',
        reactivate: 'Reactivate',
        reactivateTitle: (name: string) => `Reactivate ${name}?`,
        reactivateDescription: (workspaceAccessLabel: string) =>
          `Reactivating this user restores ${workspaceAccessLabel} without resetting the rest of the account profile.`,
        reactivateConfirm: 'Reactivate user',
        reactivatePending: 'Reactivating user…',
        reactivateSuccess: (name: string) => `${name} was reactivated.`,
        reactivateError: 'Failed to reactivate system user.',
      },
      roles: {
        title: 'Roles',
        description:
          'Review role coverage here, then open a dedicated role page when deeper changes are needed.',
        newRole: 'New role',
        unavailableTitle: 'Roles unavailable',
        emptyTitle: 'No roles available',
        emptyDescription: (workspaceAccessLabel: string) =>
          `No roles are currently available for ${workspaceAccessLabel}.`,
        columns: ['Role', 'Coverage', 'Users', 'Template', 'Updated', 'Actions'],
        permissions: (count: number) => `${count} permissions`,
        assignedUsers: (count: number) => `${count} assigned users`,
        protected: 'Built-in locked',
        custom: 'Custom role',
        edit: 'Edit',
      },
      delegation: {
        title: 'Delegated administration',
        description:
          'Delegate subsidiary or talent administration with a clear scope and current grant list.',
        grantTitle: 'Grant delegated admin',
        grantDescription: 'Choose a visible scope and assign a user or role.',
        grantButton: 'Grant delegation',
        grantPending: 'Granting delegation…',
        loadingTitle: 'Loading delegatable scopes',
        loadingDescription:
          'The organization tree is loading so the form can offer the right scopes.',
        noScopesTitle: 'No delegatable scopes available',
        noScopesDescription:
          'No visible subsidiary or talent scopes are available for delegated administration.',
        scopeTypeLabel: 'Scope type',
        scopeTypeSubsidiary: 'Subsidiary',
        scopeTypeTalent: 'Talent',
        scopeTargetLabel: 'Scope target',
        delegateTypeLabel: 'Delegate type',
        delegateTypeUser: 'User',
        delegateTypeRole: 'Role',
        delegateLabel: 'Delegate',
        sourceNote:
          'Delegation options come from the visible organization tree plus the current users and roles.',
        selectScopeError: 'Select a scope before granting delegated administration.',
        selectDelegateError: 'Select a delegate before granting delegated administration.',
        createError: 'Failed to create delegated admin assignment.',
        createSuccess: (delegateName: string, scopeName: string) =>
          `${delegateName} was granted delegated administration for ${scopeName}.`,
        unavailableTitle: 'Delegated admins unavailable',
        emptyTitle: 'No delegated admins configured',
        emptyDescription: (isAcWorkspace: boolean) =>
          `This ${isAcWorkspace ? 'AC tenant' : 'tenant'} currently has no subsidiary- or talent-scoped delegated-admin grants.`,
        columns: ['Scope', 'Delegate', 'Granted By', 'Granted At', 'Actions'],
        systemGrantedBy: 'System',
        remove: 'Remove',
        removeTitle: (name: string) => `Remove ${name}?`,
        removeDescription:
          'This removes the delegated-admin grant from the selected scope and immediately removes the assignment from the list.',
        removeConfirm: 'Remove delegation',
        removePending: 'Removing delegation…',
        removeSuccess: (name: string) => `Delegated administration for ${name} was removed.`,
        removeError: 'Failed to remove delegated admin.',
      },
    },
    editor: {
      loading: 'Loading user editor…',
      unavailableTitle: 'User editor unavailable',
      loadError: 'Failed to load system user detail.',
      supportDataError: 'Failed to load role and scope options.',
      missingTargetError: 'Missing system user id.',
      createError: 'Failed to create system user.',
      updateError: 'Failed to update system user.',
      assignmentSelectRoleError: 'Select a role before assigning it.',
      assignmentCreateError: 'Failed to assign role.',
      assignmentUpdateError: 'Failed to update role assignment.',
      assignmentRemoveError: 'Failed to remove role assignment.',
      assignmentPermissionTitle: 'Role assignment unavailable for this scope',
      assignmentPermissionDescription:
        'Your current session cannot assign roles at the selected scope. Profile editing remains available.',
      validation: {
        username: 'Username must be at least 3 characters.',
        email: 'Email address is required.',
        initialPassword: 'Initial password must be at least 12 characters.',
      },
      backToInventory: 'Back to users',
      badge: (workspaceLabel: string) => workspaceLabel,
      createTitle: 'Create system user',
      createDescription:
        'Create a new user on a dedicated page so profile data and role access stay focused.',
      editDescription:
        'Use this page to update profile data, scoped role access, and security actions.',
      accountProfileTitle: 'Account profile',
      fields: {
        username: 'Username',
        email: 'Email',
        initialPassword: 'Initial password',
        forceReset: 'Force password reset on first login',
        displayName: 'Display name',
        phone: 'Phone',
        preferredLanguage: 'Preferred language',
      },
      forceResetDescription:
        'Keep the bootstrap password short-lived by forcing the user through a reset after the first authenticated session.',
      immutableIdentityDescription:
        'Username and email remain immutable here. Password rotation stays in profile and security workflows instead of being hidden inside a crowded list view.',
      submitCreate: 'Create user',
      submitSave: 'Save profile',
      pendingCreate: 'Creating user…',
      pendingSave: 'Saving profile…',
      summaryRoleAssignmentsLabel: 'Role Assignments',
      summaryRoleAssignmentsHint: 'Current role assignments for this user.',
      summaryScopeAccessLabel: 'Scope Access',
      summaryScopeAccessHint: 'Direct visibility rules currently attached to this user.',
      summaryLastLoginLabel: 'Last Login',
      lastLoginSeen: 'Seen',
      lastLoginNeverHint: 'This user has not logged in yet.',
      updateSuccess: (name: string) => `${name} was updated.`,
      scopedAssignmentsTitle: 'Scoped role assignments',
      scopedAssignmentsDescription:
        'Assign roles at tenant, subsidiary, or talent scope from this page. The list page stays focused on browsing.',
      manageRoleTemplates: 'Manage role templates',
      scopeField: 'Scope',
      roleField: 'Role',
      expiresAtField: 'Expires at',
      assignmentInheritLabel: 'Inherit to child scopes when supported',
      assignmentScopeWarning:
        'Changing scope, inheritance, or expiration can expand or contract effective access. Review the before/after access summary before saving.',
      assignmentInitialAdminWarning:
        'Initial Admin grants every permission in this tenant. Keep at least one active tenant-scope Initial Admin assignment before saving.',
      assignmentRemovalWarning:
        "Removing this assignment may change the user's effective access. Review the affected scope, inheritance, expiration, and snapshot refresh result before saving.",
      assignmentSnapshotRefreshExpectation:
        'Permission version and snapshot refresh will be checked after save.',
      assignmentImpactSummary: (
        roleName: string,
        userName: string,
        scopeName: string,
        inheritState: string,
        expiresAt: string
      ) =>
        `Role: ${roleName}. User: ${userName}. Scope: ${scopeName}. Inherit: ${inheritState}. Expires: ${expiresAt}.`,
      assignmentCreateInitialAdminTitle: 'Assign Initial Admin?',
      assignmentCreateInitialAdminConfirm: 'Assign Initial Admin',
      assignmentUpdateTitle: (roleName: string) => `Save changes to ${roleName} assignment?`,
      assignmentUpdateConfirm: 'Save assignment',
      assignmentUpdatePending: 'Saving assignment…',
      assignmentRemovalTitle: (roleName: string, userName: string) =>
        `Remove ${roleName} from ${userName}?`,
      assignmentRemovalConfirm: 'Remove assignment',
      assignmentRemovalPending: 'Removing assignment…',
      assignmentSubmit: 'Assign role',
      assignmentPending: 'Assigning role…',
      noAssignmentsTitle: 'No scoped roles assigned',
      noAssignmentsDescription:
        'This user has no role assignments yet. Use the form above to grant one at the right scope.',
      assignmentCreated: (roleName: string) => `${roleName} was assigned.`,
      assignmentUpdated: 'Role assignment was updated.',
      assignmentRemoved: 'Role assignment was removed.',
      assignmentSavePending: 'Saving…',
      directScopeAccessTitle: 'Direct scope access',
      directScopeAccessDescription:
        'Review direct access rules here. Use the dedicated access flow to change them.',
      noDirectScopeAccessTitle: 'No direct scope access rules',
      noDirectScopeAccessDescription: 'This user has no direct access rules.',
    },
    roleEditor: {
      loading: 'Loading role…',
      unavailableTitle: 'Role unavailable',
      loadError: 'Failed to load role detail.',
      createError: 'Failed to create role.',
      updateError: 'Failed to update role.',
      missingTargetError: 'Missing role target.',
      createTitle: 'Create role',
      titleFallback: 'Role',
      backToInventory: 'Back to roles',
      badge: (workspaceLabel: string) => workspaceLabel,
      createDescription:
        'Define role details and the explicit permissions required for this scope.',
      editDescription:
        'Review role details, explicit permissions, and where this role is assigned.',
      initialAdminLockTitle: 'Initial Admin locked',
      initialAdminLockDescription:
        'Initial Admin is the built-in recovery role. Its name and permissions are locked to prevent access loss.',
      summaryExplicitPermissionsLabel: 'Explicit Permissions',
      summaryExplicitPermissionsHint:
        'Unset actions inherit the broader catalog defaults or remain unavailable.',
      summaryAssignedUsersLabel: 'Assigned Users',
      summaryAssignedUsersHint:
        'Live assignments remain visible while metadata and permissions are edited.',
      summaryBoundScopesLabel: 'Bound Scopes',
      summaryBoundScopesHint: 'Shows where this role is currently assigned.',
      scopeBindingsTitle: 'Assignment-derived scope bindings',
      scopeBindingsDescription:
        'This role is currently assigned at the tenant, subsidiary, or talent level.',
      scopeBindingsEmpty:
        'No current assignments bind this role to a tenant, subsidiary, or talent scope.',
      assignedUsersTitle: 'Assigned users',
      assignedUsersDescription:
        'Review which users currently hold this role and where the assignment is scoped.',
      assignedUsersEmpty: 'No users are currently assigned to this role.',
      fields: {
        roleCode: 'Role code',
        nameBase: 'Base role name',
        description: 'Description',
      },
      createHint:
        'Role code becomes the stable identifier after creation. Leave actions unset to avoid granting behavior you do not need.',
      editHint:
        'Role code stays immutable after creation. Roles are kept for audit history; remove assignments or change Grant, Deny, and Unset states to change effective access.',
      permissionMatrixTitle: 'Permission matrix',
      permissionMatrixDescription: 'Explicit effects can be left unset, granted, or denied.',
      notAvailable: 'N/A',
      submitCreate: 'Create role',
      submitSave: 'Save role',
      pendingCreate: 'Creating role…',
      pendingSave: 'Saving role…',
      createSuccess: (name: string) => `${name} was created.`,
      updateSuccess: (name: string) => `${name} was updated.`,
      translationManagement: {
        trigger: 'Translation management',
        title: 'Role name translations',
        baseValueLabel: 'Base role name (English)',
        save: 'Save',
        cancel: 'Cancel',
        closeButtonAriaLabel: 'Close role name translations drawer',
        empty: 'No additional translations configured yet.',
        summary: (count: number) =>
          `${count} additional locale ${count === 1 ? 'value' : 'values'} configured.`,
        languageLoadError:
          'Language options are temporarily unavailable. Load the System Dictionary languages and try again.',
      },
      validation: {
        code: 'Role code must be 3-32 characters using only A-Z, 0-9, and _.',
        nameBase: 'Base role name is required.',
      },
    },
  },
  fr: {
    shared: {
      cancel: 'Cancel',
      confirm: 'Confirm',
      confirmAction: 'Confirm action',
      never: 'Never',
      unavailable: 'Unavailable',
      seen: 'Seen',
      tenantWorkspace: 'Tenant',
      acWorkspace: 'Platform',
      tenantAccessLabel: 'tenant access',
      acAccessLabel: 'platform access',
      tenantSessionLabel: 'tenant context',
      acSessionLabel: 'platform context',
      tenantDirectoryLabel: 'tenant user directory',
      acDirectoryLabel: 'AC identity directory',
      tenantRoot: 'Tenant root',
      unnamedScope: 'Unnamed scope',
      tenantWideAssignment: 'Tenant-wide assignment',
      tenantWideBinding: 'Tenant-wide binding',
      tenantWideVisibility: 'Tenant-wide visibility',
      grantedLabel: 'Granted',
      expiresLabel: 'Expires',
      includesSubunits: 'Includes subunits',
      inherit: 'Inherit',
      userActive: 'User Active',
      userInactive: 'User Inactive',
      protectedRole: 'Built-in locked',
      customRole: 'Custom role',
      save: 'Save',
      remove: 'Remove',
      noCompatibleRoles: 'No compatible roles',
      assignLinks: (count: number) => `${count} active links`,
      scopeCount: (count: number) => `${count} scope${count === 1 ? '' : 's'}`,
      userCount: (count: number) => `${count} user${count === 1 ? '' : 's'}`,
      assignmentCount: (count: number) => `${count} assignment${count === 1 ? '' : 's'}`,
      inheritedAssignments: (count: number) =>
        `${count} inherited assignment${count === 1 ? '' : 's'} currently propagate access.`,
    },
    management: {
      pageUnavailableTitle: 'User management is unavailable',
      pageUnavailableDescription: (workspaceAccessLabel: string) =>
        `The ${workspaceAccessLabel} could not load users, roles, or delegated-admin resources.`,
      badge: (workspaceLabel: string) => workspaceLabel,
      title: 'Identity, role, and delegation control',
      description:
        'Manage users, role definitions, and delegation here. Use dedicated pages when you need to create or edit.',
      summaryVisibleUsersLabel: 'Visible Users',
      summaryVisibleUsersHint: (_workspaceSessionLabel: string) =>
        'Users matching the current filters.',
      summaryRoleTemplatesLabel: 'Role Templates',
      summaryRoleTemplatesHint: 'Role permission templates available for assignment are shown here.',
      summaryDelegationsLabel: 'Delegations',
      summaryDelegationsHint:
        'Delegated-admin records can target subsidiary or talent scope from this page.',
      tabs: {
        users: 'Users',
        roles: 'Roles',
        delegation: 'Delegation',
      },
      users: {
        title: 'System users',
        description:
          'Keep the list focused on search, status, and account actions. Creating and editing users happens on dedicated pages.',
        newUser: 'New user',
        searchLabel: 'Search',
        searchPlaceholder: 'Search username, email, or display name',
        statusLabel: 'Status',
        statusAll: 'All users',
        statusActive: 'Active only',
        statusInactive: 'Inactive only',
        unavailableTitle: 'System users unavailable',
        emptyTitle: 'No system users matched this filter',
        emptyDescription: (workspaceDirectoryLabel: string) =>
          `Adjust the search or status filter to view other users in the ${workspaceDirectoryLabel}.`,
        columns: ['User', 'Status', 'Security', 'Last Login', 'Created', 'Actions'],
        active: 'Active',
        inactive: 'Inactive',
        resetRequired: 'Reset Required',
        totpEnabled: 'TOTP Enabled',
        noTotp: 'No TOTP',
        edit: 'Edit',
        requireTotp: 'Require TOTP',
        requireTotpTitle: (name: string) => `Require TOTP for ${name}?`,
        requireTotpDescription:
          'The next successful login will require this user to complete TOTP enrollment before access is restored.',
        requireTotpConfirm: 'Require TOTP',
        requireTotpPending: 'Saving TOTP requirement…',
        requireTotpSuccess: (name: string) => `${name} must configure TOTP on next login.`,
        requireTotpError: 'Failed to mark the user for TOTP enrollment.',
        deactivate: 'Deactivate',
        deactivateTitle: (name: string) => `Deactivate ${name}?`,
        deactivateDescription: (workspaceAccessLabel: string) =>
          `This user will lose active ${workspaceAccessLabel} until the account is reactivated.`,
        deactivateConfirm: 'Deactivate user',
        deactivatePending: 'Deactivating user…',
        deactivateSuccess: (name: string) => `${name} was deactivated.`,
        deactivateError: 'Failed to deactivate system user.',
        reactivate: 'Reactivate',
        reactivateTitle: (name: string) => `Reactivate ${name}?`,
        reactivateDescription: (workspaceAccessLabel: string) =>
          `Reactivating this user restores ${workspaceAccessLabel} without resetting the rest of the account profile.`,
        reactivateConfirm: 'Reactivate user',
        reactivatePending: 'Reactivating user…',
        reactivateSuccess: (name: string) => `${name} was reactivated.`,
        reactivateError: 'Failed to reactivate system user.',
      },
      roles: {
        title: 'Roles',
        description:
          'Review role coverage here, then open a dedicated role page when deeper changes are needed.',
        newRole: 'New role',
        unavailableTitle: 'Roles unavailable',
        emptyTitle: 'No roles available',
        emptyDescription: (workspaceAccessLabel: string) =>
          `No roles are currently available for ${workspaceAccessLabel}.`,
        columns: ['Role', 'Coverage', 'Users', 'Template', 'Updated', 'Actions'],
        permissions: (count: number) => `${count} permissions`,
        assignedUsers: (count: number) => `${count} assigned users`,
        protected: 'Built-in locked',
        custom: 'Custom role',
        edit: 'Edit',
      },
      delegation: {
        title: 'Delegated administration',
        description:
          'Delegate subsidiary or talent administration with a clear scope and current grant list.',
        grantTitle: 'Grant delegated admin',
        grantDescription: 'Choose a visible scope and assign a user or role.',
        grantButton: 'Grant delegation',
        grantPending: 'Granting delegation…',
        loadingTitle: 'Loading delegatable scopes',
        loadingDescription:
          'The organization tree is loading so the form can offer the right scopes.',
        noScopesTitle: 'No delegatable scopes available',
        noScopesDescription:
          'No visible subsidiary or talent scopes are available for delegated administration.',
        scopeTypeLabel: 'Scope type',
        scopeTypeSubsidiary: 'Subsidiary',
        scopeTypeTalent: 'Talent',
        scopeTargetLabel: 'Scope target',
        delegateTypeLabel: 'Delegate type',
        delegateTypeUser: 'User',
        delegateTypeRole: 'Role',
        delegateLabel: 'Delegate',
        sourceNote:
          'Delegation options come from the visible organization tree plus the current users and roles.',
        selectScopeError: 'Select a scope before granting delegated administration.',
        selectDelegateError: 'Select a delegate before granting delegated administration.',
        createError: 'Failed to create delegated admin assignment.',
        createSuccess: (delegateName: string, scopeName: string) =>
          `${delegateName} was granted delegated administration for ${scopeName}.`,
        unavailableTitle: 'Delegated admins unavailable',
        emptyTitle: 'No delegated admins configured',
        emptyDescription: (isAcWorkspace: boolean) =>
          `This ${isAcWorkspace ? 'AC tenant' : 'tenant'} currently has no subsidiary- or talent-scoped delegated-admin grants.`,
        columns: ['Scope', 'Delegate', 'Granted By', 'Granted At', 'Actions'],
        systemGrantedBy: 'System',
        remove: 'Remove',
        removeTitle: (name: string) => `Remove ${name}?`,
        removeDescription:
          'This removes the delegated-admin grant from the selected scope and immediately removes the assignment from the list.',
        removeConfirm: 'Remove delegation',
        removePending: 'Removing delegation…',
        removeSuccess: (name: string) => `Delegated administration for ${name} was removed.`,
        removeError: 'Failed to remove delegated admin.',
      },
    },
    editor: {
      loading: 'Loading user editor…',
      unavailableTitle: 'User editor unavailable',
      loadError: 'Failed to load system user detail.',
      supportDataError: 'Failed to load role and scope options.',
      missingTargetError: 'Missing system user id.',
      createError: 'Failed to create system user.',
      updateError: 'Failed to update system user.',
      assignmentSelectRoleError: 'Select a role before assigning it.',
      assignmentCreateError: 'Failed to assign role.',
      assignmentUpdateError: 'Failed to update role assignment.',
      assignmentRemoveError: 'Failed to remove role assignment.',
      assignmentPermissionTitle: 'Role assignment unavailable for this scope',
      assignmentPermissionDescription:
        'Your current session cannot assign roles at the selected scope. Profile editing remains available.',
      validation: {
        username: 'Username must be at least 3 characters.',
        email: 'Email address is required.',
        initialPassword: 'Initial password must be at least 12 characters.',
      },
      backToInventory: 'Back to users',
      badge: (workspaceLabel: string) => workspaceLabel,
      createTitle: 'Create system user',
      createDescription:
        'Create a new user on a dedicated page so profile data and role access stay focused.',
      editDescription:
        'Use this page to update profile data, scoped role access, and security actions.',
      accountProfileTitle: 'Account profile',
      fields: {
        username: 'Username',
        email: 'Email',
        initialPassword: 'Initial password',
        forceReset: 'Force password reset on first login',
        displayName: 'Display name',
        phone: 'Phone',
        preferredLanguage: 'Preferred language',
      },
      forceResetDescription:
        'Keep the bootstrap password short-lived by forcing the user through a reset after the first authenticated session.',
      immutableIdentityDescription:
        'Username and email remain immutable here. Password rotation stays in profile and security workflows instead of being hidden inside a crowded list view.',
      submitCreate: 'Create user',
      submitSave: 'Save profile',
      pendingCreate: 'Creating user…',
      pendingSave: 'Saving profile…',
      summaryRoleAssignmentsLabel: 'Role Assignments',
      summaryRoleAssignmentsHint: 'Current role assignments for this user.',
      summaryScopeAccessLabel: 'Scope Access',
      summaryScopeAccessHint: 'Direct visibility rules currently attached to this user.',
      summaryLastLoginLabel: 'Last Login',
      lastLoginSeen: 'Seen',
      lastLoginNeverHint: 'This user has not logged in yet.',
      updateSuccess: (name: string) => `${name} was updated.`,
      scopedAssignmentsTitle: 'Scoped role assignments',
      scopedAssignmentsDescription:
        'Assign roles at tenant, subsidiary, or talent scope from this page. The list page stays focused on browsing.',
      manageRoleTemplates: 'Manage role templates',
      scopeField: 'Scope',
      roleField: 'Role',
      expiresAtField: 'Expires at',
      assignmentInheritLabel: 'Inherit to child scopes when supported',
      assignmentScopeWarning:
        'Changing scope, inheritance, or expiration can expand or contract effective access. Review the before/after access summary before saving.',
      assignmentInitialAdminWarning:
        'Initial Admin grants every permission in this tenant. Keep at least one active tenant-scope Initial Admin assignment before saving.',
      assignmentRemovalWarning:
        "Removing this assignment may change the user's effective access. Review the affected scope, inheritance, expiration, and snapshot refresh result before saving.",
      assignmentSnapshotRefreshExpectation:
        'Permission version and snapshot refresh will be checked after save.',
      assignmentImpactSummary: (
        roleName: string,
        userName: string,
        scopeName: string,
        inheritState: string,
        expiresAt: string
      ) =>
        `Role: ${roleName}. User: ${userName}. Scope: ${scopeName}. Inherit: ${inheritState}. Expires: ${expiresAt}.`,
      assignmentCreateInitialAdminTitle: 'Assign Initial Admin?',
      assignmentCreateInitialAdminConfirm: 'Assign Initial Admin',
      assignmentUpdateTitle: (roleName: string) => `Save changes to ${roleName} assignment?`,
      assignmentUpdateConfirm: 'Save assignment',
      assignmentUpdatePending: 'Saving assignment…',
      assignmentRemovalTitle: (roleName: string, userName: string) =>
        `Remove ${roleName} from ${userName}?`,
      assignmentRemovalConfirm: 'Remove assignment',
      assignmentRemovalPending: 'Removing assignment…',
      assignmentSubmit: 'Assign role',
      assignmentPending: 'Assigning role…',
      noAssignmentsTitle: 'No scoped roles assigned',
      noAssignmentsDescription:
        'This user has no role assignments yet. Use the form above to grant one at the right scope.',
      assignmentCreated: (roleName: string) => `${roleName} was assigned.`,
      assignmentUpdated: 'Role assignment was updated.',
      assignmentRemoved: 'Role assignment was removed.',
      assignmentSavePending: 'Saving…',
      directScopeAccessTitle: 'Direct scope access',
      directScopeAccessDescription:
        'Review direct access rules here. Use the dedicated access flow to change them.',
      noDirectScopeAccessTitle: 'No direct scope access rules',
      noDirectScopeAccessDescription: 'This user has no direct access rules.',
    },
    roleEditor: {
      loading: 'Loading role…',
      unavailableTitle: 'Role unavailable',
      loadError: 'Failed to load role detail.',
      createError: 'Failed to create role.',
      updateError: 'Failed to update role.',
      missingTargetError: 'Missing role target.',
      createTitle: 'Create role',
      titleFallback: 'Role',
      backToInventory: 'Back to roles',
      badge: (workspaceLabel: string) => workspaceLabel,
      createDescription:
        'Define role details and the explicit permissions required for this scope.',
      editDescription:
        'Review role details, explicit permissions, and where this role is assigned.',
      initialAdminLockTitle: 'Initial Admin locked',
      initialAdminLockDescription:
        'Initial Admin is the built-in recovery role. Its name and permissions are locked to prevent access loss.',
      summaryExplicitPermissionsLabel: 'Explicit Permissions',
      summaryExplicitPermissionsHint:
        'Unset actions inherit the broader catalog defaults or remain unavailable.',
      summaryAssignedUsersLabel: 'Assigned Users',
      summaryAssignedUsersHint:
        'Live assignments remain visible while metadata and permissions are edited.',
      summaryBoundScopesLabel: 'Bound Scopes',
      summaryBoundScopesHint: 'Shows where this role is currently assigned.',
      scopeBindingsTitle: 'Assignment-derived scope bindings',
      scopeBindingsDescription:
        'This role is currently assigned at the tenant, subsidiary, or talent level.',
      scopeBindingsEmpty:
        'No current assignments bind this role to a tenant, subsidiary, or talent scope.',
      assignedUsersTitle: 'Assigned users',
      assignedUsersDescription:
        'Review which users currently hold this role and where the assignment is scoped.',
      assignedUsersEmpty: 'No users are currently assigned to this role.',
      fields: {
        roleCode: 'Role code',
        nameBase: 'Base role name',
        description: 'Description',
      },
      createHint:
        'Role code becomes the stable identifier after creation. Leave actions unset to avoid granting behavior you do not need.',
      editHint:
        'Role code stays immutable after creation. Roles are kept for audit history; remove assignments or change Grant, Deny, and Unset states to change effective access.',
      permissionMatrixTitle: 'Permission matrix',
      permissionMatrixDescription: 'Explicit effects can be left unset, granted, or denied.',
      notAvailable: 'N/A',
      submitCreate: 'Create role',
      submitSave: 'Save role',
      pendingCreate: 'Creating role…',
      pendingSave: 'Saving role…',
      createSuccess: (name: string) => `${name} was created.`,
      updateSuccess: (name: string) => `${name} was updated.`,
      translationManagement: {
        trigger: 'Translation management',
        title: 'Role name translations',
        baseValueLabel: 'Base role name (English)',
        save: 'Save',
        cancel: 'Cancel',
        closeButtonAriaLabel: 'Close role name translations drawer',
        empty: 'No additional translations configured yet.',
        summary: (count: number) =>
          `${count} additional locale ${count === 1 ? 'value' : 'values'} configured.`,
        languageLoadError:
          'Language options are temporarily unavailable. Load the System Dictionary languages and try again.',
      },
      validation: {
        code: 'Role code must be 3-32 characters using only A-Z, 0-9, and _.',
        nameBase: 'Base role name is required.',
      },
    },
  },
} as const;

export type UserManagementCopy = (typeof COPY)[SupportedUiLocale];
const USER_MANAGEMENT_COPY_RECORD = COPY as unknown as Record<
  SupportedUiLocale,
  UserManagementCopy
>;

function resolveUserManagementCopyByLocale(locale: UserManagementLocale) {
  return resolveLocaleRecord(locale, USER_MANAGEMENT_COPY_RECORD) as UserManagementCopy;
}

export function formatUserManagementDateTime(
  value: string | null | undefined,
  locale: UserManagementLocale,
  fallback: string
) {
  return formatLocaleDateTime(locale, value ?? null, fallback);
}

export function getLocalizedRbacActionLabel(
  action: PermissionAction,
  locale: UserManagementLocale
) {
  return ROLE_ACTION_LABELS[locale][action];
}

export function getLocalizedRolePermissionOptionLabel(
  value: RbacRolePolicyEffect | 'unset',
  locale: UserManagementLocale
) {
  return ROLE_PERMISSION_OPTION_LABELS[locale][value];
}

export function getLocalizedScopeTypeLabel(
  value: 'tenant' | 'subsidiary' | 'talent',
  locale: UserManagementLocale
) {
  return SCOPE_TYPE_LABELS[locale][value];
}

export function getLocalizedDelegateTypeLabel(
  value: 'user' | 'role',
  locale: UserManagementLocale
) {
  return DELEGATE_TYPE_LABELS[locale][value];
}

export function getLocalizedLanguageLabel(value: SupportedUiLocale, locale: UserManagementLocale) {
  return LANGUAGE_LABELS[locale][value];
}

export function getLocalizedRoleResourceColumnLabel(locale: UserManagementLocale) {
  return ROLE_RESOURCE_COLUMN_LABELS[locale];
}

export function getLocalizedExplicitPermissionCountLabel(
  count: number,
  locale: UserManagementLocale
) {
  return EXPLICIT_PERMISSION_COUNT_LABELS[locale](count);
}

export function pickLocalizedName(
  values: {
    name?: Record<SupportedUiLocale, string> | null;
    localizedName?: string | null;
    code?: string | null;
  },
  locale: UserManagementLocale
) {
  if (values.localizedName?.trim()) {
    return values.localizedName;
  }

  if (values.name) {
    return pickLocaleText(locale, values.name);
  }

  return values.code || '';
}

export function useUserManagementCopy() {
  const { locale } = useUiLocale();

  return {
    copy: resolveUserManagementCopyByLocale(locale),
    locale,
  };
}
