# © 2026 月球厨师莱恩 (TPMOONCHEFRYAN) – PolyForm Noncommercial License

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcrn-worker
  namespace: tcrn
  labels:
    app.kubernetes.io/name: tcrn-worker
    app.kubernetes.io/part-of: tcrn-tms
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: tcrn-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tcrn-worker
        app.kubernetes.io/part-of: tcrn-tms
    spec:
      terminationGracePeriodSeconds: 30
      # registry-secret-placeholder
      containers:
        - name: worker
          image: ghcr.io/tpmoonchefryan/tcrn-tms/worker:replace-me
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
          env:
            - name: NODE_ENV
              value: production
            - name: ENABLE_SCHEDULED_JOBS
              value: 'true'
          envFrom:
            - secretRef:
                name: tcrn-runtime-env
