import { type SupportedUiLocale } from '@tcrn/shared';

import { resolveLocaleRecord } from '@/platform/runtime/locale/locale-text';

const LABELS = {
  en: {
    statusLabels: {
      ready: 'Ready',
      empty_no_manifest: 'No manifest',
      partial_metadata_warning: 'Partial metadata',
      drift_warning: 'Drift warning',
      redaction_warning: 'Redaction warning',
      composition_unavailable: 'Dry-run unavailable',
      permission_denied: 'Permission denied',
      api_error_retry: 'Retry needed',
      stale_verification: 'Stale verification',
    },
    scopeLabels: {
      tenant: 'Tenant',
      subsidiary: 'Subsidiary',
      talent: 'Talent',
    },
    stabilityLabels: {
      active: 'Active',
      deprecated: 'Deprecated',
      future: 'Future',
      stable: 'Stable',
      experimental: 'Experimental',
    },
    artifactStatusLabels: {
      ready: 'Ready',
      disabled: 'Disabled',
      empty_no_manifest: 'No manifest',
      partial_metadata_warning: 'Partial metadata',
    },
    artifactKindLabels: {
      manifest: 'Manifest',
      'api-readonly-export': 'API read-only export',
      'schema-catalog': 'Schema catalog',
      types: 'Type declarations',
      'sdk-readonly': 'Read-only SDK',
      'openapi-readonly': 'Read-only OpenAPI',
      'composed-dry-run': 'Composed dry-run',
    },
    downloadUnavailable: 'Download unavailable',
    downloadDisabledReason: 'Reason',
    downloadDisabledReasons: {
      empty_no_manifest: 'Downloads are disabled until the manifest exists.',
      redaction_warning: 'Downloads are disabled until redaction passes.',
      drift_warning: 'Downloads are disabled until generated artifacts match the registry.',
      stale_verification: 'Downloads are disabled until readback is refreshed.',
      artifact_disabled: 'This artifact is not ready.',
      redaction_failed: 'This artifact failed redaction.',
      missing_status: 'This artifact is missing from the current status readback.',
    },
  },
  zh_HANS: {
    statusLabels: {
      ready: '就绪',
      empty_no_manifest: '无 manifest',
      partial_metadata_warning: '元数据不完整',
      drift_warning: '漂移警告',
      redaction_warning: '脱敏警告',
      composition_unavailable: 'dry-run 不可用',
      permission_denied: '权限不足',
      api_error_retry: '需要重试',
      stale_verification: '验证已过期',
    },
    scopeLabels: {
      tenant: '租户',
      subsidiary: '分目录',
      talent: '艺人',
    },
    stabilityLabels: {
      active: '启用',
      deprecated: '已废弃',
      future: '未来',
      stable: '稳定',
      experimental: '实验',
    },
    artifactStatusLabels: {
      ready: '就绪',
      disabled: '已禁用',
      empty_no_manifest: '无 manifest',
      partial_metadata_warning: '元数据不完整',
    },
    artifactKindLabels: {
      manifest: 'Manifest',
      'api-readonly-export': 'API 只读导出',
      'schema-catalog': 'Schema 目录',
      types: '类型声明',
      'sdk-readonly': '只读 SDK',
      'openapi-readonly': '只读 OpenAPI',
      'composed-dry-run': '组合 dry-run',
    },
    downloadUnavailable: '无法下载',
    downloadDisabledReason: '原因',
    downloadDisabledReasons: {
      empty_no_manifest: 'manifest 生成前禁止下载。',
      redaction_warning: '脱敏通过前禁止下载。',
      drift_warning: '生成物与注册表一致前禁止下载。',
      stale_verification: '刷新读回验证前禁止下载。',
      artifact_disabled: '该生成物尚未就绪。',
      redaction_failed: '该生成物未通过脱敏。',
      missing_status: '当前状态读回中缺少该生成物。',
    },
  },
  zh_HANT: {
    statusLabels: {
      ready: '就緒',
      empty_no_manifest: '無 manifest',
      partial_metadata_warning: '中繼資料不完整',
      drift_warning: '漂移警告',
      redaction_warning: '遮罩警告',
      composition_unavailable: 'dry-run 不可用',
      permission_denied: '權限不足',
      api_error_retry: '需要重試',
      stale_verification: '驗證已過期',
    },
    scopeLabels: {
      tenant: '租戶',
      subsidiary: '分目錄',
      talent: '藝人',
    },
    stabilityLabels: {
      active: '啟用',
      deprecated: '已廢棄',
      future: '未來',
      stable: '穩定',
      experimental: '實驗',
    },
    artifactStatusLabels: {
      ready: '就緒',
      disabled: '已停用',
      empty_no_manifest: '無 manifest',
      partial_metadata_warning: '中繼資料不完整',
    },
    artifactKindLabels: {
      manifest: 'Manifest',
      'api-readonly-export': 'API 唯讀匯出',
      'schema-catalog': 'Schema 目錄',
      types: '型別宣告',
      'sdk-readonly': '唯讀 SDK',
      'openapi-readonly': '唯讀 OpenAPI',
      'composed-dry-run': '組合 dry-run',
    },
    downloadUnavailable: '無法下載',
    downloadDisabledReason: '原因',
    downloadDisabledReasons: {
      empty_no_manifest: 'manifest 產生前禁止下載。',
      redaction_warning: '遮罩通過前禁止下載。',
      drift_warning: '產物與註冊表一致前禁止下載。',
      stale_verification: '重新整理讀回驗證前禁止下載。',
      artifact_disabled: '此產物尚未就緒。',
      redaction_failed: '此產物未通過遮罩。',
      missing_status: '目前狀態讀回缺少此產物。',
    },
  },
  ja: {
    statusLabels: {
      ready: '準備完了',
      empty_no_manifest: 'manifest なし',
      partial_metadata_warning: 'メタデータ不足',
      drift_warning: 'ドリフト警告',
      redaction_warning: 'マスク警告',
      composition_unavailable: 'dry-run 利用不可',
      permission_denied: '権限不足',
      api_error_retry: '再試行が必要',
      stale_verification: '検証が古い',
    },
    scopeLabels: {
      tenant: 'テナント',
      subsidiary: '子組織',
      talent: 'タレント',
    },
    stabilityLabels: {
      active: '有効',
      deprecated: '非推奨',
      future: '将来',
      stable: '安定',
      experimental: '実験',
    },
    artifactStatusLabels: {
      ready: '準備完了',
      disabled: '無効',
      empty_no_manifest: 'manifest なし',
      partial_metadata_warning: 'メタデータ不足',
    },
    artifactKindLabels: {
      manifest: 'Manifest',
      'api-readonly-export': 'API 読み取り専用エクスポート',
      'schema-catalog': 'Schema カタログ',
      types: '型宣言',
      'sdk-readonly': '読み取り専用 SDK',
      'openapi-readonly': '読み取り専用 OpenAPI',
      'composed-dry-run': '合成 dry-run',
    },
    downloadUnavailable: 'ダウンロード不可',
    downloadDisabledReason: '理由',
    downloadDisabledReasons: {
      empty_no_manifest: 'manifest が生成されるまでダウンロードできません。',
      redaction_warning: 'マスクが通るまでダウンロードできません。',
      drift_warning: '生成物がレジストリと一致するまでダウンロードできません。',
      stale_verification: '読み戻し検証を更新するまでダウンロードできません。',
      artifact_disabled: 'この生成物はまだ準備できていません。',
      redaction_failed: 'この生成物はマスク検証に失敗しました。',
      missing_status: '現在の状態読みにこの生成物がありません。',
    },
  },
  ko: {
    statusLabels: {
      ready: '준비됨',
      empty_no_manifest: 'manifest 없음',
      partial_metadata_warning: '메타데이터 불완전',
      drift_warning: '드리프트 경고',
      redaction_warning: '마스킹 경고',
      composition_unavailable: 'dry-run 사용 불가',
      permission_denied: '권한 부족',
      api_error_retry: '재시도 필요',
      stale_verification: '검증 만료',
    },
    scopeLabels: {
      tenant: '테넌트',
      subsidiary: '하위 스코프',
      talent: '아티스트',
    },
    stabilityLabels: {
      active: '활성',
      deprecated: '사용 중단',
      future: '예정',
      stable: '안정',
      experimental: '실험',
    },
    artifactStatusLabels: {
      ready: '준비됨',
      disabled: '비활성',
      empty_no_manifest: 'manifest 없음',
      partial_metadata_warning: '메타데이터 불완전',
    },
    artifactKindLabels: {
      manifest: 'Manifest',
      'api-readonly-export': 'API 읽기 전용 내보내기',
      'schema-catalog': 'Schema 카탈로그',
      types: '타입 선언',
      'sdk-readonly': '읽기 전용 SDK',
      'openapi-readonly': '읽기 전용 OpenAPI',
      'composed-dry-run': '구성 dry-run',
    },
    downloadUnavailable: '다운로드 불가',
    downloadDisabledReason: '사유',
    downloadDisabledReasons: {
      empty_no_manifest: 'manifest가 생성될 때까지 다운로드가 비활성화됩니다.',
      redaction_warning: '마스킹이 통과할 때까지 다운로드가 비활성화됩니다.',
      drift_warning: '생성물이 레지스트리와 일치할 때까지 다운로드가 비활성화됩니다.',
      stale_verification: '읽기 검증을 새로고침할 때까지 다운로드가 비활성화됩니다.',
      artifact_disabled: '이 생성물은 아직 준비되지 않았습니다.',
      redaction_failed: '이 생성물은 마스킹 검증에 실패했습니다.',
      missing_status: '현재 상태 읽기에 이 생성물이 없습니다.',
    },
  },
  fr: {
    statusLabels: {
      ready: 'Pret',
      empty_no_manifest: 'Aucun manifest',
      partial_metadata_warning: 'Metadonnees partielles',
      drift_warning: 'Alerte derive',
      redaction_warning: 'Alerte redaction',
      composition_unavailable: 'Dry-run indisponible',
      permission_denied: 'Permission refusee',
      api_error_retry: 'Nouvel essai requis',
      stale_verification: 'Verification obsolete',
    },
    scopeLabels: {
      tenant: 'Tenant',
      subsidiary: 'Portee secondaire',
      talent: 'Talent',
    },
    stabilityLabels: {
      active: 'Actif',
      deprecated: 'Obsolete',
      future: 'Futur',
      stable: 'Stable',
      experimental: 'Experimental',
    },
    artifactStatusLabels: {
      ready: 'Pret',
      disabled: 'Desactive',
      empty_no_manifest: 'Aucun manifest',
      partial_metadata_warning: 'Metadonnees partielles',
    },
    artifactKindLabels: {
      manifest: 'Manifest',
      'api-readonly-export': 'Export API lecture seule',
      'schema-catalog': 'Catalogue schema',
      types: 'Declarations de types',
      'sdk-readonly': 'SDK lecture seule',
      'openapi-readonly': 'OpenAPI lecture seule',
      'composed-dry-run': 'Dry-run compose',
    },
    downloadUnavailable: 'Telechargement indisponible',
    downloadDisabledReason: 'Raison',
    downloadDisabledReasons: {
      empty_no_manifest: 'Telechargements desactives tant que le manifest est absent.',
      redaction_warning: 'Telechargements desactives tant que la redaction ne passe pas.',
      drift_warning: 'Telechargements desactives tant que les artefacts ne correspondent pas au registre.',
      stale_verification: 'Telechargements desactives tant que la verification n est pas rafraichie.',
      artifact_disabled: 'Cet artefact n est pas pret.',
      redaction_failed: 'Cet artefact a echoue la redaction.',
      missing_status: 'Cet artefact manque dans la lecture d etat courante.',
    },
  },
} as const;

const COPY = {
  en: {
    eyebrow: 'TCRN Builder',
    title: 'Builder Registry',
    subtitle:
      'Read-only TCRN-native capability metadata. This is not an app builder, plugin marketplace, code runner, or database editor.',
    readonly: 'Read-only',
    refresh: 'Refresh readback',
    downloading: 'Preparing download',
    download: 'Download',
    downloadMenu: 'Download artifact',
    openSwagger: 'Open Swagger docs',
    openApiRegistry: 'Open API Registry',
    inspectDryRun: 'Inspect dry-run',
    search: 'Search modules and capabilities',
    module: 'Module',
    capability: 'Capability',
    scope: 'Scope',
    operations: 'Operations',
    readOperations: 'Read operations',
    artifacts: 'Artifacts',
    stability: 'Stability',
    permissions: 'Permissions',
    lastVerified: 'Last verified',
    actions: 'Actions',
    inspect: 'Inspect',
    close: 'Close',
    loadingTitle: 'Loading Builder Registry',
    loadingDescription: 'Reading generated manifests and read-only artifact status.',
    emptyTitle: 'No Builder manifest',
    emptyDescription: 'Generated Builder Registry manifests are unavailable.',
    deniedTitle: 'AC permission required',
    errorTitle: 'Builder Registry unavailable',
    retry: 'Retry',
    ready: 'Ready',
    warning: 'Warning',
    disabled: 'Disabled',
    noPermission: 'No static permission',
    detailTitle: 'Builder Registry detail',
    sourceRefs: 'Source refs',
    schemaRefs: 'Schema refs',
    dynamicPermission: 'Dynamic permission is classified and remains enforced by TCRN RBAC.',
    dryRunTitle: 'Composed dry-run',
    dryRunNote: 'Dry-run only. No editor, script input, SQL box, deploy, publish, or mutation action is available.',
    unsupportedReasons: 'Unsupported reasons',
    downloads: 'Downloads',
    modulesMetric: 'Modules',
    capabilitiesMetric: 'Capabilities',
    operationsMetric: 'Read operations',
    generatedMetric: 'Generated artifacts',
    generatedAt: 'Generated',
    sourceCommit: 'Source commit',
    manifestVersion: 'Manifest version',
    manifestChip: 'Manifest',
    sdkDocsChip: 'SDK/docs',
    schemaCoverageChip: 'Schema coverage',
    composedDryRunChip: 'Composed dry-run',
    redactionChip: 'Redaction',
    moduleFilter: 'Module filter',
    warningFilter: 'Warning filter',
    withWarnings: 'With warnings',
    withoutWarnings: 'Without warnings',
    warningsTitle: 'Warnings',
    noWarnings: 'No warnings',
    generatedArtifactsTitle: 'Generated artifacts',
    sourceRegistryRefs: 'Source registry refs',
    controllerSource: 'Controller source',
    openapiSource: 'OpenAPI source',
    operationSource: 'Operation source',
    nativeRefs: 'Native operation refs',
    permissionRequirements: 'Permission requirements',
    scopeRequirements: 'Scope requirements',
    dryRunMode: 'Dry-run mode',
    inputSchema: 'Input schema',
    dryRunPlan: 'Dry-run plan',
    redactedSampleOutput: 'Redacted sample output',
    all: 'All',
    ...LABELS.en,
  },
  zh_HANS: {
    eyebrow: 'TCRN Builder',
    title: 'Builder 注册表',
    subtitle:
      '只读的 TCRN 原生能力元数据。这里不是应用构建器、插件市场、代码运行器或数据库编辑器。',
    readonly: '只读',
    refresh: '刷新读回',
    downloading: '正在准备下载',
    download: '下载',
    downloadMenu: '下载生成物',
    openSwagger: '打开 Swagger 文档',
    openApiRegistry: '打开 API 注册表',
    inspectDryRun: '查看 dry-run',
    search: '搜索模块与能力',
    module: '模块',
    capability: '能力',
    scope: '范围',
    operations: '操作',
    readOperations: '只读操作',
    artifacts: '生成物',
    stability: '稳定性',
    permissions: '权限',
    lastVerified: '最后验证',
    actions: '操作',
    inspect: '查看',
    close: '关闭',
    loadingTitle: '正在加载 Builder 注册表',
    loadingDescription: '正在读取生成的 manifest 与只读生成物状态。',
    emptyTitle: '暂无 Builder manifest',
    emptyDescription: '生成的 Builder 注册表 manifest 不可用。',
    deniedTitle: '需要 AC 权限',
    errorTitle: 'Builder 注册表不可用',
    retry: '重试',
    ready: '就绪',
    warning: '警告',
    disabled: '已禁用',
    noPermission: '无静态权限',
    detailTitle: 'Builder 注册表详情',
    sourceRefs: '来源引用',
    schemaRefs: 'Schema 引用',
    dynamicPermission: '动态权限已分类，仍由 TCRN RBAC 强制执行。',
    dryRunTitle: '组合 dry-run',
    dryRunNote: '仅 dry-run。没有编辑器、脚本输入、SQL 框、部署、发布或写入操作。',
    unsupportedReasons: '不可用原因',
    downloads: '下载',
    modulesMetric: '模块',
    capabilitiesMetric: '能力',
    operationsMetric: '只读操作',
    generatedMetric: '生成物',
    generatedAt: '生成时间',
    sourceCommit: '来源提交',
    manifestVersion: 'Manifest 版本',
    manifestChip: 'Manifest',
    sdkDocsChip: 'SDK/文档',
    schemaCoverageChip: 'Schema 覆盖',
    composedDryRunChip: '组合 dry-run',
    redactionChip: '脱敏',
    moduleFilter: '模块过滤',
    warningFilter: '警告过滤',
    withWarnings: '有警告',
    withoutWarnings: '无警告',
    warningsTitle: '警告',
    noWarnings: '无警告',
    generatedArtifactsTitle: '生成物',
    sourceRegistryRefs: '来源注册表引用',
    controllerSource: 'Controller 来源',
    openapiSource: 'OpenAPI 来源',
    operationSource: '操作来源',
    nativeRefs: '原生操作引用',
    permissionRequirements: '权限要求',
    scopeRequirements: 'Scope 要求',
    dryRunMode: 'Dry-run 模式',
    inputSchema: '输入 Schema',
    dryRunPlan: 'Dry-run 计划',
    redactedSampleOutput: '脱敏示例输出',
    all: '全部',
    ...LABELS.zh_HANS,
  },
  zh_HANT: {
    eyebrow: 'TCRN Builder',
    title: 'Builder 註冊表',
    subtitle:
      '唯讀的 TCRN 原生能力中繼資料。這裡不是應用構建器、外掛市場、代碼執行器或資料庫編輯器。',
    readonly: '唯讀',
    refresh: '重新整理讀回',
    downloading: '正在準備下載',
    download: '下載',
    downloadMenu: '下載產物',
    openSwagger: '開啟 Swagger 文件',
    openApiRegistry: '開啟 API 註冊表',
    inspectDryRun: '檢視 dry-run',
    search: '搜尋模組與能力',
    module: '模組',
    capability: '能力',
    scope: '範圍',
    operations: '操作',
    readOperations: '唯讀操作',
    artifacts: '產物',
    stability: '穩定性',
    permissions: '權限',
    lastVerified: '最後驗證',
    actions: '操作',
    inspect: '檢視',
    close: '關閉',
    loadingTitle: '正在載入 Builder 註冊表',
    loadingDescription: '正在讀取產生的 manifest 與唯讀產物狀態。',
    emptyTitle: '尚無 Builder manifest',
    emptyDescription: '產生的 Builder 註冊表 manifest 不可用。',
    deniedTitle: '需要 AC 權限',
    errorTitle: 'Builder 註冊表不可用',
    retry: '重試',
    ready: '就緒',
    warning: '警告',
    disabled: '已停用',
    noPermission: '無靜態權限',
    detailTitle: 'Builder 註冊表詳情',
    sourceRefs: '來源引用',
    schemaRefs: 'Schema 引用',
    dynamicPermission: '動態權限已分類，仍由 TCRN RBAC 強制執行。',
    dryRunTitle: '組合 dry-run',
    dryRunNote: '僅 dry-run。沒有編輯器、腳本輸入、SQL 框、部署、發布或寫入操作。',
    unsupportedReasons: '不可用原因',
    downloads: '下載',
    modulesMetric: '模組',
    capabilitiesMetric: '能力',
    operationsMetric: '唯讀操作',
    generatedMetric: '產物',
    generatedAt: '產生時間',
    sourceCommit: '來源提交',
    manifestVersion: 'Manifest 版本',
    manifestChip: 'Manifest',
    sdkDocsChip: 'SDK/文件',
    schemaCoverageChip: 'Schema 覆蓋',
    composedDryRunChip: '組合 dry-run',
    redactionChip: '遮罩',
    moduleFilter: '模組篩選',
    warningFilter: '警告篩選',
    withWarnings: '有警告',
    withoutWarnings: '無警告',
    warningsTitle: '警告',
    noWarnings: '無警告',
    generatedArtifactsTitle: '產物',
    sourceRegistryRefs: '來源註冊表引用',
    controllerSource: 'Controller 來源',
    openapiSource: 'OpenAPI 來源',
    operationSource: '操作來源',
    nativeRefs: '原生操作引用',
    permissionRequirements: '權限要求',
    scopeRequirements: 'Scope 要求',
    dryRunMode: 'Dry-run 模式',
    inputSchema: '輸入 Schema',
    dryRunPlan: 'Dry-run 計畫',
    redactedSampleOutput: '遮罩範例輸出',
    all: '全部',
    ...LABELS.zh_HANT,
  },
  ja: {
    eyebrow: 'TCRN Builder',
    title: 'Builder レジストリ',
    subtitle:
      'TCRN ネイティブ機能メタデータの読み取り専用ビューです。アプリビルダー、プラグインマーケット、コード実行、データベース編集ではありません。',
    readonly: '読み取り専用',
    refresh: '再読み込み',
    downloading: 'ダウンロード準備中',
    download: 'ダウンロード',
    downloadMenu: '生成物をダウンロード',
    openSwagger: 'Swagger を開く',
    openApiRegistry: 'API レジストリを開く',
    inspectDryRun: 'dry-run を表示',
    search: 'モジュールと機能を検索',
    module: 'モジュール',
    capability: '機能',
    scope: 'スコープ',
    operations: '操作',
    readOperations: '読み取り操作',
    artifacts: '生成物',
    stability: '安定性',
    permissions: '権限',
    lastVerified: '最終検証',
    actions: '操作',
    inspect: '表示',
    close: '閉じる',
    loadingTitle: 'Builder レジストリを読み込み中',
    loadingDescription: '生成済み manifest と読み取り専用生成物の状態を読んでいます。',
    emptyTitle: 'Builder manifest がありません',
    emptyDescription: '生成済み Builder レジストリ manifest を利用できません。',
    deniedTitle: 'AC 権限が必要です',
    errorTitle: 'Builder レジストリを利用できません',
    retry: '再試行',
    ready: '準備完了',
    warning: '警告',
    disabled: '無効',
    noPermission: '静的権限なし',
    detailTitle: 'Builder レジストリ詳細',
    sourceRefs: 'ソース参照',
    schemaRefs: 'Schema 参照',
    dynamicPermission: '動的権限は分類済みで、TCRN RBAC が引き続き強制します。',
    dryRunTitle: '合成 dry-run',
    dryRunNote: 'dry-run のみ。エディタ、スクリプト入力、SQL、デプロイ、公開、変更操作はありません。',
    unsupportedReasons: '未対応理由',
    downloads: 'ダウンロード',
    modulesMetric: 'モジュール',
    capabilitiesMetric: '機能',
    operationsMetric: '読み取り操作',
    generatedMetric: '生成物',
    generatedAt: '生成日時',
    sourceCommit: 'ソースコミット',
    manifestVersion: 'Manifest バージョン',
    manifestChip: 'Manifest',
    sdkDocsChip: 'SDK/ドキュメント',
    schemaCoverageChip: 'Schema カバレッジ',
    composedDryRunChip: '合成 dry-run',
    redactionChip: 'マスク',
    moduleFilter: 'モジュールフィルター',
    warningFilter: '警告フィルター',
    withWarnings: '警告あり',
    withoutWarnings: '警告なし',
    warningsTitle: '警告',
    noWarnings: '警告なし',
    generatedArtifactsTitle: '生成物',
    sourceRegistryRefs: 'ソースレジストリ参照',
    controllerSource: 'Controller ソース',
    openapiSource: 'OpenAPI ソース',
    operationSource: '操作ソース',
    nativeRefs: 'ネイティブ操作参照',
    permissionRequirements: '権限要件',
    scopeRequirements: 'スコープ要件',
    dryRunMode: 'Dry-run モード',
    inputSchema: '入力 Schema',
    dryRunPlan: 'Dry-run 計画',
    redactedSampleOutput: 'マスク済みサンプル出力',
    all: 'すべて',
    ...LABELS.ja,
  },
  ko: {
    eyebrow: 'TCRN Builder',
    title: 'Builder 레지스트리',
    subtitle:
      '읽기 전용 TCRN 네이티브 기능 메타데이터입니다. 앱 빌더, 플러그인 마켓, 코드 실행기 또는 데이터베이스 편집기가 아닙니다.',
    readonly: '읽기 전용',
    refresh: '읽기 새로고침',
    downloading: '다운로드 준비 중',
    download: '다운로드',
    downloadMenu: '생성물 다운로드',
    openSwagger: 'Swagger 열기',
    openApiRegistry: 'API 레지스트리 열기',
    inspectDryRun: 'dry-run 보기',
    search: '모듈 및 기능 검색',
    module: '모듈',
    capability: '기능',
    scope: '범위',
    operations: '작업',
    readOperations: '읽기 작업',
    artifacts: '생성물',
    stability: '안정성',
    permissions: '권한',
    lastVerified: '마지막 검증',
    actions: '작업',
    inspect: '보기',
    close: '닫기',
    loadingTitle: 'Builder 레지스트리 로드 중',
    loadingDescription: '생성된 manifest 및 읽기 전용 생성물 상태를 읽고 있습니다.',
    emptyTitle: 'Builder manifest 없음',
    emptyDescription: '생성된 Builder 레지스트리 manifest를 사용할 수 없습니다.',
    deniedTitle: 'AC 권한 필요',
    errorTitle: 'Builder 레지스트리를 사용할 수 없음',
    retry: '다시 시도',
    ready: '준비됨',
    warning: '경고',
    disabled: '비활성',
    noPermission: '정적 권한 없음',
    detailTitle: 'Builder 레지스트리 상세',
    sourceRefs: '소스 참조',
    schemaRefs: 'Schema 참조',
    dynamicPermission: '동적 권한은 분류되며 TCRN RBAC가 계속 강제합니다.',
    dryRunTitle: '구성 dry-run',
    dryRunNote: 'dry-run 전용입니다. 편집기, 스크립트 입력, SQL, 배포, 게시 또는 변경 작업은 없습니다.',
    unsupportedReasons: '미지원 사유',
    downloads: '다운로드',
    modulesMetric: '모듈',
    capabilitiesMetric: '기능',
    operationsMetric: '읽기 작업',
    generatedMetric: '생성물',
    generatedAt: '생성 시간',
    sourceCommit: '소스 커밋',
    manifestVersion: 'Manifest 버전',
    manifestChip: 'Manifest',
    sdkDocsChip: 'SDK/문서',
    schemaCoverageChip: 'Schema 적용 범위',
    composedDryRunChip: '구성 dry-run',
    redactionChip: '마스킹',
    moduleFilter: '모듈 필터',
    warningFilter: '경고 필터',
    withWarnings: '경고 있음',
    withoutWarnings: '경고 없음',
    warningsTitle: '경고',
    noWarnings: '경고 없음',
    generatedArtifactsTitle: '생성물',
    sourceRegistryRefs: '소스 레지스트리 참조',
    controllerSource: 'Controller 소스',
    openapiSource: 'OpenAPI 소스',
    operationSource: '작업 소스',
    nativeRefs: '네이티브 작업 참조',
    permissionRequirements: '권한 요구사항',
    scopeRequirements: '범위 요구사항',
    dryRunMode: 'Dry-run 모드',
    inputSchema: '입력 Schema',
    dryRunPlan: 'Dry-run 계획',
    redactedSampleOutput: '마스킹된 샘플 출력',
    all: '전체',
    ...LABELS.ko,
  },
  fr: {
    eyebrow: 'TCRN Builder',
    title: 'Registre Builder',
    subtitle:
      'Metadonnees de capacite TCRN natives en lecture seule. Ce n est pas un app builder, une marketplace plugin, un runner de code ou un editeur base de donnees.',
    readonly: 'Lecture seule',
    refresh: 'Actualiser',
    downloading: 'Preparation du telechargement',
    download: 'Telecharger',
    downloadMenu: 'Telecharger un artefact',
    openSwagger: 'Ouvrir Swagger',
    openApiRegistry: 'Ouvrir registre API',
    inspectDryRun: 'Voir dry-run',
    search: 'Rechercher modules et capacites',
    module: 'Module',
    capability: 'Capacite',
    scope: 'Portee',
    operations: 'Operations',
    readOperations: 'Operations lecture',
    artifacts: 'Artefacts',
    stability: 'Stabilite',
    permissions: 'Permissions',
    lastVerified: 'Derniere verification',
    actions: 'Actions',
    inspect: 'Inspecter',
    close: 'Fermer',
    loadingTitle: 'Chargement du registre Builder',
    loadingDescription: 'Lecture des manifests generes et des artefacts lecture seule.',
    emptyTitle: 'Aucun manifest Builder',
    emptyDescription: 'Les manifests Builder generes sont indisponibles.',
    deniedTitle: 'Permission AC requise',
    errorTitle: 'Registre Builder indisponible',
    retry: 'Reessayer',
    ready: 'Pret',
    warning: 'Avertissement',
    disabled: 'Desactive',
    noPermission: 'Aucune permission statique',
    detailTitle: 'Detail registre Builder',
    sourceRefs: 'Sources',
    schemaRefs: 'Schemas',
    dynamicPermission: 'La permission dynamique est classee et reste appliquee par TCRN RBAC.',
    dryRunTitle: 'Dry-run compose',
    dryRunNote: 'Dry-run seulement. Aucun editeur, script, SQL, deploiement, publication ou mutation.',
    unsupportedReasons: 'Raisons indisponibles',
    downloads: 'Telechargements',
    modulesMetric: 'Modules',
    capabilitiesMetric: 'Capacites',
    operationsMetric: 'Operations lecture',
    generatedMetric: 'Artefacts generes',
    generatedAt: 'Genere',
    sourceCommit: 'Source commit',
    manifestVersion: 'Version manifest',
    manifestChip: 'Manifest',
    sdkDocsChip: 'SDK/docs',
    schemaCoverageChip: 'Couverture schema',
    composedDryRunChip: 'Dry-run compose',
    redactionChip: 'Redaction',
    moduleFilter: 'Filtre module',
    warningFilter: 'Filtre avertissement',
    withWarnings: 'Avec avertissements',
    withoutWarnings: 'Sans avertissements',
    warningsTitle: 'Avertissements',
    noWarnings: 'Aucun avertissement',
    generatedArtifactsTitle: 'Artefacts generes',
    sourceRegistryRefs: 'References source',
    controllerSource: 'Source controller',
    openapiSource: 'Source OpenAPI',
    operationSource: 'Source operation',
    nativeRefs: 'References operations natives',
    permissionRequirements: 'Permissions requises',
    scopeRequirements: 'Portees requises',
    dryRunMode: 'Mode dry-run',
    inputSchema: 'Schema entree',
    dryRunPlan: 'Plan dry-run',
    redactedSampleOutput: 'Sortie exemple redactee',
    all: 'Tous',
    ...LABELS.fr,
  },
} as const;

export type BuilderRegistryCopy = (typeof COPY)['en'];
const COPY_RECORD = COPY as unknown as Record<SupportedUiLocale, BuilderRegistryCopy>;

export function useBuilderRegistryCopy(locale: SupportedUiLocale) {
  return resolveLocaleRecord(locale, COPY_RECORD) as BuilderRegistryCopy;
}
