import type { SupportedUiLocale } from '@tcrn/shared';

import { useUiLocale } from '@/platform/runtime/locale/locale-provider';
import { pickLocaleText } from '@/platform/runtime/locale/locale-text';

type CopyMap = Parameters<typeof pickLocaleText>[1];

const text = (locale: SupportedUiLocale, copy: CopyMap) => pickLocaleText(locale, copy);

export function useRuntimeFlagsCopy() {
  const { locale } = useUiLocale();
  const t = (copy: CopyMap) => text(locale, copy);

  return {
    locale,
    title: t({
      en: 'Runtime Flags',
      zh_HANS: '运行时开关',
      zh_HANT: '執行期開關',
      ja: 'ランタイムフラグ',
      ko: '런타임 플래그',
      fr: 'Flags runtime',
    }),
    description: t({
      en: 'Review registered rollout controls, kill switches, provider readiness, and safe evaluation previews.',
      zh_HANS: '查看已注册的灰度控制、Kill Switch、提供方就绪性与安全评估预览。',
      zh_HANT: '查看已註冊的灰度控制、Kill Switch、提供方就緒性與安全評估預覽。',
      ja: '登録済みのロールアウト制御、Kill Switch、プロバイダー準備状況、安全な評価プレビューを確認します。',
      ko: '등록된 롤아웃 제어, Kill Switch, 제공자 준비 상태, 안전 평가 미리보기를 검토합니다.',
      fr: 'Consultez les controles de rollout, kill switches, readiness fournisseur et apercus d evaluation surs.',
    }),
    actions: {
      refresh: t({
        en: 'Refresh',
        zh_HANS: '刷新',
        zh_HANT: '重新整理',
        ja: '更新',
        ko: '새로고침',
        fr: 'Actualiser',
      }),
      openProvider: t({
        en: 'Open provider setup',
        zh_HANS: '打开提供方配置',
        zh_HANT: '開啟提供方設定',
        ja: 'プロバイダー設定を開く',
        ko: '제공자 설정 열기',
        fr: 'Ouvrir le fournisseur',
      }),
      preview: t({
        en: 'Preview',
        zh_HANS: '预览',
        zh_HANT: '預覽',
        ja: 'プレビュー',
        ko: '미리보기',
        fr: 'Apercu',
      }),
      activate: t({
        en: 'Activate kill switch',
        zh_HANS: '启用 Kill Switch',
        zh_HANT: '啟用 Kill Switch',
        ja: 'Kill Switch を有効化',
        ko: 'Kill Switch 활성화',
        fr: 'Activer le kill switch',
      }),
      deactivate: t({
        en: 'Deactivate/Revert',
        zh_HANS: '停用/回滚',
        zh_HANT: '停用/回復',
        ja: '無効化/復旧',
        ko: '비활성화/되돌리기',
        fr: 'Desactiver/Revenir',
      }),
      cancel: t({
        en: 'Cancel',
        zh_HANS: '取消',
        zh_HANT: '取消',
        ja: 'キャンセル',
        ko: '취소',
        fr: 'Annuler',
      }),
      close: t({
        en: 'Close panel',
        zh_HANS: '关闭面板',
        zh_HANT: '關閉面板',
        ja: 'パネルを閉じる',
        ko: '패널 닫기',
        fr: 'Fermer le panneau',
      }),
      submit: t({
        en: 'Submit',
        zh_HANS: '提交',
        zh_HANT: '提交',
        ja: '送信',
        ko: '제출',
        fr: 'Envoyer',
      }),
    },
    labels: {
      platformControlPlane: t({
        en: 'Platform Control Plane',
        zh_HANS: '平台控制平面',
        zh_HANT: '平台控制平面',
        ja: 'プラットフォーム制御プレーン',
        ko: '플랫폼 제어 평면',
        fr: 'Plan de controle plateforme',
      }),
      registeredFlags: t({
        en: 'Registered flags',
        zh_HANS: '已注册开关',
        zh_HANT: '已註冊開關',
        ja: '登録済みフラグ',
        ko: '등록된 플래그',
        fr: 'Flags enregistres',
      }),
      activeSwitches: t({
        en: 'Active kill switches',
        zh_HANS: '活动 Kill Switch',
        zh_HANT: '作用中 Kill Switch',
        ja: '有効な Kill Switch',
        ko: '활성 Kill Switch',
        fr: 'Kill switches actifs',
      }),
      providerMode: t({
        en: 'Provider mode',
        zh_HANS: '提供方模式',
        zh_HANT: '提供方模式',
        ja: 'プロバイダーモード',
        ko: '제공자 모드',
        fr: 'Mode fournisseur',
      }),
      providerHealth: t({
        en: 'Provider health',
        zh_HANS: '提供方健康',
        zh_HANT: '提供方健康',
        ja: 'プロバイダーヘルス',
        ko: '제공자 상태',
        fr: 'Sante fournisseur',
      }),
      lastEvaluationFallback: t({
        en: 'Last evaluation fallback',
        zh_HANS: '最近评估回退',
        zh_HANT: '最近評估回退',
        ja: '直近評価フォールバック',
        ko: '최근 평가 폴백',
        fr: 'Dernier fallback',
      }),
      lastAuditEvent: t({
        en: 'Last audit event',
        zh_HANS: '最近审计事件',
        zh_HANT: '最近稽核事件',
        ja: '直近監査イベント',
        ko: '최근 감사 이벤트',
        fr: 'Dernier audit',
      }),
      fallback: t({
        en: 'Fallback',
        zh_HANS: '回退',
        zh_HANT: '回退',
        ja: 'フォールバック',
        ko: '폴백',
        fr: 'Fallback',
      }),
      approvedContextKeys: t({
        en: 'Approved context keys',
        zh_HANS: '已批准上下文键',
        zh_HANT: '已核准上下文鍵',
        ja: '承認済みコンテキストキー',
        ko: '승인된 컨텍스트 키',
        fr: 'Cles de contexte approuvees',
      }),
      redactedContext: t({
        en: 'Redacted context',
        zh_HANS: '已脱敏上下文',
        zh_HANT: '已脫敏上下文',
        ja: 'マスク済みコンテキスト',
        ko: '마스킹된 컨텍스트',
        fr: 'Contexte redacte',
      }),
      flagCode: t({
        en: 'Flag code',
        zh_HANS: '开关代码',
        zh_HANT: '開關代碼',
        ja: 'フラグコード',
        ko: '플래그 코드',
        fr: 'Code du flag',
      }),
      status: t({
        en: 'Status',
        zh_HANS: '状态',
        zh_HANT: '狀態',
        ja: 'ステータス',
        ko: '상태',
        fr: 'Statut',
      }),
      category: t({
        en: 'Category',
        zh_HANS: '类别',
        zh_HANT: '類別',
        ja: 'カテゴリ',
        ko: '분류',
        fr: 'Categorie',
      }),
      owner: t({
        en: 'Owner module',
        zh_HANS: '归属模块',
        zh_HANT: '歸屬模組',
        ja: '所有モジュール',
        ko: '소유 모듈',
        fr: 'Module proprietaire',
      }),
      defaultValue: t({
        en: 'Default',
        zh_HANS: '默认值',
        zh_HANT: '預設值',
        ja: 'デフォルト',
        ko: '기본값',
        fr: 'Defaut',
      }),
      failBehavior: t({
        en: 'Fail behavior',
        zh_HANS: '失败行为',
        zh_HANT: '失敗行為',
        ja: '失敗時動作',
        ko: '실패 동작',
        fr: 'Comportement en echec',
      }),
      providerMapping: t({
        en: 'Provider mapping',
        zh_HANS: '提供方映射',
        zh_HANT: '提供方映射',
        ja: 'プロバイダー対応',
        ko: '제공자 매핑',
        fr: 'Mapping fournisseur',
      }),
      lastUpdated: t({
        en: 'Last updated',
        zh_HANS: '最近更新',
        zh_HANT: '最近更新',
        ja: '最終更新',
        ko: '최근 업데이트',
        fr: 'Derniere MAJ',
      }),
      provider: t({
        en: 'Provider readiness',
        zh_HANS: '提供方就绪性',
        zh_HANT: '提供方就緒性',
        ja: 'プロバイダー準備状況',
        ko: '제공자 준비 상태',
        fr: 'Readiness fournisseur',
      }),
      actions: t({
        en: 'Actions',
        zh_HANS: '操作',
        zh_HANT: '操作',
        ja: '操作',
        ko: '작업',
        fr: 'Actions',
      }),
      value: t({ en: 'Value', zh_HANS: '取值', zh_HANT: '取值', ja: '値', ko: '값', fr: 'Valeur' }),
      source: t({
        en: 'Source',
        zh_HANS: '来源',
        zh_HANT: '來源',
        ja: 'ソース',
        ko: '소스',
        fr: 'Source',
      }),
      actor: t({
        en: 'Actor',
        zh_HANS: '操作者',
        zh_HANT: '操作者',
        ja: '実行者',
        ko: '작업자',
        fr: 'Acteur',
      }),
      sso: t({ en: 'SSO', zh_HANS: 'SSO', zh_HANT: 'SSO', ja: 'SSO', ko: 'SSO', fr: 'SSO' }),
      endpoint: t({
        en: 'Endpoint',
        zh_HANS: '端点',
        zh_HANT: '端點',
        ja: 'エンドポイント',
        ko: '엔드포인트',
        fr: 'Endpoint',
      }),
      configured: t({
        en: 'configured',
        zh_HANS: '已配置',
        zh_HANT: '已設定',
        ja: '設定済み',
        ko: '구성됨',
        fr: 'configure',
      }),
      notConfigured: t({
        en: 'not configured',
        zh_HANS: '未配置',
        zh_HANT: '未設定',
        ja: '未設定',
        ko: '구성 안 됨',
        fr: 'non configure',
      }),
      reason: t({
        en: 'Reason',
        zh_HANS: '原因',
        zh_HANT: '原因',
        ja: '理由',
        ko: '사유',
        fr: 'Raison',
      }),
      expiry: t({
        en: 'Expiry',
        zh_HANS: '过期时间',
        zh_HANT: '到期時間',
        ja: '期限',
        ko: '만료',
        fr: 'Expiration',
      }),
      affectedBehavior: t({
        en: 'Affected behavior',
        zh_HANS: '影响行为',
        zh_HANT: '影響行為',
        ja: '影響される動作',
        ko: '영향받는 동작',
        fr: 'Comportement affecte',
      }),
      rollback: t({
        en: 'Rollback instruction',
        zh_HANS: '回滚说明',
        zh_HANT: '回復說明',
        ja: '復旧手順',
        ko: '롤백 지시',
        fr: 'Instruction de retour',
      }),
      confirm: t({
        en: 'I confirm this is an emergency runtime control.',
        zh_HANS: '我确认这是紧急运行时控制。',
        zh_HANT: '我確認這是緊急執行期控制。',
        ja: 'これは緊急ランタイム制御であることを確認します。',
        ko: '긴급 런타임 제어임을 확인합니다.',
        fr: 'Je confirme qu il s agit d un controle runtime urgent.',
      }),
      killSwitchConfirmation: t({
        en: 'Kill switch confirmation',
        zh_HANS: 'Kill Switch 确认',
        zh_HANT: 'Kill Switch 確認',
        ja: 'Kill Switch 確認',
        ko: 'Kill Switch 확인',
        fr: 'Confirmation du kill switch',
      }),
      impactPreview: t({
        en: 'Impact preview',
        zh_HANS: '影响预览',
        zh_HANT: '影響預覽',
        ja: '影響プレビュー',
        ko: '영향 미리보기',
        fr: 'Apercu d impact',
      }),
      requiredBeforeActivation: t({
        en: 'Required before activation',
        zh_HANS: '启用前必填',
        zh_HANT: '啟用前必填',
        ja: '有効化前に必須',
        ko: '활성화 전에 필수',
        fr: 'Requis avant activation',
      }),
    },
    states: {
      loading: t({
        en: 'Loading runtime flags',
        zh_HANS: '正在加载运行时开关',
        zh_HANT: '正在載入執行期開關',
        ja: 'ランタイムフラグを読み込み中',
        ko: '런타임 플래그 로드 중',
        fr: 'Chargement des flags runtime',
      }),
      error: t({
        en: 'Runtime flags could not load',
        zh_HANS: '运行时开关加载失败',
        zh_HANT: '執行期開關載入失敗',
        ja: '読み込みに失敗しました',
        ko: '로드 실패',
        fr: 'Chargement impossible',
      }),
      empty: t({
        en: 'No registered flags',
        zh_HANS: '暂无已注册开关',
        zh_HANT: '暫無已註冊開關',
        ja: '登録済みフラグなし',
        ko: '등록된 플래그 없음',
        fr: 'Aucun flag enregistre',
      }),
      noActiveSwitches: t({
        en: 'No active kill switches',
        zh_HANS: '暂无活动 Kill Switch',
        zh_HANT: '暫無作用中 Kill Switch',
        ja: '有効な Kill Switch はありません',
        ko: '활성 Kill Switch 없음',
        fr: 'Aucun kill switch actif',
      }),
      permissionDenied: t({
        en: 'Permission denied',
        zh_HANS: '权限不足',
        zh_HANT: '權限不足',
        ja: '権限がありません',
        ko: '권한 없음',
        fr: 'Permission refusee',
      }),
      saved: t({
        en: 'Kill switch saved',
        zh_HANS: 'Kill Switch 已保存',
        zh_HANT: 'Kill Switch 已儲存',
        ja: 'Kill Switch を保存しました',
        ko: 'Kill Switch 저장됨',
        fr: 'Kill switch enregistre',
      }),
      previewReady: t({
        en: 'Evaluation preview ready',
        zh_HANS: '评估预览已就绪',
        zh_HANT: '評估預覽已就緒',
        ja: '評価プレビューの準備完了',
        ko: '평가 미리보기 준비됨',
        fr: 'Apercu d evaluation pret',
      }),
      blockedContext: t({
        en: 'Unsafe context blocked',
        zh_HANS: '不安全上下文已阻止',
        zh_HANT: '不安全上下文已阻止',
        ja: '安全でないコンテキストをブロック',
        ko: '안전하지 않은 컨텍스트 차단',
        fr: 'Contexte non sur bloque',
      }),
    },
  };
}
