import { type SupportedUiLocale } from '@tcrn/shared';

import { resolveLocaleRecord } from '@/platform/runtime/locale/locale-text';

const COPY = {
  en: {
    title: 'API Gateway Readiness',
    subtitle: 'Read-only APISIX/Kong route policy readiness derived from the API Registry.',
    refresh: 'Refresh',
    readonly: 'Read-only',
    loadingTitle: 'Loading gateway readiness',
    loadingDescription: 'Reading generated route policy, renders, and safety checks.',
    deniedTitle: 'AC permission required',
    errorTitle: 'Gateway readiness unavailable',
    retry: 'Retry',
    openRegistry: 'Open API Registry',
    openSwagger: 'Open Swagger',
    downloadPolicy: 'Download route policy',
    downloadApisix: 'Download APISIX render',
    downloadKong: 'Download Kong render',
    openRunbook: 'Open runbook',
    activeProxy: 'Active proxy',
    routePolicy: 'Route policy',
    renderStatus: 'Render status',
    trustedHeaders: 'Trusted headers',
    rateCors: 'Rate limit / CORS',
    canaryRollback: 'Canary / rollback',
    verification: 'Verification',
    routeCount: 'Routes',
    provider: 'Provider',
    operation: 'Operation',
    method: 'Method',
    path: 'Path',
    auth: 'Auth',
    cutover: 'Cutover',
    notApplied: 'Not applied',
    noRoutes: 'No generated gateway policy',
    noRoutesDescription: 'The API Registry currently has no gateway-eligible routes.',
    close: 'Close',
    states: {
      clean_ready: 'Clean readiness',
      empty_no_policy: 'No generated gateway policy',
      render_failed: 'Render failed',
      drift_or_parity_warning: 'Drift or parity warning',
      trusted_header_warning: 'Trusted header warning',
      canary_rollback_unavailable: 'Canary rollback unavailable',
      stale_verification: 'Stale verification',
    },
  },
  zh_HANS: {
    title: 'API 网关就绪',
    subtitle: '从 API 注册表派生的只读 APISIX/Kong 路由策略就绪状态。',
    refresh: '刷新',
    readonly: '只读',
    loadingTitle: '正在加载网关就绪状态',
    loadingDescription: '正在读取生成的路由策略、渲染结果与安全检查。',
    deniedTitle: '需要 AC 权限',
    errorTitle: '网关就绪状态不可用',
    retry: '重试',
    openRegistry: '打开 API 注册表',
    openSwagger: '打开 Swagger',
    downloadPolicy: '下载路由策略',
    downloadApisix: '下载 APISIX 渲染',
    downloadKong: '下载 Kong 渲染',
    openRunbook: '打开运行手册',
    activeProxy: '当前代理',
    routePolicy: '路由策略',
    renderStatus: '渲染状态',
    trustedHeaders: '可信头策略',
    rateCors: '限流 / CORS',
    canaryRollback: '灰度 / 回滚',
    verification: '验收结果',
    routeCount: '路由',
    provider: '提供方',
    operation: '操作',
    method: '方法',
    path: '路径',
    auth: '认证',
    cutover: '切流',
    notApplied: '未应用',
    noRoutes: '暂无生成的网关策略',
    noRoutesDescription: 'API 注册表当前没有可进入网关就绪渲染的路由。',
    close: '关闭',
    states: {
      clean_ready: '就绪干净',
      empty_no_policy: '暂无生成的网关策略',
      render_failed: '渲染失败',
      drift_or_parity_warning: '漂移或一致性警告',
      trusted_header_warning: '可信头警告',
      canary_rollback_unavailable: '灰度回滚不可用',
      stale_verification: '验收结果已过期',
    },
  },
  zh_HANT: {
    title: 'API 閘道就緒',
    subtitle: '從 API 註冊表衍生的唯讀 APISIX/Kong 路由策略就緒狀態。',
    refresh: '重新整理',
    readonly: '唯讀',
    loadingTitle: '正在載入閘道就緒狀態',
    loadingDescription: '正在讀取產生的路由策略、渲染結果與安全檢查。',
    deniedTitle: '需要 AC 權限',
    errorTitle: '閘道就緒狀態不可用',
    retry: '重試',
    openRegistry: '開啟 API 註冊表',
    openSwagger: '開啟 Swagger',
    downloadPolicy: '下載路由策略',
    downloadApisix: '下載 APISIX 渲染',
    downloadKong: '下載 Kong 渲染',
    openRunbook: '開啟執行手冊',
    activeProxy: '目前代理',
    routePolicy: '路由策略',
    renderStatus: '渲染狀態',
    trustedHeaders: '可信標頭策略',
    rateCors: '限流 / CORS',
    canaryRollback: '灰度 / 回滾',
    verification: '驗收結果',
    routeCount: '路由',
    provider: '提供方',
    operation: '操作',
    method: '方法',
    path: '路徑',
    auth: '認證',
    cutover: '切流',
    notApplied: '未套用',
    noRoutes: '尚無產生的閘道策略',
    noRoutesDescription: 'API 註冊表目前沒有可進入閘道就緒渲染的路由。',
    close: '關閉',
    states: {
      clean_ready: '就緒乾淨',
      empty_no_policy: '尚無產生的閘道策略',
      render_failed: '渲染失敗',
      drift_or_parity_warning: '漂移或一致性警告',
      trusted_header_warning: '可信標頭警告',
      canary_rollback_unavailable: '灰度回滾不可用',
      stale_verification: '驗收結果已過期',
    },
  },
  ja: {
    title: 'API ゲートウェイ準備',
    subtitle: 'API レジストリから派生した読み取り専用の APISIX/Kong ルート準備状況。',
    refresh: '更新',
    readonly: '読み取り専用',
    loadingTitle: 'ゲートウェイ準備状況を読み込み中',
    loadingDescription: '生成済みルートポリシー、レンダー、安全チェックを読み込んでいます。',
    deniedTitle: 'AC 権限が必要です',
    errorTitle: 'ゲートウェイ準備状況を利用できません',
    retry: '再試行',
    openRegistry: 'API レジストリを開く',
    openSwagger: 'Swagger を開く',
    downloadPolicy: 'ルートポリシーをダウンロード',
    downloadApisix: 'APISIX レンダーをダウンロード',
    downloadKong: 'Kong レンダーをダウンロード',
    openRunbook: 'ランブックを開く',
    activeProxy: '有効なプロキシ',
    routePolicy: 'ルートポリシー',
    renderStatus: 'レンダー状態',
    trustedHeaders: '信頼ヘッダー',
    rateCors: 'レート制限 / CORS',
    canaryRollback: 'カナリア / ロールバック',
    verification: '検証',
    routeCount: 'ルート',
    provider: 'プロバイダー',
    operation: '操作',
    method: 'メソッド',
    path: 'パス',
    auth: '認証',
    cutover: '切替',
    notApplied: '未適用',
    noRoutes: '生成されたゲートウェイポリシーはありません',
    noRoutesDescription: 'API レジストリにゲートウェイ対象ルートがありません。',
    close: '閉じる',
    states: {
      clean_ready: '準備正常',
      empty_no_policy: '生成されたゲートウェイポリシーはありません',
      render_failed: 'レンダー失敗',
      drift_or_parity_warning: 'ドリフトまたはパリティ警告',
      trusted_header_warning: '信頼ヘッダー警告',
      canary_rollback_unavailable: 'カナリア/ロールバック不可',
      stale_verification: '検証が古い',
    },
  },
  ko: {
    title: 'API 게이트웨이 준비',
    subtitle: 'API 레지스트리에서 파생된 읽기 전용 APISIX/Kong 라우트 준비 상태입니다.',
    refresh: '새로고침',
    readonly: '읽기 전용',
    loadingTitle: '게이트웨이 준비 상태 로드 중',
    loadingDescription: '생성된 라우트 정책, 렌더, 안전 점검을 읽고 있습니다.',
    deniedTitle: 'AC 권한 필요',
    errorTitle: '게이트웨이 준비 상태를 사용할 수 없음',
    retry: '다시 시도',
    openRegistry: 'API 레지스트리 열기',
    openSwagger: 'Swagger 열기',
    downloadPolicy: '라우트 정책 다운로드',
    downloadApisix: 'APISIX 렌더 다운로드',
    downloadKong: 'Kong 렌더 다운로드',
    openRunbook: '런북 열기',
    activeProxy: '활성 프록시',
    routePolicy: '라우트 정책',
    renderStatus: '렌더 상태',
    trustedHeaders: '신뢰 헤더',
    rateCors: '레이트 제한 / CORS',
    canaryRollback: '카나리 / 롤백',
    verification: '검증',
    routeCount: '라우트',
    provider: '제공자',
    operation: '작업',
    method: '메서드',
    path: '경로',
    auth: '인증',
    cutover: '전환',
    notApplied: '미적용',
    noRoutes: '생성된 게이트웨이 정책 없음',
    noRoutesDescription: 'API 레지스트리에 게이트웨이 대상 라우트가 없습니다.',
    close: '닫기',
    states: {
      clean_ready: '준비 정상',
      empty_no_policy: '생성된 게이트웨이 정책 없음',
      render_failed: '렌더 실패',
      drift_or_parity_warning: '드리프트 또는 패리티 경고',
      trusted_header_warning: '신뢰 헤더 경고',
      canary_rollback_unavailable: '카나리 롤백 불가',
      stale_verification: '검증 오래됨',
    },
  },
  fr: {
    title: 'Preparation passerelle API',
    subtitle: 'Etat APISIX/Kong en lecture seule derive du registre API.',
    refresh: 'Actualiser',
    readonly: 'Lecture seule',
    loadingTitle: 'Chargement de la preparation passerelle',
    loadingDescription: 'Lecture de la politique de routes, des rendus et des controles.',
    deniedTitle: 'Permission AC requise',
    errorTitle: 'Preparation passerelle indisponible',
    retry: 'Reessayer',
    openRegistry: 'Ouvrir le registre API',
    openSwagger: 'Ouvrir Swagger',
    downloadPolicy: 'Telecharger la politique',
    downloadApisix: 'Telecharger le rendu APISIX',
    downloadKong: 'Telecharger le rendu Kong',
    openRunbook: 'Ouvrir le runbook',
    activeProxy: 'Proxy actif',
    routePolicy: 'Politique de routes',
    renderStatus: 'Etat du rendu',
    trustedHeaders: 'En-tetes fiables',
    rateCors: 'Limite / CORS',
    canaryRollback: 'Canary / rollback',
    verification: 'Verification',
    routeCount: 'Routes',
    provider: 'Fournisseur',
    operation: 'Operation',
    method: 'Methode',
    path: 'Chemin',
    auth: 'Auth',
    cutover: 'Bascule',
    notApplied: 'Non applique',
    noRoutes: 'Aucune politique passerelle generee',
    noRoutesDescription: 'Le registre API ne contient aucune route eligible.',
    close: 'Fermer',
    states: {
      clean_ready: 'Preparation propre',
      empty_no_policy: 'Aucune politique passerelle generee',
      render_failed: 'Echec du rendu',
      drift_or_parity_warning: 'Avertissement de derive ou parite',
      trusted_header_warning: 'Avertissement en-tetes fiables',
      canary_rollback_unavailable: 'Canary rollback indisponible',
      stale_verification: 'Verification perimee',
    },
  },
} as const;

export type ApiGatewayReadinessCopy = (typeof COPY)['en'];
const COPY_RECORD = COPY as unknown as Record<SupportedUiLocale, ApiGatewayReadinessCopy>;

export function useApiGatewayReadinessCopy(locale: SupportedUiLocale) {
  return resolveLocaleRecord(locale, COPY_RECORD) as ApiGatewayReadinessCopy;
}
