// © 2026 月球厨师莱恩 (TPMOONCHEFRYAN) – PolyForm Noncommercial License

import type { HomepageComponentType } from '../types/homepage/schema';
import {
  PUBLIC_PRESENCE_COMPONENT_VISUAL_SUPPORT,
  PUBLIC_PRESENCE_DOCUMENT_SCHEMA_VERSION,
  PUBLIC_PRESENCE_DOCUMENT_STATES,
  PUBLIC_PRESENCE_FALLBACK_POLICIES,
  PUBLIC_PRESENCE_FAN_ACTION_SLOTS,
  PUBLIC_PRESENCE_FIELD_PROVENANCES,
  PUBLIC_PRESENCE_HASH_ALGORITHMS,
  PUBLIC_PRESENCE_MEDIA_CATEGORIES,
  PUBLIC_PRESENCE_NOTE_KINDS,
  PUBLIC_PRESENCE_PHASE_VISIBILITIES,
  PUBLIC_PRESENCE_PROJECTION_MODES,
  PUBLIC_PRESENCE_REGISTRY_VERSION,
  PUBLIC_PRESENCE_REVEAL_PHASES,
  PUBLIC_PRESENCE_SAFETY_POLICY_VERSION,
  PUBLIC_PRESENCE_SOURCE_POLICIES,
  PUBLIC_PRESENCE_STAGE_SECTION_KINDS,
  PUBLIC_PRESENCE_TEMPLATE_IDS,
  PUBLIC_PRESENCE_UNKNOWN_FIELD_POLICIES,
  PUBLIC_PRESENCE_URL_CATEGORIES,
  PUBLIC_PRESENCE_WORKFLOW_EVENT_TYPES,
  type PublicPresenceComponentDefinition,
  type PublicPresenceCollectionOperationDefinition,
  type PublicPresenceContentHashPolicy,
  type PublicPresenceFieldDefinition,
  type PublicPresenceSafetyPolicy,
  type PublicPresenceStageSectionDefinition,
  type PublicPresenceTemplateDefinition,
} from './types';

const createFieldDefinition = (
  input: PublicPresenceFieldDefinition,
): PublicPresenceFieldDefinition => input;

const createCollectionOperationDefinition = (
  input: PublicPresenceCollectionOperationDefinition,
): PublicPresenceCollectionOperationDefinition => input;

const createComponentFieldDefinitions = (prefix: string) => ({
  displayName: createFieldDefinition({
    fieldKey: 'displayName',
    jsonPath: `${prefix}.displayName`,
    valueType: 'string',
    required: 'optional',
    provenance: [...PUBLIC_PRESENCE_FIELD_PROVENANCES],
    visualEditable: false,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'lockedSourceOwned',
  }),
  bio: createFieldDefinition({
    fieldKey: 'bio',
    jsonPath: `${prefix}.bio`,
    valueType: 'string',
    required: 'optional',
    provenance: ['publicPresence', 'override', 'locked', 'sourceOwned'],
    visualEditable: false,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'lockedSourceOwned',
  }),
  avatarUrl: createFieldDefinition({
    fieldKey: 'avatarUrl',
    jsonPath: `${prefix}.avatarUrl`,
    valueType: 'url',
    required: 'optional',
    provenance: ['inherited', 'override', 'publicPresence', 'locked', 'sourceOwned'],
    visualEditable: false,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'mediaAssetUrl',
    mediaCategory: 'profileAsset',
    validationRules: ['safeMediaUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  platforms: createFieldDefinition({
    fieldKey: 'platforms',
    jsonPath: `${prefix}.platforms`,
    valueType: 'objectArray',
    required: 'always',
    provenance: ['publicPresence', 'locked', 'sourceOwned'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    validationRules: ['atLeastOnePlatform', 'safePlatformUrls'],
    fallbackPolicy: 'safePlaceholder',
  }),
  images: createFieldDefinition({
    fieldKey: 'images',
    jsonPath: `${prefix}.images`,
    valueType: 'objectArray',
    required: 'optional',
    provenance: ['publicPresence', 'locked', 'sourceOwned'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    mediaCategory: 'galleryImage',
    validationRules: ['safeGalleryImages'],
    fallbackPolicy: 'safePlaceholder',
  }),
  videoUrl: createFieldDefinition({
    fieldKey: 'videoUrl',
    jsonPath: `${prefix}.videoUrl`,
    valueType: 'url',
    required: 'always',
    provenance: ['publicPresence', 'locked', 'sourceOwned'],
    visualEditable: false,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'embedUrl',
    validationRules: ['safeEmbedUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  contentHtml: createFieldDefinition({
    fieldKey: 'contentHtml',
    jsonPath: `${prefix}.contentHtml`,
    valueType: 'richText',
    required: 'always',
    provenance: ['publicPresence', 'locked', 'sourceOwned'],
    visualEditable: false,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'htmlContent',
    validationRules: ['noRawHtmlExecution'],
    fallbackPolicy: 'stripField',
  }),
  url: createFieldDefinition({
    fieldKey: 'url',
    jsonPath: `${prefix}.url`,
    valueType: 'url',
    required: 'always',
    provenance: ['publicPresence', 'locked', 'sourceOwned'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    urlCategory: 'fanActionUrl',
    validationRules: ['safeFanActionUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  streamUrl: createFieldDefinition({
    fieldKey: 'streamUrl',
    jsonPath: `${prefix}.streamUrl`,
    valueType: 'url',
    required: 'optional',
    provenance: ['publicPresence', 'locked', 'sourceOwned'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'streamUrl',
    validationRules: ['safeStreamUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  embedValue: createFieldDefinition({
    fieldKey: 'embedValue',
    jsonPath: `${prefix}.embedValue`,
    valueType: 'url',
    required: 'optional',
    provenance: ['locked', 'sourceOwned'],
    visualEditable: false,
    aiEditable: false,
    sourceOnly: true,
    urlCategory: 'embedUrl',
    validationRules: ['safeEmbedUrl'],
    fallbackPolicy: 'lockedSourceOwned',
  }),
}) as const;

const componentField = createComponentFieldDefinitions('props');

const sectionField = {
  displayName: createFieldDefinition({
    fieldKey: 'displayName',
    jsonPath: 'fields.displayName',
    valueType: 'string',
    required: 'always',
    provenance: ['inherited', 'override', 'publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'safePlaceholder',
  }),
  teaserName: createFieldDefinition({
    fieldKey: 'teaserName',
    jsonPath: 'fields.teaserName',
    valueType: 'string',
    required: 'conditional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    phaseVisibility: ['teaser', 'countdown', 'preRevealHold'],
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'safePlaceholder',
  }),
  revealName: createFieldDefinition({
    fieldKey: 'revealName',
    jsonPath: 'fields.revealName',
    valueType: 'string',
    required: 'conditional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    phaseVisibility: ['revealed', 'liveLaunch', 'postLaunch', 'expiredFallback'],
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'safePlaceholder',
  }),
  headline: createFieldDefinition({
    fieldKey: 'headline',
    jsonPath: 'fields.headline',
    valueType: 'string',
    required: 'optional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'safePlaceholder',
  }),
  intro: createFieldDefinition({
    fieldKey: 'intro',
    jsonPath: 'fields.intro',
    valueType: 'string',
    required: 'optional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'safePlaceholder',
  }),
  avatarUrl: createFieldDefinition({
    fieldKey: 'avatarUrl',
    jsonPath: 'fields.avatarUrl',
    valueType: 'url',
    required: 'optional',
    provenance: ['inherited', 'override', 'publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'mediaAssetUrl',
    mediaCategory: 'profileAsset',
    validationRules: ['safeMediaUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  heroMediaUrl: createFieldDefinition({
    fieldKey: 'heroMediaUrl',
    jsonPath: 'fields.heroMediaUrl',
    valueType: 'url',
    required: 'optional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'mediaAssetUrl',
    mediaCategory: 'heroMedia',
    validationRules: ['safeMediaUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  primaryCtaLabel: createFieldDefinition({
    fieldKey: 'primaryCtaLabel',
    jsonPath: 'fields.primaryCtaLabel',
    valueType: 'string',
    required: 'optional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    validationRules: ['nonEmpty'],
    fallbackPolicy: 'safePlaceholder',
  }),
  primaryCtaUrl: createFieldDefinition({
    fieldKey: 'primaryCtaUrl',
    jsonPath: 'fields.primaryCtaUrl',
    valueType: 'url',
    required: 'optional',
    provenance: ['publicPresence', 'override', 'locked'],
    visualEditable: true,
    aiEditable: true,
    sourceOnly: false,
    urlCategory: 'fanActionUrl',
    validationRules: ['safeFanActionUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  phase: createFieldDefinition({
    fieldKey: 'phase',
    jsonPath: 'fields.phase',
    valueType: 'enum',
    required: 'always',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['knownPhase'],
    fallbackPolicy: 'safePlaceholder',
  }),
  revealAtUtc: createFieldDefinition({
    fieldKey: 'revealAtUtc',
    jsonPath: 'fields.revealAtUtc',
    valueType: 'datetime',
    required: 'always',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['isoUtcDateTime'],
    fallbackPolicy: 'safePlaceholder',
  }),
  timezone: createFieldDefinition({
    fieldKey: 'timezone',
    jsonPath: 'fields.timezone',
    valueType: 'timezone',
    required: 'always',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['ianaTimeZone'],
    fallbackPolicy: 'safePlaceholder',
  }),
  streamUrl: createFieldDefinition({
    fieldKey: 'streamUrl',
    jsonPath: 'fields.streamUrl',
    valueType: 'url',
    required: 'optional',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'streamUrl',
    validationRules: ['safeStreamUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  launchUrl: createFieldDefinition({
    fieldKey: 'launchUrl',
    jsonPath: 'fields.launchUrl',
    valueType: 'url',
    required: 'optional',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    urlCategory: 'launchUrl',
    validationRules: ['safeLaunchUrl'],
    fallbackPolicy: 'safePlaceholder',
  }),
  notes: createFieldDefinition({
    fieldKey: 'notes',
    jsonPath: 'fields.notes',
    valueType: 'objectArray',
    required: 'optional',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['structuredAgencyNotes'],
    fallbackPolicy: 'safePlaceholder',
  }),
  actions: createFieldDefinition({
    fieldKey: 'actions',
    jsonPath: 'fields.actions',
    valueType: 'objectArray',
    required: 'optional',
    provenance: ['publicPresence', 'locked'],
    visualEditable: true,
    aiEditable: false,
    sourceOnly: false,
    validationRules: ['typedFanActions'],
    fallbackPolicy: 'safePlaceholder',
  }),
} as const;

export const PUBLIC_PRESENCE_TEMPLATE_DEFINITIONS: Record<
  (typeof PUBLIC_PRESENCE_TEMPLATE_IDS)[number],
  PublicPresenceTemplateDefinition
> = {
  activeTalentHub: {
    templateId: 'activeTalentHub',
    registryVersion: PUBLIC_PRESENCE_REGISTRY_VERSION,
    label: 'Active Talent Hub',
    useCase: 'Always-on official public presence for an active talent.',
    requiredSections: ['firstEncounter', 'officialChannels'],
    recommendedSections: [
      'currentLaunchAction',
      'stageSchedule',
      'fanInteraction',
      'fanActions',
      'agencyNotes',
      'goodsSupport',
      'officialUpdatesFeed',
    ],
    optionalSections: [
      'teaserRevealMedia',
      'milestoneUnlocks',
      'countdownReveal',
    ],
    lockedSections: [],
    defaultSectionOrder: [
      'firstEncounter',
      'currentLaunchAction',
      'officialChannels',
      'stageSchedule',
      'fanInteraction',
      'fanActions',
      'agencyNotes',
      'goodsSupport',
      'officialUpdatesFeed',
      'milestoneUnlocks',
    ],
    personaKitFields: ['accentTone', 'campaignLabel', 'tagline'],
    validationRules: ['requiresOfficialChannels', 'requiresFirstEncounter'],
    policyReferences: ['publicPresenceSafetyPolicy', 'validationRegistry'],
  },
  debutReveal: {
    templateId: 'debutReveal',
    registryVersion: PUBLIC_PRESENCE_REGISTRY_VERSION,
    label: 'Debut / Reveal',
    useCase: 'Campaign-safe debut or reveal workflow with teaser-safe public output.',
    requiredSections: ['firstEncounter', 'countdownReveal'],
    recommendedSections: [
      'teaserRevealMedia',
      'officialChannels',
      'currentLaunchAction',
      'fanInteraction',
      'fanActions',
      'agencyNotes',
      'goodsSupport',
      'officialUpdatesFeed',
      'milestoneUnlocks',
    ],
    optionalSections: ['stageSchedule'],
    lockedSections: [],
    defaultSectionOrder: [
      'firstEncounter',
      'countdownReveal',
      'teaserRevealMedia',
      'currentLaunchAction',
      'officialChannels',
      'fanInteraction',
      'fanActions',
      'agencyNotes',
      'goodsSupport',
      'officialUpdatesFeed',
      'milestoneUnlocks',
      'stageSchedule',
    ],
    personaKitFields: ['accentTone', 'campaignLabel', 'tagline'],
    validationRules: ['requiresCountdownReveal', 'requiresRevealSafeNaming'],
    policyReferences: ['publicPresenceSafetyPolicy', 'validationRegistry'],
  },
};

export const PUBLIC_PRESENCE_STAGE_SECTION_DEFINITIONS: Record<
  (typeof PUBLIC_PRESENCE_STAGE_SECTION_KINDS)[number],
  PublicPresenceStageSectionDefinition
> = {
  firstEncounter: {
    kind: 'firstEncounter',
    purpose: 'Own the first viewport contract and inherited/override public identity composition.',
    allowedComponents: [],
    slotRules: ['stageSectionOwnedFieldsOnly'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['requiresDisplayName', 'safeHeroMedia', 'safePrimaryCta'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [
      sectionField.displayName,
      sectionField.teaserName,
      sectionField.revealName,
      sectionField.headline,
      sectionField.intro,
      sectionField.avatarUrl,
      sectionField.heroMediaUrl,
      sectionField.primaryCtaLabel,
      sectionField.primaryCtaUrl,
    ],
  },
  currentLaunchAction: {
    kind: 'currentLaunchAction',
    purpose: 'Highlight the current official CTA or launch action.',
    allowedComponents: ['LinkButton', 'LiveStatus'],
    slotRules: ['singlePrimaryAction'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['safeActionUrls'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [],
  },
  countdownReveal: {
    kind: 'countdownReveal',
    purpose: 'Own reveal timing, safe teaser/reveal names, and server-authoritative launch gating.',
    allowedComponents: [],
    slotRules: ['stageSectionOwnedFieldsOnly'],
    phaseVisibility: [...PUBLIC_PRESENCE_REVEAL_PHASES],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['requiresRevealAtUtc', 'requiresTimezone', 'safeRevealUrls'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [
      sectionField.phase,
      sectionField.revealAtUtc,
      sectionField.timezone,
      sectionField.teaserName,
      sectionField.revealName,
      sectionField.streamUrl,
      sectionField.launchUrl,
    ],
  },
  officialChannels: {
    kind: 'officialChannels',
    purpose: 'Provide validated official social and channel destinations.',
    allowedComponents: ['SocialLinks'],
    collectionOperations: [
      createCollectionOperationDefinition({
        addLabel: 'addChannel',
        canAdd: true,
        canRemove: true,
        canReorder: true,
        collectionKey: 'platforms',
        itemLabel: 'channel',
        minItems: 0,
        removeLabel: 'removeChannel',
        reorderLabel: 'reorderChannels',
      }),
    ],
    slotRules: ['officialLinksOnly'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['safeOfficialChannelUrls'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [],
  },
  stageSchedule: {
    kind: 'stageSchedule',
    purpose: 'Expose a bounded official schedule contract.',
    allowedComponents: ['Schedule'],
    collectionOperations: [
      createCollectionOperationDefinition({
        addLabel: 'addEvent',
        canAdd: true,
        canRemove: true,
        canReorder: true,
        collectionKey: 'events',
        itemLabel: 'scheduleEntry',
        minItems: 0,
        removeLabel: 'removeEvent',
        reorderLabel: 'reorderEvents',
      }),
    ],
    slotRules: ['boundedScheduleOnly'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['structuredSchedule'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [],
  },
  teaserRevealMedia: {
    kind: 'teaserRevealMedia',
    purpose: 'Hold reveal-safe teaser or reveal media with explicit phase behavior.',
    allowedComponents: ['ImageGallery', 'VideoEmbed'],
    slotRules: ['mediaOnly'],
    phaseVisibility: [...PUBLIC_PRESENCE_REVEAL_PHASES],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['safeRevealMedia'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [],
  },
  goodsSupport: {
    kind: 'goodsSupport',
    purpose: 'Bound goods and support destinations to explicit slots and validated URLs.',
    allowedComponents: ['LinkButton'],
    collectionOperations: [
      createCollectionOperationDefinition({
        addLabel: 'addGoodsLink',
        canAdd: true,
        canRemove: true,
        canReorder: true,
        collectionKey: 'components',
        itemLabel: 'goodsLink',
        minItems: 0,
        removeLabel: 'removeGoodsLink',
        reorderLabel: 'reorderGoodsLinks',
      }),
    ],
    slotRules: ['validatedGoodsSupportActions'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['safeGoodsSupportUrls'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [],
  },
  fanInteraction: {
    kind: 'fanInteraction',
    purpose: 'Expose bounded fan interaction surfaces such as Marshmallow.',
    allowedComponents: ['MarshmallowWidget'],
    slotRules: ['internalInteractionSurfaceOnly'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['internalRouteOnlyInteractionSurface'],
    fallbackBehavior: 'safePlaceholder',
    fieldDefinitions: [],
  },
  agencyNotes: {
    kind: 'agencyNotes',
    purpose: 'Publish structured notes rather than raw executable rich text.',
    allowedComponents: [],
    slotRules: ['stageSectionOwnedFieldsOnly'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['structuredAgencyNotes'],
    fallbackBehavior: 'safePlaceholder',
    collectionOperations: [
      createCollectionOperationDefinition({
        addLabel: 'addNote',
        canAdd: true,
        canRemove: true,
        canReorder: true,
        collectionKey: 'notes',
        itemLabel: 'agencyNote',
        minItems: 0,
        removeLabel: 'removeNote',
        reorderLabel: 'reorderNotes',
      }),
    ],
    fieldDefinitions: [sectionField.notes],
  },
  fanActions: {
    kind: 'fanActions',
    purpose: 'Bind typed fan action slots to safe URLs and labels.',
    allowedComponents: [],
    slotRules: ['typedFanActionSlots'],
    phaseVisibility: ['always'],
    editabilityState: 'validEditable',
    sourcePolicy: 'registryOwned',
    validationRules: ['typedFanActions'],
    fallbackBehavior: 'safePlaceholder',
    collectionOperations: [
      createCollectionOperationDefinition({
        addLabel: 'addAction',
        canAdd: true,
        canRemove: true,
        canReorder: true,
        collectionKey: 'actions',
        itemLabel: 'fanAction',
        minItems: 0,
        removeLabel: 'removeAction',
        reorderLabel: 'reorderActions',
      }),
    ],
    fieldDefinitions: [sectionField.actions],
  },
  milestoneUnlocks: {
    kind: 'milestoneUnlocks',
    purpose: 'Reserve a bounded future unlock surface without opening arbitrary widgets.',
    allowedComponents: ['Divider', 'Spacer'],
    slotRules: ['lockedUntilFutureSlice'],
    phaseVisibility: ['always'],
    editabilityState: 'validLocked',
    sourcePolicy: 'preserveLocked',
    validationRules: ['futureLockedSection'],
    fallbackBehavior: 'lockedSourceOwned',
    fieldDefinitions: [],
  },
  officialUpdatesFeed: {
    kind: 'officialUpdatesFeed',
    purpose: 'Preserve official update or feed-like compatibility content in a locked state.',
    allowedComponents: ['BilibiliDynamic'],
    slotRules: ['lockedFeedCompatibilityOnly'],
    phaseVisibility: ['always'],
    editabilityState: 'validLocked',
    sourcePolicy: 'preserveLocked',
    validationRules: ['compatibilityFeedOnly'],
    fallbackBehavior: 'lockedSourceOwned',
    fieldDefinitions: [],
  },
};

const createComponentDefinition = (
  input: PublicPresenceComponentDefinition,
): PublicPresenceComponentDefinition => input;

export const PUBLIC_PRESENCE_COMPONENT_DEFINITIONS: Record<
  HomepageComponentType,
  PublicPresenceComponentDefinition
> = {
  ProfileCard: createComponentDefinition({
    componentType: 'ProfileCard',
    rendererSupport: true,
    visualSupport: 'locked',
    sourcePolicy: 'preserveLocked',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'ProfileCard',
    defaultProps: {
      displayName: '',
      bio: '',
      avatarUrl: '',
      avatarShape: 'circle',
      nameFontSize: 'large',
      bioMaxLines: 3,
    },
    fieldDefinitions: [
      componentField.displayName,
      componentField.bio,
      componentField.avatarUrl,
      createFieldDefinition({
        fieldKey: 'avatarShape',
        jsonPath: 'props.avatarShape',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownAvatarShape'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'nameFontSize',
        jsonPath: 'props.nameFontSize',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownNameFontSize'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'bioMaxLines',
        jsonPath: 'props.bioMaxLines',
        valueType: 'integer',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['positiveInteger'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['media.profileAsset'],
    aiPatchAllowlist: [],
  }),
  SocialLinks: createComponentDefinition({
    componentType: 'SocialLinks',
    rendererSupport: true,
    visualSupport: 'supported',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'structured',
    propsSchemaKey: 'SocialLinks',
    defaultProps: {
      platforms: [],
      style: 'pill',
      layout: 'horizontal',
      iconSize: 'medium',
    },
    fieldDefinitions: [
      componentField.platforms,
      createFieldDefinition({
        fieldKey: 'style',
        jsonPath: 'props.style',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: true,
        sourceOnly: false,
        validationRules: ['knownStyle'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'layout',
        jsonPath: 'props.layout',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: true,
        sourceOnly: false,
        validationRules: ['knownLayout'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'iconSize',
        jsonPath: 'props.iconSize',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: true,
        sourceOnly: false,
        validationRules: ['knownIconSize'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['url.officialChannelUrl'],
    aiPatchAllowlist: ['platforms', 'style', 'layout', 'iconSize'],
  }),
  ImageGallery: createComponentDefinition({
    componentType: 'ImageGallery',
    rendererSupport: true,
    visualSupport: 'supported',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'structured',
    propsSchemaKey: 'ImageGallery',
    defaultProps: {
      images: [],
      layoutMode: 'grid',
      columns: 3,
      gap: 'medium',
      showCaptions: true,
    },
    fieldDefinitions: [
      componentField.images,
      createFieldDefinition({
        fieldKey: 'layoutMode',
        jsonPath: 'props.layoutMode',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['knownLayoutMode'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'columns',
        jsonPath: 'props.columns',
        valueType: 'integer',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['galleryColumnsRange'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'showCaptions',
        jsonPath: 'props.showCaptions',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['boolean'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['media.galleryImage'],
    aiPatchAllowlist: [],
  }),
  VideoEmbed: createComponentDefinition({
    componentType: 'VideoEmbed',
    rendererSupport: true,
    visualSupport: 'limited',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'VideoEmbed',
    defaultProps: {
      videoUrl: '',
      aspectRatio: '16:9',
      autoplay: false,
      showControls: true,
      title: '',
    },
    fieldDefinitions: [
      componentField.videoUrl,
      createFieldDefinition({
        fieldKey: 'aspectRatio',
        jsonPath: 'props.aspectRatio',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['knownAspectRatio'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'autoplay',
        jsonPath: 'props.autoplay',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['boolean'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'showControls',
        jsonPath: 'props.showControls',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['boolean'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'title',
        jsonPath: 'props.title',
        valueType: 'string',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['url.embedUrl', 'embed.youtube'],
    aiPatchAllowlist: [],
  }),
  RichText: createComponentDefinition({
    componentType: 'RichText',
    rendererSupport: true,
    visualSupport: 'locked',
    sourcePolicy: 'preserveLocked',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'RichText',
    defaultProps: {
      contentHtml: '',
      textAlign: 'left',
    },
    fieldDefinitions: [
      componentField.contentHtml,
      createFieldDefinition({
        fieldKey: 'textAlign',
        jsonPath: 'props.textAlign',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownTextAlign'],
        fallbackPolicy: 'stripField',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['html.content'],
    aiPatchAllowlist: [],
  }),
  LinkButton: createComponentDefinition({
    componentType: 'LinkButton',
    rendererSupport: true,
    visualSupport: 'supported',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'structured',
    propsSchemaKey: 'LinkButton',
    defaultProps: {
      label: '',
      url: '',
      style: 'primary',
      fullWidth: false,
    },
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'label',
        jsonPath: 'props.label',
        valueType: 'string',
        required: 'always',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: true,
        sourceOnly: false,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'safePlaceholder',
      }),
      componentField.url,
      createFieldDefinition({
        fieldKey: 'style',
        jsonPath: 'props.style',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: true,
        sourceOnly: false,
        validationRules: ['knownButtonStyle'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'fullWidth',
        jsonPath: 'props.fullWidth',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['boolean'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['url.fanActionUrl'],
    aiPatchAllowlist: ['label', 'url', 'style'],
  }),
  MarshmallowWidget: createComponentDefinition({
    componentType: 'MarshmallowWidget',
    rendererSupport: true,
    visualSupport: 'limited',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'MarshmallowWidget',
    defaultProps: {
      displayMode: 'compact',
      showRecentCount: 3,
      showSubmitButton: true,
    },
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'displayMode',
        jsonPath: 'props.displayMode',
        valueType: 'enum',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['knownDisplayMode'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'showRecentCount',
        jsonPath: 'props.showRecentCount',
        valueType: 'integer',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['nonNegativeInteger'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'showSubmitButton',
        jsonPath: 'props.showSubmitButton',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['boolean'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['internal.marshmallow'],
    aiPatchAllowlist: [],
  }),
  Schedule: createComponentDefinition({
    componentType: 'Schedule',
    rendererSupport: true,
    visualSupport: 'supported',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'structured',
    propsSchemaKey: 'Schedule',
    defaultProps: {
      title: '',
      weekOf: '',
      events: [],
    },
    collectionOperations: [
      createCollectionOperationDefinition({
        addLabel: 'addEvent',
        canAdd: true,
        canRemove: true,
        canReorder: true,
        collectionKey: 'events',
        itemLabel: 'scheduleEntry',
        minItems: 0,
        removeLabel: 'removeEvent',
        reorderLabel: 'reorderEvents',
      }),
    ],
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'title',
        jsonPath: 'props.title',
        valueType: 'string',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'weekOf',
        jsonPath: 'props.weekOf',
        valueType: 'string',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['dateLikeString'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'events',
        jsonPath: 'props.events',
        valueType: 'objectArray',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['structuredScheduleEvents'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: [],
    aiPatchAllowlist: [],
  }),
  MusicPlayer: createComponentDefinition({
    componentType: 'MusicPlayer',
    rendererSupport: true,
    visualSupport: 'locked',
    sourcePolicy: 'sourceOnly',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'MusicPlayer',
    defaultProps: {
      platform: 'spotify',
      embedValue: '',
      title: '',
      artist: '',
    },
    fieldDefinitions: [
      componentField.embedValue,
      createFieldDefinition({
        fieldKey: 'platform',
        jsonPath: 'props.platform',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownMusicPlatform'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'title',
        jsonPath: 'props.title',
        valueType: 'string',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'artist',
        jsonPath: 'props.artist',
        valueType: 'string',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
    ],
    unknownFieldPolicy: 'preserveSourceOwned',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['url.embedUrl'],
    aiPatchAllowlist: [],
  }),
  LiveStatus: createComponentDefinition({
    componentType: 'LiveStatus',
    rendererSupport: true,
    visualSupport: 'supported',
    sourcePolicy: 'registryOwned',
    publicProjectionMode: 'structured',
    propsSchemaKey: 'LiveStatus',
    defaultProps: {
      platform: 'youtube',
      channelName: '',
      streamUrl: '',
      isLive: false,
      viewers: '',
      title: '',
    },
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'platform',
        jsonPath: 'props.platform',
        valueType: 'enum',
        required: 'always',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['knownLivePlatform'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'channelName',
        jsonPath: 'props.channelName',
        valueType: 'string',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'safePlaceholder',
      }),
      componentField.streamUrl,
      createFieldDefinition({
        fieldKey: 'isLive',
        jsonPath: 'props.isLive',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['boolean'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'viewers',
        jsonPath: 'props.viewers',
        valueType: 'string',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'safePlaceholder',
      }),
      createFieldDefinition({
        fieldKey: 'title',
        jsonPath: 'props.title',
        valueType: 'string',
        required: 'optional',
        provenance: ['publicPresence', 'locked'],
        visualEditable: true,
        aiEditable: false,
        sourceOnly: false,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'safePlaceholder',
      }),
    ],
    unknownFieldPolicy: 'preserveLocked',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: ['url.streamUrl'],
    aiPatchAllowlist: [],
  }),
  Divider: createComponentDefinition({
    componentType: 'Divider',
    rendererSupport: true,
    visualSupport: 'locked',
    sourcePolicy: 'sourceOnly',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'Divider',
    defaultProps: {
      style: 'solid',
      spacing: 'medium',
    },
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'style',
        jsonPath: 'props.style',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownDividerStyle'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'spacing',
        jsonPath: 'props.spacing',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownSpacing'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
    ],
    unknownFieldPolicy: 'preserveSourceOwned',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: [],
    aiPatchAllowlist: [],
  }),
  Spacer: createComponentDefinition({
    componentType: 'Spacer',
    rendererSupport: true,
    visualSupport: 'locked',
    sourcePolicy: 'sourceOnly',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'Spacer',
    defaultProps: {
      height: 'medium',
    },
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'height',
        jsonPath: 'props.height',
        valueType: 'enum',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['knownSpacerHeight'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
    ],
    unknownFieldPolicy: 'preserveSourceOwned',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: [],
    aiPatchAllowlist: [],
  }),
  BilibiliDynamic: createComponentDefinition({
    componentType: 'BilibiliDynamic',
    rendererSupport: true,
    visualSupport: 'locked',
    sourcePolicy: 'sourceOnly',
    publicProjectionMode: 'safeFallback',
    propsSchemaKey: 'BilibiliDynamic',
    defaultProps: {
      uid: '',
      title: '',
      maxItems: 5,
      filterType: 'all',
      cardStyle: 'standard',
      refreshInterval: 0,
      showHeader: true,
    },
    fieldDefinitions: [
      createFieldDefinition({
        fieldKey: 'uid',
        jsonPath: 'props.uid',
        valueType: 'string',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'title',
        jsonPath: 'props.title',
        valueType: 'string',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'maxItems',
        jsonPath: 'props.maxItems',
        valueType: 'integer',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['positiveInteger'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'filterType',
        jsonPath: 'props.filterType',
        valueType: 'string',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'cardStyle',
        jsonPath: 'props.cardStyle',
        valueType: 'string',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonEmpty'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'refreshInterval',
        jsonPath: 'props.refreshInterval',
        valueType: 'integer',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['nonNegativeInteger'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
      createFieldDefinition({
        fieldKey: 'showHeader',
        jsonPath: 'props.showHeader',
        valueType: 'boolean',
        required: 'optional',
        provenance: ['locked', 'sourceOwned'],
        visualEditable: false,
        aiEditable: false,
        sourceOnly: true,
        validationRules: ['boolean'],
        fallbackPolicy: 'lockedSourceOwned',
      }),
    ],
    unknownFieldPolicy: 'preserveSourceOwned',
    lockedSourceOwnedPolicy: 'lockedSourceOwned',
    safetyPolicyReferences: [],
    aiPatchAllowlist: [],
  }),
};

const urlPolicy = {
  officialChannelUrl: {
    category: 'officialChannelUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Official channels must resolve to public HTTPS destinations.',
  },
  fanActionUrl: {
    category: 'fanActionUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Fan actions must use public HTTPS URLs.',
  },
  goodsUrl: {
    category: 'goodsUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Goods destinations must use public HTTPS URLs.',
  },
  supportUrl: {
    category: 'supportUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Support destinations must use public HTTPS URLs.',
  },
  streamUrl: {
    category: 'streamUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Stream destinations must use public HTTPS URLs.',
  },
  launchUrl: {
    category: 'launchUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Launch actions must use public HTTPS URLs.',
  },
  mediaAssetUrl: {
    category: 'mediaAssetUrl',
    allowedProtocols: ['https:'],
    allowInternalPath: true,
    blockPrivateHosts: true,
    description: 'Media URLs should resolve to managed public assets or HTTPS URLs.',
  },
  embedUrl: {
    category: 'embedUrl',
    allowedProtocols: ['https:'],
    allowListedHosts: [
      'youtube.com',
      'www.youtube.com',
      'm.youtube.com',
      'youtu.be',
    ],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Only allowlisted embed providers are valid in MVP.',
  },
  htmlContent: {
    category: 'htmlContent',
    allowedProtocols: [],
    allowInternalPath: false,
    blockPrivateHosts: true,
    description: 'Raw executable HTML is not allowed in MVP.',
  },
} as const satisfies PublicPresenceSafetyPolicy['urlPolicies'];

const mediaPolicy = {
  heroMedia: {
    category: 'heroMedia',
    allowedProtocols: ['https:'],
    allowInternalPath: true,
    preferManagedAssets: true,
    description: 'Hero media should prefer managed assets or HTTPS URLs.',
  },
  profileAsset: {
    category: 'profileAsset',
    allowedProtocols: ['https:'],
    allowInternalPath: true,
    preferManagedAssets: true,
    description: 'Profile assets should prefer managed assets or HTTPS URLs.',
  },
  galleryImage: {
    category: 'galleryImage',
    allowedProtocols: ['https:'],
    allowInternalPath: true,
    preferManagedAssets: true,
    description: 'Gallery images should prefer managed assets or HTTPS URLs.',
  },
  metadataOgImage: {
    category: 'metadataOgImage',
    allowedProtocols: ['https:'],
    allowInternalPath: true,
    preferManagedAssets: true,
    description: 'Metadata OG images should resolve to managed assets or HTTPS URLs.',
  },
} as const satisfies PublicPresenceSafetyPolicy['mediaPolicies'];

export const PUBLIC_PRESENCE_SAFETY_POLICY: PublicPresenceSafetyPolicy = {
  version: PUBLIC_PRESENCE_SAFETY_POLICY_VERSION,
  urlPolicies: urlPolicy,
  mediaPolicies: mediaPolicy,
  embedPolicies: {
    youtube: {
      providerId: 'youtube',
      acceptedHosts: [
        'youtube.com',
        'www.youtube.com',
        'm.youtube.com',
        'youtu.be',
      ],
      allowYouTubeWatchUrl: true,
      fallbackBehavior: 'safePlaceholder',
      aiEditable: false,
    },
  },
  htmlRules: {
    forbiddenPatterns: [
      '<script',
      '<style',
      '<iframe',
      'javascript:',
      ' on',
      'style=',
    ],
    fallbackBehavior: 'stripField',
  },
};

export const PUBLIC_PRESENCE_CONTENT_HASH_POLICY: PublicPresenceContentHashPolicy = {
  algorithm: 'sha256',
  canonicalization: 'stableJson',
  coveredDocumentFields: [
    'schemaVersion',
    'templateId',
    'sections',
    'metadata',
    'personaKit',
  ],
  excludesDerivedFields: [
    'validationSnapshots',
    'workflowState',
    'workflowEvents',
    'projectionHash',
  ],
};

export const PUBLIC_PRESENCE_REGISTRY_METADATA = {
  componentVisualSupport: [...PUBLIC_PRESENCE_COMPONENT_VISUAL_SUPPORT],
  contentHashPolicy: PUBLIC_PRESENCE_CONTENT_HASH_POLICY,
  documentStates: [...PUBLIC_PRESENCE_DOCUMENT_STATES],
  documentSchemaVersion: PUBLIC_PRESENCE_DOCUMENT_SCHEMA_VERSION,
  fanActionSlots: [...PUBLIC_PRESENCE_FAN_ACTION_SLOTS],
  fallbackPolicies: [...PUBLIC_PRESENCE_FALLBACK_POLICIES],
  hashAlgorithms: [...PUBLIC_PRESENCE_HASH_ALGORITHMS],
  mediaCategories: [...PUBLIC_PRESENCE_MEDIA_CATEGORIES],
  noteKinds: [...PUBLIC_PRESENCE_NOTE_KINDS],
  phaseVisibilities: [...PUBLIC_PRESENCE_PHASE_VISIBILITIES],
  projectionModes: [...PUBLIC_PRESENCE_PROJECTION_MODES],
  registryVersion: PUBLIC_PRESENCE_REGISTRY_VERSION,
  revealPhases: [...PUBLIC_PRESENCE_REVEAL_PHASES],
  safetyPolicyVersion: PUBLIC_PRESENCE_SAFETY_POLICY_VERSION,
  sourcePolicies: [...PUBLIC_PRESENCE_SOURCE_POLICIES],
  stageSectionKinds: [...PUBLIC_PRESENCE_STAGE_SECTION_KINDS],
  templateIds: [...PUBLIC_PRESENCE_TEMPLATE_IDS],
  unknownFieldPolicies: [...PUBLIC_PRESENCE_UNKNOWN_FIELD_POLICIES],
  urlCategories: [...PUBLIC_PRESENCE_URL_CATEGORIES],
  workflowEventTypes: [...PUBLIC_PRESENCE_WORKFLOW_EVENT_TYPES],
} as const;
