import { useUiLocale } from '@/platform/runtime/locale/locale-provider';
import { pickLocaleText } from '@/platform/runtime/locale/locale-text';

type CopyMap = Parameters<typeof pickLocaleText>[1];

const familyCopy: Record<string, CopyMap> = {
  identity_provider: {
    en: 'Identity',
    zh_HANS: '身份',
    zh_HANT: '身份',
    ja: 'ID',
    ko: 'ID',
    fr: 'Identité',
  },
  observability_console: {
    en: 'Observability',
    zh_HANS: '可观测性',
    zh_HANT: '可觀測性',
    ja: '可観測性',
    ko: '관측',
    fr: 'Observabilité',
  },
  runtime_flags: {
    en: 'Runtime Flags',
    zh_HANS: '运行时开关',
    zh_HANT: '執行期開關',
    ja: 'ランタイムフラグ',
    ko: '런타임 플래그',
    fr: 'Flags runtime',
  },
  webhook_delivery: {
    en: 'Webhook Delivery',
    zh_HANS: 'Webhook 投递',
    zh_HANT: 'Webhook 投遞',
    ja: 'Webhook 配信',
    ko: '웹훅 전달',
    fr: 'Livraison webhook',
  },
  event_backbone: {
    en: 'Event Backbone',
    zh_HANS: '事件骨干',
    zh_HANT: '事件骨幹',
    ja: 'イベント基盤',
    ko: '이벤트 백본',
    fr: 'Backbone événementiel',
  },
  api_gateway: {
    en: 'API Gateway',
    zh_HANS: 'API 网关',
    zh_HANT: 'API 閘道',
    ja: 'API ゲートウェイ',
    ko: 'API 게이트웨이',
    fr: 'Passerelle API',
  },
  internal_tooling: {
    en: 'Internal Tools',
    zh_HANS: '内部工具',
    zh_HANT: '內部工具',
    ja: '内部ツール',
    ko: '내부 도구',
    fr: 'Outils internes',
  },
  developer_portal: {
    en: 'Developer Portal',
    zh_HANS: '开发者门户',
    zh_HANT: '開發者入口',
    ja: '開発者ポータル',
    ko: '개발자 포털',
    fr: 'Portail développeur',
  },
  external_authorization: {
    en: 'External AuthZ',
    zh_HANS: '外部授权',
    zh_HANT: '外部授權',
    ja: '外部認可',
    ko: '외부 권한',
    fr: 'Autorisation externe',
  },
};

export function usePlatformToolConnectionsCopy() {
  const { locale } = useUiLocale();
  const text = (copy: CopyMap) => pickLocaleText(locale, copy);

  return {
    locale,
    text,
    title: text({
      en: 'Platform Tool Connections',
      zh_HANS: '平台工具连接',
      zh_HANT: '平台工具連線',
      ja: 'プラットフォームツール接続',
      ko: '플랫폼 도구 연결',
      fr: 'Connexions aux outils plateforme',
    }),
    statusLine: text({
      en: 'AC platform boundary active.',
      zh_HANS: 'AC 平台边界已生效。',
      zh_HANT: 'AC 平台邊界已生效。',
      ja: 'AC プラットフォーム境界が有効です。',
      ko: 'AC 플랫폼 경계가 활성화되었습니다.',
      fr: 'Frontière plateforme AC active.',
    }),
    filters: {
      environment: text({
        en: 'Environment',
        zh_HANS: '环境',
        zh_HANT: '環境',
        ja: '環境',
        ko: '환경',
        fr: 'Environnement',
      }),
      family: text({
        en: 'Family',
        zh_HANS: '家族',
        zh_HANT: '家族',
        ja: 'ファミリー',
        ko: '제품군',
        fr: 'Famille',
      }),
      allFamilies: text({
        en: 'All families',
        zh_HANS: '全部家族',
        zh_HANT: '全部家族',
        ja: 'すべて',
        ko: '전체',
        fr: 'Toutes',
      }),
    },
    columns: {
      tool: text({ en: 'Tool', zh_HANS: '工具', zh_HANT: '工具', ja: 'ツール', ko: '도구', fr: 'Outil' }),
      family: text({ en: 'Family', zh_HANS: '家族', zh_HANT: '家族', ja: 'ファミリー', ko: '제품군', fr: 'Famille' }),
      connection: text({ en: 'Connection', zh_HANS: '连接', zh_HANT: '連線', ja: '接続', ko: '연결', fr: 'Connexion' }),
      health: text({ en: 'Health', zh_HANS: '健康', zh_HANT: '健康', ja: 'ヘルス', ko: '상태', fr: 'Santé' }),
      sso: text({ en: 'SSO', zh_HANS: 'SSO', zh_HANT: 'SSO', ja: 'SSO', ko: 'SSO', fr: 'SSO' }),
      actions: text({ en: 'Actions', zh_HANS: '操作', zh_HANT: '操作', ja: '操作', ko: '작업', fr: 'Actions' }),
    },
    actions: {
      refresh: text({ en: 'Refresh', zh_HANS: '刷新', zh_HANT: '重新整理', ja: '更新', ko: '새로고침', fr: 'Actualiser' }),
      inspect: text({ en: 'Inspect', zh_HANS: '查看', zh_HANT: '檢視', ja: '詳細', ko: '검토', fr: 'Inspecter' }),
      configure: text({ en: 'Configure', zh_HANS: '配置', zh_HANT: '設定', ja: '設定', ko: '구성', fr: 'Configurer' }),
      runCheck: text({ en: 'Run check', zh_HANS: '运行检查', zh_HANT: '執行檢查', ja: 'チェック', ko: '점검 실행', fr: 'Vérifier' }),
      open: text({ en: 'Open', zh_HANS: '打开', zh_HANT: '開啟', ja: '開く', ko: '열기', fr: 'Ouvrir' }),
      save: text({ en: 'Save', zh_HANS: '保存', zh_HANT: '儲存', ja: '保存', ko: '저장', fr: 'Enregistrer' }),
      cancel: text({ en: 'Cancel', zh_HANS: '取消', zh_HANT: '取消', ja: 'キャンセル', ko: '취소', fr: 'Annuler' }),
      close: text({ en: 'Close panel', zh_HANS: '关闭面板', zh_HANT: '關閉面板', ja: 'パネルを閉じる', ko: '패널 닫기', fr: 'Fermer le panneau' }),
      disabledOpen: text({
        en: 'Link unavailable',
        zh_HANS: '链接不可用',
        zh_HANT: '連結不可用',
        ja: 'リンク不可',
        ko: '링크 사용 불가',
        fr: 'Lien indisponible',
      }),
      openBlockedReason: text({
        en: 'Open is disabled until the connection is enabled and a backend-approved deep link is available.',
        zh_HANS: '仅当连接已启用且后端批准深链时，打开操作才可用。',
        zh_HANT: '只有連線已啟用且後端核准深層連結時，開啟操作才可用。',
        ja: '接続が有効で、バックエンド承認済みの深リンクがある場合のみ開けます。',
        ko: '연결이 활성화되고 백엔드 승인 딥링크가 있을 때만 열 수 있습니다.',
        fr: 'L’ouverture reste désactivée tant que la connexion n’est pas activée et qu’un lien profond approuvé par le backend n’existe pas.',
      }),
    },
    fields: {
      endpointUrl: text({ en: 'Endpoint URL', zh_HANS: '端点 URL', zh_HANT: '端點 URL', ja: 'エンドポイント URL', ko: '엔드포인트 URL', fr: 'URL endpoint' }),
      internalServiceUrl: text({ en: 'Internal service URL', zh_HANS: '内部服务 URL', zh_HANT: '內部服務 URL', ja: '内部サービス URL', ko: '내부 서비스 URL', fr: 'URL service interne' }),
      namespace: text({ en: 'Namespace', zh_HANS: '命名空间', zh_HANT: '命名空間', ja: '名前空間', ko: '네임스페이스', fr: 'Namespace' }),
      serviceName: text({ en: 'Service name', zh_HANS: '服务名', zh_HANT: '服務名', ja: 'サービス名', ko: '서비스 이름', fr: 'Nom du service' }),
      deploymentMode: text({ en: 'Deployment mode', zh_HANS: '部署模式', zh_HANT: '部署模式', ja: 'デプロイモード', ko: '배포 모드', fr: 'Mode de déploiement' }),
      localDevMode: text({ en: 'Local-dev mode', zh_HANS: '本地开发模式', zh_HANT: '本機開發模式', ja: 'ローカル開発モード', ko: '로컬 개발 모드', fr: 'Mode local-dev' }),
      enabled: text({ en: 'Enabled', zh_HANS: '启用', zh_HANT: '啟用', ja: '有効', ko: '사용', fr: 'Activé' }),
      secretRef: text({ en: 'Client secret reference', zh_HANS: '客户端密钥引用', zh_HANT: '用戶端密鑰引用', ja: 'クライアントシークレット参照', ko: '클라이언트 시크릿 참조', fr: 'Référence secret client' }),
    },
    states: {
      loading: text({ en: 'Loading platform tools', zh_HANS: '正在加载平台工具', zh_HANT: '正在載入平台工具', ja: '読み込み中', ko: '플랫폼 도구 로드 중', fr: 'Chargement des outils' }),
      empty: text({ en: 'No platform tools', zh_HANS: '暂无平台工具', zh_HANT: '暫無平台工具', ja: 'ツールがありません', ko: '도구 없음', fr: 'Aucun outil' }),
      error: text({ en: 'Platform tools could not load', zh_HANS: '平台工具加载失败', zh_HANT: '平台工具載入失敗', ja: '読み込み失敗', ko: '로드 실패', fr: 'Chargement impossible' }),
      saved: text({ en: 'Connection saved', zh_HANS: '连接已保存', zh_HANT: '連線已儲存', ja: '接続を保存しました', ko: '연결 저장됨', fr: 'Connexion enregistrée' }),
      denied: text({ en: 'Deep link denied', zh_HANS: '深链已拒绝', zh_HANT: '深層連結已拒絕', ja: '深リンクは拒否されました', ko: '딥링크 거부됨', fr: 'Lien profond refusé' }),
    },
    readinessReasons: {
      notConfigured: text({
        en: 'Not configured: no enabled connection metadata exists for this AC environment.',
        zh_HANS: '未配置：此 AC 环境没有已启用的连接元数据。',
        zh_HANT: '未設定：此 AC 環境沒有已啟用的連線中繼資料。',
        ja: '未設定: この AC 環境には有効な接続メタデータがありません。',
        ko: '미구성: 이 AC 환경에는 활성화된 연결 메타데이터가 없습니다.',
        fr: 'Non configuré : aucune métadonnée de connexion activée n’existe pour cet environnement AC.',
      }),
      healthUnknown: text({
        en: 'Health unknown: no successful health proof has been recorded.',
        zh_HANS: '健康状态未知：尚未记录成功的健康检查证明。',
        zh_HANT: '健康狀態未知：尚未記錄成功的健康檢查證明。',
        ja: 'ヘルス不明: 成功したヘルス証跡はまだ記録されていません。',
        ko: '상태 알 수 없음: 성공한 상태 점검 증거가 아직 기록되지 않았습니다.',
        fr: 'Santé inconnue : aucune preuve de santé réussie n’a été enregistrée.',
      }),
      ssoBlocked: text({
        en: 'SSO blocked: human-console access remains fail-closed until real SSO readiness is proven.',
        zh_HANS: 'SSO 已阻止：在证明真实 SSO 就绪前，人工控制台访问保持失败关闭。',
        zh_HANT: 'SSO 已阻擋：在證明真實 SSO 就緒前，人員主控台存取保持失敗關閉。',
        ja: 'SSO ブロック: 実際の SSO 準備状況が証明されるまで、人向けコンソールアクセスは fail-closed です。',
        ko: 'SSO 차단: 실제 SSO 준비가 증명될 때까지 콘솔 접근은 fail-closed 상태입니다.',
        fr: 'SSO bloqué : l’accès console humain reste fail-closed tant que la préparation SSO réelle n’est pas prouvée.',
      }),
      ssoNotApplicable: text({
        en: 'SSO not applicable for this tool state.',
        zh_HANS: '此工具状态不适用 SSO。',
        zh_HANT: '此工具狀態不適用 SSO。',
        ja: 'このツール状態では SSO は対象外です。',
        ko: '이 도구 상태에는 SSO가 적용되지 않습니다.',
        fr: 'SSO non applicable pour cet état d’outil.',
      }),
      localStubbed: text({
        en: 'Local-dev stub only: useful for AC readiness proof, not production tool availability.',
        zh_HANS: '仅本地开发 stub：可用于 AC 就绪证明，不代表生产工具可用。',
        zh_HANT: '僅本機開發 stub：可用於 AC 就緒證明，不代表生產工具可用。',
        ja: 'ローカル開発 stub のみ: AC 準備状況の証明用であり、本番ツール可用性ではありません。',
        ko: '로컬 개발 stub 전용: AC 준비 상태 증명용이며 프로덕션 도구 가용성이 아닙니다.',
        fr: 'Stub local-dev seulement : utile pour la preuve AC, pas pour la disponibilité production.',
      }),
      ready: text({
        en: 'Ready only reflects backend readiness metadata for this connection.',
        zh_HANS: 'Ready 仅表示此连接的后端就绪元数据。',
        zh_HANT: 'Ready 僅表示此連線的後端就緒中繼資料。',
        ja: 'Ready はこの接続のバックエンド準備メタデータのみを示します。',
        ko: 'Ready는 이 연결의 백엔드 준비 메타데이터만 의미합니다.',
        fr: 'Ready reflète uniquement les métadonnées de préparation backend de cette connexion.',
      }),
    },
    eventBackbone: {
      title: text({ en: 'Event backbone readiness', zh_HANS: '事件骨干就绪状态', zh_HANT: '事件骨幹就緒狀態', ja: 'イベント基盤の準備状態', ko: '이벤트 백본 준비 상태', fr: 'Préparation backbone événementiel' }),
      loading: text({ en: 'Loading event backbone readiness', zh_HANS: '正在加载事件骨干就绪状态', zh_HANT: '正在載入事件骨幹就緒狀態', ja: '準備状態を読み込み中', ko: '이벤트 백본 준비 상태 로드 중', fr: 'Chargement de la préparation' }),
      error: text({ en: 'Event backbone readiness could not load', zh_HANS: '事件骨干就绪状态加载失败', zh_HANT: '事件骨幹就緒狀態載入失敗', ja: '準備状態を読み込めません', ko: '이벤트 백본 준비 상태를 로드할 수 없음', fr: 'Préparation indisponible' }),
      boundary: text({ en: 'TCRN owns event meaning, outbox, replay, tenant scope, and audit.', zh_HANS: 'TCRN 拥有事件语义、outbox、重放、租户范围和审计。', zh_HANT: 'TCRN 擁有事件語義、outbox、重放、租戶範圍和稽核。', ja: 'TCRN がイベント意味、outbox、再実行、テナント範囲、監査を所有します。', ko: 'TCRN이 이벤트 의미, outbox, 재실행, 테넌트 범위와 감사를 소유합니다.', fr: "TCRN possède le sens d'événement, l'outbox, la relecture, le périmètre tenant et l'audit." }),
      bridgeMode: text({ en: 'Bridge mode', zh_HANS: '桥接模式', zh_HANT: '橋接模式', ja: 'ブリッジモード', ko: '브리지 모드', fr: 'Mode bridge' }),
      disabledDefault: text({ en: 'NATS transport is disabled by default.', zh_HANS: 'NATS 传输默认关闭。', zh_HANT: 'NATS 傳輸預設關閉。', ja: 'NATS 転送は既定で無効です。', ko: 'NATS 전송은 기본 비활성입니다.', fr: 'Le transport NATS est désactivé par défaut.' }),
      registry: text({ en: 'Registry events', zh_HANS: '注册表事件', zh_HANT: '註冊表事件', ja: 'レジストリイベント', ko: '레지스트리 이벤트', fr: 'Événements registre' }),
      families: text({ en: 'families', zh_HANS: '个家族', zh_HANT: '個家族', ja: 'ファミリー', ko: '개 제품군', fr: 'familles' }),
      rawPayloadAccess: text({ en: 'Raw payload access', zh_HANS: '原始载荷访问', zh_HANT: '原始載荷存取', ja: '生ペイロードアクセス', ko: '원시 페이로드 접근', fr: 'Accès payload brut' }),
      noRawPayload: text({ en: 'No raw payload, token, or PII surface.', zh_HANS: '不暴露原始载荷、令牌或 PII。', zh_HANT: '不暴露原始載荷、權杖或 PII。', ja: '生ペイロード、トークン、PII は表示しません。', ko: '원시 페이로드, 토큰, PII 표면 없음.', fr: 'Aucun payload brut, jeton ou PII exposé.' }),
      streams: text({ en: 'Streams', zh_HANS: '流', zh_HANT: '串流', ja: 'ストリーム', ko: '스트림', fr: 'Streams' }),
      consumers: text({ en: 'Consumers', zh_HANS: '消费者', zh_HANT: '消費者', ja: 'コンシューマー', ko: '컨슈머', fr: 'Consommateurs' }),
      family: text({ en: 'Family', zh_HANS: '家族', zh_HANT: '家族', ja: 'ファミリー', ko: '제품군', fr: 'Famille' }),
      stream: text({ en: 'Stream', zh_HANS: '流', zh_HANT: '串流', ja: 'ストリーム', ko: '스트림', fr: 'Stream' }),
      status: text({ en: 'Status', zh_HANS: '状态', zh_HANT: '狀態', ja: '状態', ko: '상태', fr: 'Statut' }),
      dlq: text({ en: 'DLQ', zh_HANS: 'DLQ', zh_HANT: 'DLQ', ja: 'DLQ', ko: 'DLQ', fr: 'DLQ' }),
      queue: text({ en: 'Queue', zh_HANS: '队列', zh_HANT: '佇列', ja: 'キュー', ko: '큐', fr: 'File' }),
      consumer: text({ en: 'Consumer', zh_HANS: '消费者', zh_HANT: '消費者', ja: 'コンシューマー', ko: '컨슈머', fr: 'Consommateur' }),
      classification: text({ en: 'Classification', zh_HANS: '分类', zh_HANT: '分類', ja: '分類', ko: '분류', fr: 'Classification' }),
    },
    familyLabel: (family: string) => text(familyCopy[family] ?? { en: family }),
  };
}
