// SPDX-License-Identifier: Apache-2.0
// Global configuration seed data

import { PrismaClient } from '../../src/platform/prisma/client';

import { createLocalizedText } from '../../../shared/src/constants/locale';

export async function seedGlobalConfig(prisma: PrismaClient) {
  console.log('  → Seeding global configuration...');

  const configs = [
    {
      key: 'system.version',
      value: { version: '0.1.0', buildDate: new Date().toISOString() },
      description: 'System version information',
    },
    {
      key: 'system.maintenance',
      value: { enabled: false, message: null, allowedIps: [] },
      description: 'Maintenance mode configuration',
    },
    {
      key: 'system.baseDomain',
      value: { domain: 'tcrn.app' },
      description: 'Base domain for system subdomains (e.g., {talentCode}.m.{domain})',
    },
    {
      key: 'security.password_policy',
      value: {
        minLength: 8,
        requireUppercase: true,
        requireLowercase: true,
        requireNumber: true,
        requireSpecial: true,
        maxAgeDays: 90,
        historyCount: 5,
      },
      description: 'Password policy settings',
    },
    {
      key: 'security.session',
      value: {
        accessTokenExpiresIn: '15m',
        refreshTokenExpiresIn: '12h',
        maxConcurrentSessions: 5,
      },
      description: 'Session configuration',
    },
    {
      key: 'security.rate_limit',
      value: {
        global: { points: 100, duration: 60 },
        login: { points: 5, duration: 300 },
        api: { points: 200, duration: 60 },
      },
      description: 'Rate limiting configuration',
    },
    {
      key: 'feature_flags',
      value: {
        pii_encryption: true,
        totp_2fa: true,
        external_homepage: true,
        marshmallow: true,
        report_export: true,
        bulk_import: true,
      },
      description: 'Feature flags',
    },
    {
      key: 'dictionaries.profile_types',
      value: [
        { code: 'individual', name: createLocalizedText({
          en: 'Individual',
          zh_HANS: '个人',
          zh_HANT: '个人',
          ja: '個人',
          ko: 'Individual',
          fr: 'Individual',
        }), },
        { code: 'company', name: createLocalizedText({
          en: 'Company',
          zh_HANS: '企业',
          zh_HANT: '企业',
          ja: '法人',
          ko: 'Company',
          fr: 'Company',
        }), },
      ],
      description: 'Profile type dictionary',
    },
    {
      key: 'dictionaries.genders',
      value: [
        { code: 'male', name: createLocalizedText({
          en: 'Male',
          zh_HANS: '男',
          zh_HANT: '男',
          ja: '男性',
          ko: 'Male',
          fr: 'Male',
        }), },
        { code: 'female', name: createLocalizedText({
          en: 'Female',
          zh_HANS: '女',
          zh_HANT: '女',
          ja: '女性',
          ko: 'Female',
          fr: 'Female',
        }), },
        { code: 'other', name: createLocalizedText({
          en: 'Other',
          zh_HANS: '其他',
          zh_HANT: '其他',
          ja: 'その他',
          ko: 'Other',
          fr: 'Other',
        }), },
        { code: 'prefer_not_to_say', name: createLocalizedText({
          en: 'Prefer not to say',
          zh_HANS: '不愿透露',
          zh_HANT: '不愿透露',
          ja: '回答しない',
          ko: 'Prefer not to say',
          fr: 'Prefer not to say',
        }), },
      ],
      description: 'Gender dictionary',
    },
    {
      key: 'dictionaries.languages',
      value: [
        { code: 'en', name: createLocalizedText({
          en: 'English',
          zh_HANS: '英语',
          zh_HANT: '英语',
          ja: '英語',
          ko: 'English',
          fr: 'English',
        }), },
        { code: 'zh', name: createLocalizedText({
          en: 'Chinese',
          zh_HANS: '中文',
          zh_HANT: '中文',
          ja: '中国語',
          ko: 'Chinese',
          fr: 'Chinese',
        }), },
        { code: 'ja', name: createLocalizedText({
          en: 'Japanese',
          zh_HANS: '日语',
          zh_HANT: '日语',
          ja: '日本語',
          ko: 'Japanese',
          fr: 'Japanese',
        }), },
        { code: 'ko', name: createLocalizedText({
          en: 'Korean',
          zh_HANS: '韩语',
          zh_HANT: '韩语',
          ja: '韓国語',
          ko: 'Korean',
          fr: 'Korean',
        }), },
        { code: 'es', name: createLocalizedText({
          en: 'Spanish',
          zh_HANS: '西班牙语',
          zh_HANT: '西班牙语',
          ja: 'スペイン語',
          ko: 'Spanish',
          fr: 'Spanish',
        }), },
        { code: 'fr', name: createLocalizedText({
          en: 'French',
          zh_HANS: '法语',
          zh_HANT: '法语',
          ja: 'フランス語',
          ko: 'French',
          fr: 'French',
        }), },
        { code: 'de', name: createLocalizedText({
          en: 'German',
          zh_HANS: '德语',
          zh_HANT: '德语',
          ja: 'ドイツ語',
          ko: 'German',
          fr: 'German',
        }), },
        { code: 'pt', name: createLocalizedText({
          en: 'Portuguese',
          zh_HANS: '葡萄牙语',
          zh_HANT: '葡萄牙语',
          ja: 'ポルトガル語',
          ko: 'Portuguese',
          fr: 'Portuguese',
        }), },
        { code: 'ru', name: createLocalizedText({
          en: 'Russian',
          zh_HANS: '俄语',
          zh_HANT: '俄语',
          ja: 'ロシア語',
          ko: 'Russian',
          fr: 'Russian',
        }), },
        { code: 'th', name: createLocalizedText({
          en: 'Thai',
          zh_HANS: '泰语',
          zh_HANT: '泰语',
          ja: 'タイ語',
          ko: 'Thai',
          fr: 'Thai',
        }), },
        { code: 'vi', name: createLocalizedText({
          en: 'Vietnamese',
          zh_HANS: '越南语',
          zh_HANT: '越南语',
          ja: 'ベトナム語',
          ko: 'Vietnamese',
          fr: 'Vietnamese',
        }), },
        { code: 'id', name: createLocalizedText({
          en: 'Indonesian',
          zh_HANS: '印尼语',
          zh_HANT: '印尼语',
          ja: 'インドネシア語',
          ko: 'Indonesian',
          fr: 'Indonesian',
        }), },
      ],
      description: 'Language dictionary',
    },
    {
      key: 'dictionaries.timezones',
      value: [
        { code: 'Asia/Tokyo', name: createLocalizedText({
          en: 'Tokyo (JST)',
          zh_HANS: 'Tokyo (JST)',
          zh_HANT: 'Tokyo (JST)',
          ja: 'Tokyo (JST)',
          ko: 'Tokyo (JST)',
          fr: 'Tokyo (JST)',
        }), offset: '+09:00' },
        { code: 'Asia/Shanghai', name: createLocalizedText({
          en: 'Shanghai (CST)',
          zh_HANS: 'Shanghai (CST)',
          zh_HANT: 'Shanghai (CST)',
          ja: 'Shanghai (CST)',
          ko: 'Shanghai (CST)',
          fr: 'Shanghai (CST)',
        }), offset: '+08:00' },
        { code: 'Asia/Hong_Kong', name: createLocalizedText({
          en: 'Hong Kong (HKT)',
          zh_HANS: 'Hong Kong (HKT)',
          zh_HANT: 'Hong Kong (HKT)',
          ja: 'Hong Kong (HKT)',
          ko: 'Hong Kong (HKT)',
          fr: 'Hong Kong (HKT)',
        }), offset: '+08:00' },
        { code: 'Asia/Taipei', name: createLocalizedText({
          en: 'Taipei (CST)',
          zh_HANS: 'Taipei (CST)',
          zh_HANT: 'Taipei (CST)',
          ja: 'Taipei (CST)',
          ko: 'Taipei (CST)',
          fr: 'Taipei (CST)',
        }), offset: '+08:00' },
        { code: 'Asia/Seoul', name: createLocalizedText({
          en: 'Seoul (KST)',
          zh_HANS: 'Seoul (KST)',
          zh_HANT: 'Seoul (KST)',
          ja: 'Seoul (KST)',
          ko: 'Seoul (KST)',
          fr: 'Seoul (KST)',
        }), offset: '+09:00' },
        { code: 'Asia/Singapore', name: createLocalizedText({
          en: 'Singapore (SGT)',
          zh_HANS: 'Singapore (SGT)',
          zh_HANT: 'Singapore (SGT)',
          ja: 'Singapore (SGT)',
          ko: 'Singapore (SGT)',
          fr: 'Singapore (SGT)',
        }), offset: '+08:00' },
        { code: 'America/Los_Angeles', name: createLocalizedText({
          en: 'Los Angeles (PST)',
          zh_HANS: 'Los Angeles (PST)',
          zh_HANT: 'Los Angeles (PST)',
          ja: 'Los Angeles (PST)',
          ko: 'Los Angeles (PST)',
          fr: 'Los Angeles (PST)',
        }), offset: '-08:00' },
        { code: 'America/New_York', name: createLocalizedText({
          en: 'New York (EST)',
          zh_HANS: 'New York (EST)',
          zh_HANT: 'New York (EST)',
          ja: 'New York (EST)',
          ko: 'New York (EST)',
          fr: 'New York (EST)',
        }), offset: '-05:00' },
        { code: 'Europe/London', name: createLocalizedText({
          en: 'London (GMT)',
          zh_HANS: 'London (GMT)',
          zh_HANT: 'London (GMT)',
          ja: 'London (GMT)',
          ko: 'London (GMT)',
          fr: 'London (GMT)',
        }), offset: '+00:00' },
        { code: 'Europe/Paris', name: createLocalizedText({
          en: 'Paris (CET)',
          zh_HANS: 'Paris (CET)',
          zh_HANT: 'Paris (CET)',
          ja: 'Paris (CET)',
          ko: 'Paris (CET)',
          fr: 'Paris (CET)',
        }), offset: '+01:00' },
        { code: 'Australia/Sydney', name: createLocalizedText({
          en: 'Sydney (AEST)',
          zh_HANS: 'Sydney (AEST)',
          zh_HANT: 'Sydney (AEST)',
          ja: 'Sydney (AEST)',
          ko: 'Sydney (AEST)',
          fr: 'Sydney (AEST)',
        }), offset: '+10:00' },
        { code: 'UTC', name: createLocalizedText({
          en: 'UTC',
          zh_HANS: 'UTC',
          zh_HANT: 'UTC',
          ja: 'UTC',
          ko: 'UTC',
          fr: 'UTC',
        }), offset: '+00:00' },
      ],
      description: 'Timezone dictionary',
    },
    {
      key: 'dictionaries.countries',
      value: [
        { code: 'JP', name: createLocalizedText({
          en: 'Japan',
          zh_HANS: '日本',
          zh_HANT: '日本',
          ja: '日本',
          ko: 'Japan',
          fr: 'Japan',
        }), },
        { code: 'CN', name: createLocalizedText({
          en: 'China',
          zh_HANS: '中国',
          zh_HANT: '中国',
          ja: '中国',
          ko: 'China',
          fr: 'China',
        }), },
        { code: 'TW', name: createLocalizedText({
          en: 'Taiwan',
          zh_HANS: '台湾',
          zh_HANT: '台湾',
          ja: '台湾',
          ko: 'Taiwan',
          fr: 'Taiwan',
        }), },
        { code: 'HK', name: createLocalizedText({
          en: 'Hong Kong',
          zh_HANS: '香港',
          zh_HANT: '香港',
          ja: '香港',
          ko: 'Hong Kong',
          fr: 'Hong Kong',
        }), },
        { code: 'KR', name: createLocalizedText({
          en: 'South Korea',
          zh_HANS: '韩国',
          zh_HANT: '韩国',
          ja: '韓国',
          ko: 'South Korea',
          fr: 'South Korea',
        }), },
        { code: 'US', name: createLocalizedText({
          en: 'United States',
          zh_HANS: '美国',
          zh_HANT: '美国',
          ja: 'アメリカ',
          ko: 'United States',
          fr: 'United States',
        }), },
        { code: 'GB', name: createLocalizedText({
          en: 'United Kingdom',
          zh_HANS: '英国',
          zh_HANT: '英国',
          ja: 'イギリス',
          ko: 'United Kingdom',
          fr: 'United Kingdom',
        }), },
        { code: 'DE', name: createLocalizedText({
          en: 'Germany',
          zh_HANS: '德国',
          zh_HANT: '德国',
          ja: 'ドイツ',
          ko: 'Germany',
          fr: 'Germany',
        }), },
        { code: 'FR', name: createLocalizedText({
          en: 'France',
          zh_HANS: '法国',
          zh_HANT: '法国',
          ja: 'フランス',
          ko: 'France',
          fr: 'France',
        }), },
        { code: 'AU', name: createLocalizedText({
          en: 'Australia',
          zh_HANS: '澳大利亚',
          zh_HANT: '澳大利亚',
          ja: 'オーストラリア',
          ko: 'Australia',
          fr: 'Australia',
        }), },
        { code: 'SG', name: createLocalizedText({
          en: 'Singapore',
          zh_HANS: '新加坡',
          zh_HANT: '新加坡',
          ja: 'シンガポール',
          ko: 'Singapore',
          fr: 'Singapore',
        }), },
        { code: 'MY', name: createLocalizedText({
          en: 'Malaysia',
          zh_HANS: '马来西亚',
          zh_HANT: '马来西亚',
          ja: 'マレーシア',
          ko: 'Malaysia',
          fr: 'Malaysia',
        }), },
        { code: 'TH', name: createLocalizedText({
          en: 'Thailand',
          zh_HANS: '泰国',
          zh_HANT: '泰国',
          ja: 'タイ',
          ko: 'Thailand',
          fr: 'Thailand',
        }), },
        { code: 'VN', name: createLocalizedText({
          en: 'Vietnam',
          zh_HANS: '越南',
          zh_HANT: '越南',
          ja: 'ベトナム',
          ko: 'Vietnam',
          fr: 'Vietnam',
        }), },
        { code: 'ID', name: createLocalizedText({
          en: 'Indonesia',
          zh_HANS: '印度尼西亚',
          zh_HANT: '印度尼西亚',
          ja: 'インドネシア',
          ko: 'Indonesia',
          fr: 'Indonesia',
        }), },
        { code: 'PH', name: createLocalizedText({
          en: 'Philippines',
          zh_HANS: '菲律宾',
          zh_HANT: '菲律宾',
          ja: 'フィリピン',
          ko: 'Philippines',
          fr: 'Philippines',
        }), },
      ],
      description: 'Country dictionary',
    },
  ];

  for (const config of configs) {
    await prisma.globalConfig.upsert({
      where: { key: config.key },
      update: { value: config.value, description: config.description },
      create: config,
    });
  }

  console.log(`    ✓ Created ${configs.length} global configs`);
}
