// © 2026 月球厨师莱恩 (TPMOONCHEFRYAN) – PolyForm Noncommercial License
// Social platform seed data

import { PrismaClient } from '@prisma/client';

export async function seedSocialPlatforms(prisma: PrismaClient) {
  console.log('  → Seeding social platforms...');

  const platforms = [
    {
      code: 'BILIBILI',
      nameEn: 'Bilibili',
      nameZh: '哔哩哔哩',
      nameJa: 'ビリビリ',
      displayName: 'bilibili',
      iconUrl: '/icons/platforms/bilibili.svg',
      baseUrl: 'https://www.bilibili.com',
      profileUrlTemplate: 'https://space.bilibili.com/{uid}',
      color: '#00A1D6',
      sortOrder: 1,
    },
    {
      code: 'YOUTUBE',
      nameEn: 'YouTube',
      nameZh: 'YouTube',
      nameJa: 'YouTube',
      displayName: 'YouTube',
      iconUrl: '/icons/platforms/youtube.svg',
      baseUrl: 'https://www.youtube.com',
      profileUrlTemplate: 'https://www.youtube.com/channel/{uid}',
      color: '#FF0000',
      sortOrder: 2,
    },
    {
      code: 'TWITCH',
      nameEn: 'Twitch',
      nameZh: 'Twitch',
      nameJa: 'Twitch',
      displayName: 'Twitch',
      iconUrl: '/icons/platforms/twitch.svg',
      baseUrl: 'https://www.twitch.tv',
      profileUrlTemplate: 'https://www.twitch.tv/{uid}',
      color: '#9146FF',
      sortOrder: 3,
    },
    {
      code: 'TWITTER',
      nameEn: 'X (Twitter)',
      nameZh: 'X (推特)',
      nameJa: 'X (Twitter)',
      displayName: 'X',
      iconUrl: '/icons/platforms/x.svg',
      baseUrl: 'https://x.com',
      profileUrlTemplate: 'https://x.com/{uid}',
      color: '#000000',
      sortOrder: 4,
    },
    {
      code: 'TIKTOK',
      nameEn: 'TikTok',
      nameZh: 'TikTok',
      nameJa: 'TikTok',
      displayName: 'TikTok',
      iconUrl: '/icons/platforms/tiktok.svg',
      baseUrl: 'https://www.tiktok.com',
      profileUrlTemplate: 'https://www.tiktok.com/@{uid}',
      color: '#000000',
      sortOrder: 5,
    },
    {
      code: 'DOUYIN',
      nameEn: 'Douyin',
      nameZh: '抖音',
      nameJa: 'Douyin',
      displayName: '抖音',
      iconUrl: '/icons/platforms/douyin.svg',
      baseUrl: 'https://www.douyin.com',
      profileUrlTemplate: 'https://www.douyin.com/user/{uid}',
      color: '#161823',
      sortOrder: 6,
    },
    {
      code: 'INSTAGRAM',
      nameEn: 'Instagram',
      nameZh: 'Instagram',
      nameJa: 'Instagram',
      displayName: 'Instagram',
      iconUrl: '/icons/platforms/instagram.svg',
      baseUrl: 'https://www.instagram.com',
      profileUrlTemplate: 'https://www.instagram.com/{uid}',
      color: '#E4405F',
      sortOrder: 7,
    },
    {
      code: 'WEIBO',
      nameEn: 'Weibo',
      nameZh: '微博',
      nameJa: 'Weibo',
      displayName: '微博',
      iconUrl: '/icons/platforms/weibo.svg',
      baseUrl: 'https://weibo.com',
      profileUrlTemplate: 'https://weibo.com/u/{uid}',
      color: '#E6162D',
      sortOrder: 8,
    },
    {
      code: 'XIAOHONGSHU',
      nameEn: 'Xiaohongshu',
      nameZh: '小红书',
      nameJa: '小紅書',
      displayName: '小红书',
      iconUrl: '/icons/platforms/xiaohongshu.svg',
      baseUrl: 'https://www.xiaohongshu.com',
      profileUrlTemplate: 'https://www.xiaohongshu.com/user/profile/{uid}',
      color: '#FE2C55',
      sortOrder: 9,
    },
    {
      code: 'FANBOX',
      nameEn: 'pixivFANBOX',
      nameZh: 'pixivFANBOX',
      nameJa: 'pixivFANBOX',
      displayName: 'FANBOX',
      iconUrl: '/icons/platforms/fanbox.svg',
      baseUrl: 'https://www.fanbox.cc',
      profileUrlTemplate: 'https://{uid}.fanbox.cc',
      color: '#0096FA',
      sortOrder: 10,
    },
    {
      code: 'PATREON',
      nameEn: 'Patreon',
      nameZh: 'Patreon',
      nameJa: 'Patreon',
      displayName: 'Patreon',
      iconUrl: '/icons/platforms/patreon.svg',
      baseUrl: 'https://www.patreon.com',
      profileUrlTemplate: 'https://www.patreon.com/{uid}',
      color: '#FF424D',
      sortOrder: 11,
    },
    {
      code: 'DISCORD',
      nameEn: 'Discord',
      nameZh: 'Discord',
      nameJa: 'Discord',
      displayName: 'Discord',
      iconUrl: '/icons/platforms/discord.svg',
      baseUrl: 'https://discord.com',
      profileUrlTemplate: null,
      color: '#5865F2',
      sortOrder: 12,
    },
    {
      code: 'AFDIAN',
      nameEn: 'Afdian',
      nameZh: '爱发电',
      nameJa: '愛発電',
      displayName: '爱发电',
      iconUrl: '/icons/platforms/afdian.svg',
      baseUrl: 'https://afdian.net',
      profileUrlTemplate: 'https://afdian.net/a/{uid}',
      color: '#946CE6',
      sortOrder: 13,
    },
    {
      code: 'NICONICO',
      nameEn: 'Niconico',
      nameZh: 'Niconico',
      nameJa: 'ニコニコ',
      displayName: 'ニコニコ',
      iconUrl: '/icons/platforms/niconico.svg',
      baseUrl: 'https://www.nicovideo.jp',
      profileUrlTemplate: 'https://www.nicovideo.jp/user/{uid}',
      color: '#252525',
      sortOrder: 14,
    },
    {
      code: 'BOOTH',
      nameEn: 'BOOTH',
      nameZh: 'BOOTH',
      nameJa: 'BOOTH',
      displayName: 'BOOTH',
      iconUrl: '/icons/platforms/booth.svg',
      baseUrl: 'https://booth.pm',
      profileUrlTemplate: 'https://{uid}.booth.pm',
      color: '#FC4D50',
      sortOrder: 15,
    },
  ];

  for (const platform of platforms) {
    await prisma.socialPlatform.upsert({
      where: { code: platform.code },
      update: platform,
      create: platform,
    });
  }

  console.log(`    ✓ Created ${platforms.length} social platforms`);
}
