// SPDX-License-Identifier: Apache-2.0
// Social platform seed data

import { PrismaClient } from '../../src/platform/prisma/client';

import { createLocalizedText } from '../../../shared/src/constants/locale';

export async function seedSocialPlatforms(prisma: PrismaClient) {
  console.log('  → Seeding social platforms...');

  const platforms = [
    {
      code: 'BILIBILI',
      name: createLocalizedText({
        en: 'Bilibili',
        zh_HANS: '哔哩哔哩',
        zh_HANT: '哔哩哔哩',
        ja: 'ビリビリ',
        ko: 'Bilibili',
        fr: 'Bilibili',
      }),
      displayName: 'bilibili',
      iconUrl: '/icons/platforms/bilibili.svg',
      baseUrl: 'https://www.bilibili.com',
      profileUrlTemplate: 'https://space.bilibili.com/{uid}',
      color: '#00A1D6',
      sortOrder: 1,
    },
    {
      code: 'YOUTUBE',
      name: createLocalizedText({
        en: 'YouTube',
        zh_HANS: 'YouTube',
        zh_HANT: 'YouTube',
        ja: 'YouTube',
        ko: 'YouTube',
        fr: 'YouTube',
      }),
      displayName: 'YouTube',
      iconUrl: '/icons/platforms/youtube.svg',
      baseUrl: 'https://www.youtube.com',
      profileUrlTemplate: 'https://www.youtube.com/channel/{uid}',
      color: '#FF0000',
      sortOrder: 2,
    },
    {
      code: 'TWITCH',
      name: createLocalizedText({
        en: 'Twitch',
        zh_HANS: 'Twitch',
        zh_HANT: 'Twitch',
        ja: 'Twitch',
        ko: 'Twitch',
        fr: 'Twitch',
      }),
      displayName: 'Twitch',
      iconUrl: '/icons/platforms/twitch.svg',
      baseUrl: 'https://www.twitch.tv',
      profileUrlTemplate: 'https://www.twitch.tv/{uid}',
      color: '#9146FF',
      sortOrder: 3,
    },
    {
      code: 'TWITTER',
      name: createLocalizedText({
        en: 'X (Twitter)',
        zh_HANS: 'X (推特)',
        zh_HANT: 'X (推特)',
        ja: 'X (Twitter)',
        ko: 'X (Twitter)',
        fr: 'X (Twitter)',
      }),
      displayName: 'X',
      iconUrl: '/icons/platforms/x.svg',
      baseUrl: 'https://x.com',
      profileUrlTemplate: 'https://x.com/{uid}',
      color: '#000000',
      sortOrder: 4,
    },
    {
      code: 'TIKTOK',
      name: createLocalizedText({
        en: 'TikTok',
        zh_HANS: 'TikTok',
        zh_HANT: 'TikTok',
        ja: 'TikTok',
        ko: 'TikTok',
        fr: 'TikTok',
      }),
      displayName: 'TikTok',
      iconUrl: '/icons/platforms/tiktok.svg',
      baseUrl: 'https://www.tiktok.com',
      profileUrlTemplate: 'https://www.tiktok.com/@{uid}',
      color: '#000000',
      sortOrder: 5,
    },
    {
      code: 'DOUYIN',
      name: createLocalizedText({
        en: 'Douyin',
        zh_HANS: '抖音',
        zh_HANT: '抖音',
        ja: 'Douyin',
        ko: 'Douyin',
        fr: 'Douyin',
      }),
      displayName: '抖音',
      iconUrl: '/icons/platforms/douyin.svg',
      baseUrl: 'https://www.douyin.com',
      profileUrlTemplate: 'https://www.douyin.com/user/{uid}',
      color: '#161823',
      sortOrder: 6,
    },
    {
      code: 'INSTAGRAM',
      name: createLocalizedText({
        en: 'Instagram',
        zh_HANS: 'Instagram',
        zh_HANT: 'Instagram',
        ja: 'Instagram',
        ko: 'Instagram',
        fr: 'Instagram',
      }),
      displayName: 'Instagram',
      iconUrl: '/icons/platforms/instagram.svg',
      baseUrl: 'https://www.instagram.com',
      profileUrlTemplate: 'https://www.instagram.com/{uid}',
      color: '#E4405F',
      sortOrder: 7,
    },
    {
      code: 'WEIBO',
      name: createLocalizedText({
        en: 'Weibo',
        zh_HANS: '微博',
        zh_HANT: '微博',
        ja: 'Weibo',
        ko: 'Weibo',
        fr: 'Weibo',
      }),
      displayName: '微博',
      iconUrl: '/icons/platforms/weibo.svg',
      baseUrl: 'https://weibo.com',
      profileUrlTemplate: 'https://weibo.com/u/{uid}',
      color: '#E6162D',
      sortOrder: 8,
    },
    {
      code: 'XIAOHONGSHU',
      name: createLocalizedText({
        en: 'Xiaohongshu',
        zh_HANS: '小红书',
        zh_HANT: '小红书',
        ja: '小紅書',
        ko: 'Xiaohongshu',
        fr: 'Xiaohongshu',
      }),
      displayName: '小红书',
      iconUrl: '/icons/platforms/xiaohongshu.svg',
      baseUrl: 'https://www.xiaohongshu.com',
      profileUrlTemplate: 'https://www.xiaohongshu.com/user/profile/{uid}',
      color: '#FE2C55',
      sortOrder: 9,
    },
    {
      code: 'FANBOX',
      name: createLocalizedText({
        en: 'pixivFANBOX',
        zh_HANS: 'pixivFANBOX',
        zh_HANT: 'pixivFANBOX',
        ja: 'pixivFANBOX',
        ko: 'pixivFANBOX',
        fr: 'pixivFANBOX',
      }),
      displayName: 'FANBOX',
      iconUrl: '/icons/platforms/fanbox.svg',
      baseUrl: 'https://www.fanbox.cc',
      profileUrlTemplate: 'https://{uid}.fanbox.cc',
      color: '#0096FA',
      sortOrder: 10,
    },
    {
      code: 'PATREON',
      name: createLocalizedText({
        en: 'Patreon',
        zh_HANS: 'Patreon',
        zh_HANT: 'Patreon',
        ja: 'Patreon',
        ko: 'Patreon',
        fr: 'Patreon',
      }),
      displayName: 'Patreon',
      iconUrl: '/icons/platforms/patreon.svg',
      baseUrl: 'https://www.patreon.com',
      profileUrlTemplate: 'https://www.patreon.com/{uid}',
      color: '#FF424D',
      sortOrder: 11,
    },
    {
      code: 'DISCORD',
      name: createLocalizedText({
        en: 'Discord',
        zh_HANS: 'Discord',
        zh_HANT: 'Discord',
        ja: 'Discord',
        ko: 'Discord',
        fr: 'Discord',
      }),
      displayName: 'Discord',
      iconUrl: '/icons/platforms/discord.svg',
      baseUrl: 'https://discord.com',
      profileUrlTemplate: null,
      color: '#5865F2',
      sortOrder: 12,
    },
    {
      code: 'AFDIAN',
      name: createLocalizedText({
        en: 'Afdian',
        zh_HANS: '爱发电',
        zh_HANT: '爱发电',
        ja: '愛発電',
        ko: 'Afdian',
        fr: 'Afdian',
      }),
      displayName: '爱发电',
      iconUrl: '/icons/platforms/afdian.svg',
      baseUrl: 'https://afdian.net',
      profileUrlTemplate: 'https://afdian.net/a/{uid}',
      color: '#946CE6',
      sortOrder: 13,
    },
    {
      code: 'NICONICO',
      name: createLocalizedText({
        en: 'Niconico',
        zh_HANS: 'Niconico',
        zh_HANT: 'Niconico',
        ja: 'ニコニコ',
        ko: 'Niconico',
        fr: 'Niconico',
      }),
      displayName: 'ニコニコ',
      iconUrl: '/icons/platforms/niconico.svg',
      baseUrl: 'https://www.nicovideo.jp',
      profileUrlTemplate: 'https://www.nicovideo.jp/user/{uid}',
      color: '#252525',
      sortOrder: 14,
    },
    {
      code: 'BOOTH',
      name: createLocalizedText({
        en: 'BOOTH',
        zh_HANS: 'BOOTH',
        zh_HANT: 'BOOTH',
        ja: 'BOOTH',
        ko: 'BOOTH',
        fr: 'BOOTH',
      }),
      displayName: 'BOOTH',
      iconUrl: '/icons/platforms/booth.svg',
      baseUrl: 'https://booth.pm',
      profileUrlTemplate: 'https://{uid}.booth.pm',
      color: '#FC4D50',
      sortOrder: 15,
    },
  ];

  for (const platform of platforms) {
    await prisma.socialPlatform.upsert({
      where: { code: platform.code },
      update: platform,
      create: platform,
    });
  }

  console.log(`    ✓ Created ${platforms.length} social platforms`);
}
